### PR TITLE
Add /MP to all projects and configs in VS 2012 project files.

### PR DESCRIPTION
**Pull request by chief1983**
The diff might look nasty, but 'git diff -w origin/master' should show that it's mostly whitespace, and the only logical changes are the addition of the /MP setting to most of the projects' configs.  Freespace2 already has it across the board, so no changes are required to it.  This was tested while test compiling PR #104 after merging in master to that branch, to verify that AppVeyor was wrong about 2012 compilation being broken.  The /MP flag allowed Debug and Release SSE2 to build very quickly compared to previously.

### CODE REVIEW

**Comment by chief1983** [comment]
AppVeyor is stupid, this built fine in 2012 and doesn't affect 2013, no compile-reason not to merge this.

**Comment by chief1983** [comment]
Although apparently I do need to disable Partial Rebuilds for this to actually affect anything.

**Comment by asarium** [comment]
Are these changes complete or is it still missing the Partial Rebuild changes?

**Comment by chief1983** [comment]
Still missing, been on vacation.  I'll get back to this soon, prob next week.

**Comment by chief1983** [comment]
Disabled the Incremental Rebuilding for debug builds, to allow /MP to take effect on all builds.

**Pull request merged**
