### PR TITLE
TrueType support

### PR DESCRIPTION
**Pull request by asarium**
This PR adds support for using TrueType fonts for text rendering. This is implemented using the [NanoVG](https://github.com/memononen/nanovg) library which now handles most of the 2D operations FSO does. The OpenGL rendering backend of NanoVG requires at least OpenGL 2 which means that these changes also move the minimum OpenGL version to 2.

Another significant change is that the OpenGL function loading is now handled by [GLAD](https://github.com/Dav1dde/glad) which is a tool for generating a C header/source pair which automatically loads all the required functions from the OpenGL context.

### CODE REVIEW

**Comment by SamuelCho** [comment]
Several questions after looking at this

1) I'm really worried about side effects. I'd be cool if this was just a library that just prepared a bunch of textures and vertices for us then it would be up to us as to how we rendered it using our own graphics code. As I said before, the direct calls to OpenGL outside of our purview is something I'm worried about. Has this been tested with render targets? 

2) It also looks like this library sets it's own shaders which I guess is expected. But won't this essentially kill fixed function support? Not that I don't mind killing fixed function support but it's not a decision we should probably take likely. 

3) This seems to carry a lot of state changes between NVG end draw calls. Not only do we have to reset the state tracking for our own OpenGL backend, NVG itself has to flush the entire OpenGL state it changed. Any idea what the performance is like?

**Comment by asarium** [comment]
1. I tested it with render targets and it worked fine. One thing that could be done at some point is to provide our own implementation of the NanoVG rendering backend but as long as OpenGL is the only API we target, using the existing implementation would be the more efficient solution.

2. I should probably add a little more information to the PR. NanoVG requires at least OpenGL 2 anything without support for shaders is not going to be supported. Fixed-function will still be supported because OpenGL 2 still allowed that.

3. I have not done any extensive performance tests but I also haven't encountered any significant performance regressions while testing.

**Comment by SamuelCho** [comment]
How are modelview and projection matrices handled? Are viewports handled okay? How is blending, depth modes, culling, and other OpenGL states handled with NanoVG?

I definitely feel like an asshole being anal retentive about all this. But I hope you understand where I'm coming from. In the future, I think I want to put some more rules on integrating external libraries. One of which should be that they not make unsolicited graphics API calls on their own. I feel NanoVG is good for small OpenGL apps and games but on a codebase and game engine as complex as ours, I really don't think it's a good idea. But I'll approve this pull request whenever it's ready regardless.

**Comment by asarium** [comment]
Modelview and projection matrices are not used, NanoVG handles that by itself.
The various states are controlled via the usual `gl*` calls. I made sure that our state tracker is updates with the new values after NanoVG is done rendering so we don't end up in an inconsistent state.

I understand why you are reluctant to add this library. It would be worse if this library was some sort of closed source black box but it's not. The source code is included in the FSO code base and we can change it if we find bugs. We could even use our own state tracker for changing the OpenGL state which would reduce the number of state changes. I won't do that for the initial merge but at some point I may end up doing it.

Sidenote: Since I have changed the way OpenGL functions are loaded your OpenGL Core branch will most likely be broken by these changes. The program I use for generating the loader can also generate a loader for OpenGL 3 Core so if you want I can help you with setting that up once this is merged.

I just rebased the branch onto the latest master and cleaned up the history. Once CI passes this can be merged.

**Comment by SamuelCho** [comment]
Yeah the merge will be pretty ugly with the OpenGL Core stuff but I think I'll be able to power through it on a weekend with a lot of coffee. 

I definitely would have preferred the GLAD stuff to be in a seperate merge but it's honestly not that big of a deal. I think I'll be okay integrating the GLAD stuff with what I have.

**Comment by asarium** [comment]
I would also have preferred a separate GLAD merge but it's too late for that now.

**Comment by SamuelCho** [comment]
Do you mind if I generate a new glad header and loader with 4.5 compatibility functions and extensions? The loader currently in the projects generates stuff up to OpenGL 2 but I think it won't hurt to have a 4.5 compatibility loader even if the OpenGL context doesn't match. Whatever gets loaded gets loaded and what doesn't doesn't. GLAD seems to be smart enough to not load functions it shouldn't be loading.

**Comment by asarium** [comment]
I don't think that's a good idea. We already have issues on Linux with using OpenGL 3 shader features in a compatibility profile. Using a loader with 4.5 features for the compatibility profile would only make those issues worse because people would use the functions without realizing that it might break other platforms.

**Comment by SamuelCho** [comment]
The shader issues are largely because we don't properly declare which #extension and #version the shader needs. My OpenGL Core changes fixes that. Compatibility issues outside of shaders aren't really a problem so long as the graphics calls are being safeguarded with checks to which version and extensions are available.

**Comment by asarium** [comment]
Another issue is that Mesa simply doesn't allow the usage of OpenGL 3 shaders in a compatibility profile. Why exactly do you need a 4.5 loader anyway? We aren't using those features and if we do then it should use the extension providing the functionality instead of relying on a 4.5 compatibility profile which may not even exist (e.g. Mesa only supports it up to OpenGL 3.0).

**Comment by SamuelCho** [comment]
I need a loader that will be able to load at least 3.2 functions while also not breaking the legacy fixed function code.

**Comment by asarium** [comment]
Which functions? If they have an ARB extension then we could use that instead.

**Comment by SamuelCho** [comment]
I'm trying to get my OpenGL Core changes working with your merge. What do you mean I need to use an ARB extension?

**Comment by asarium** [comment]
Oh you want the OpenGL Core functions! I though you wanted a compatibility profile. Of course I can generate a loader for OpenGL 3.2 Core profile.

**Comment by SamuelCho** [comment]
Yeah but if you just generate a loader for the OpenGL 3.2 Core profile, that breaks all the fixed function calls that are currently in the code. I haven't removed them yet, nor have I even decided if it's prudent to just remove them entirely, which is why I need a header with those functions to at least let the code compile. Which is why I'm looking to generate a compatibility header.

**Comment by asarium** [comment]
Ok, I misunderstood for what you wanted to use it. I think we agreed that the fixed-function stuff would be removed because we can't use it in a core context.

Anyway, here is a 4.5 compatibility loader. It should be a drop in replacement of the current loader: [glad.zip](https://github.com/scp-fs2open/fs2open.github.com/files/401201/glad.zip)

**Comment by SamuelCho** [comment]
Yeah I'm sorry if I wasn't clear. The fixed function situation is awkward because I'm afraid there will be a large percentage of users that will have problems even with the newly unfucked Core-compatible shaders. I did test it with my laptop but that has an Intel HD 5500 so who knows what it's like on an older Intel HD 3000 or 2000. I'd rather mothball and keep the fixed pipeline code in for now albeit unused. Hopefully no complications will come from this once the OpenGL Core changes are pushed upstream, but if they do, I will have to make the forced fixed function launcher flag to  force the game to create a 2.1 compatibility context. I really hope we won't come to that but that's my contingency plan.

**Comment by asarium** [comment]
How would that coexistence work? For the core profile we would need a core profile GLAD loader which doesn't include all the fixed-function stuff we are currently using so we can't keep the code in. If we use a compatibility loader on a core profile we risk incompatibilities because some functions may not be available.

Why would we keep the fixed function code at all? With the recent move to OpenGL 2 a GPU with shader support is absolutely required by FSO and from there it isn't a big step to the OpenGL core profile. I think at this point we should just drop the fixed function renderer. It sucks for people with an old GPU but we can't keep supporting two fundamentally different graphics concepts.

**Comment by SamuelCho** [comment]
If that's the position you want to take, I'll take it with you. I just don't want to be standing alone if there happens to be a deluge of complaints of people unable to run FSO anymore. :D

**Comment by asarium** [comment]
I'm pretty sure @The-E said at some point that we don't need the fixed function renderer anymore but I think that was on IRC so I can't find a direct quote of that. Besides, the [Steam Hardware survey](http://store.steampowered.com/hwsurvey/videocard/) shows that only ~4% of Steam users have a GPU with DirectX support < 9 (which is AFAIK the same feature level as OpenGL 3) so a lot of people already have a GPU capable of supporting OpenGL 3.

And even if the new update breaks the newer versions of FSO for someone, they still have the current version and they can play everything with it.

**Comment by The-E** [comment]
I think setting OpenGL 3 Core as the required minimum is a reasonable thing to do these days. While it would be nice to retain compatibility with hardware too old to handle shaders, I do consider it a "nice to have" thing, not something we actually need (I know certain people who would disagree, but ... well). If maintaining that code path imposes an undue burden on us as coders for very little benefit, then we should drop it like it's hot.

**Comment by MageKing17** [comment]
I'm pretty sure moving to a Core profile gives us more than we lose by ditching outdated OpenGL versions anyway.

**Pull request merged**
