### PR TITLE
Clean out player t_plr before use

### PR DESCRIPTION
**Pull request by z64555**
* Directly reference t_plr instead of player* p
Should fix issue #4057

### CODE REVIEW

**Review by Goober5000 — COMMENTED** [review]
Was the `p = &t_plr;` line needed?  Because I fired up this branch and the first thing I got was a nullptr exception due to `this->p` being null here:
```
void pilotfile::plr_read_flags()
{
	// tips?
	p->tips = (int)handler->readUByte("tips");
```

**Comment by z64555** [comment]
*loud grumbling*

Yes, apparently it is needed because of the way that the rest of the file handler works.  I thought I could get away with omitting the assignment since in that function, it appears moot to be using a pointer when you could be referencing the object direct instead.

**Comment by notimaginative** [comment]
Why not just use a simple `p->reset();` and be done with it? Is there some reason that doesn't work?

**Comment by z64555** [comment]
> Why not just use a simple `p->reset();` and be done with it? Is there some reason that doesn't work?

If you wanted to go the minimalist route, yeah, it would work.

I felt the changes to using the local `t_plr` were an opportunity to try to organize/clean up `verify()` since it seems to be a bit sloppy.  I don't particularly like the way it sets the `player* p` as part of its interface, and then use functions to modify its members hiding the fact that `p` can't be omitted.

**Review by Goober5000 — APPROVED** [review]
Ok, this new PR shows the dialog when expected and doesn't show it when not expected.

**Pull request merged**
