### PR TITLE
Add capability to have a pure lua script

### PR DESCRIPTION
**Pull request by asarium**
This adds the capability to have a Lua script that does not need to use
our table syntax at all but instead defines the hooks by calling API
functions. This also makes it possible to add hook functions at runtime
if the script requires that.

### CODE REVIEW

**Comment by asarium** [comment]
How did you arrive at that conclusion? This is a strict addition of features. Table based scripts will be unaffected.

**Comment by MageKing17** [comment]
The removal of the ADE Debug code.

**Comment by asarium** [comment]
That code has been superseded by the code using the Lua internat stack trace long ago. It was not used or useful anymore.

**Comment by chief1983** [comment]
If they don't need to be fixed shouldn't we add the tidy-ignore comment to them at least?

**Comment by Goober5000** [comment]
Nah.  I just looked at them and they are trivial.

**Pull request merged**
