### PR TITLE
Physically based rendering

### PR DESCRIPTION
**Pull request by SamuelCho**
Introduces physically-based Blinn-Phong Fresnel lighting, roughness map support, high dynamic range tonemapping, and better bloom.

### CODE REVIEW

**Comment by chief1983** [comment]
Guessing the Mac issues with this won't be sorted until we move to Core?

**Comment by SamuelCho** [comment]
I'll take a look at PBR in Mac to see if I can immediately address anything.

**Comment by chief1983** [comment]
Well, if it helps, the first issue I saw on my machine (Radeon HD 6750M) was in the tech room, mediaVPs, looking at the Ulysses.  There was a line through the middle of the ship viewing area, and below the line was shader darker than above the line.  The cockpit wasn't rendering correctly either.  Didn't get much farther than that.

**Comment by SamuelCho** [comment]
Shadows probably aren't working. Try disabling shadows and see if that line disappears.

**Comment by chief1983** [comment]
Got rid of that line and shading, but the Ulysses still looks a bit odd, with a white translucent cockpit and some gray stripes instead of the usual blue-ish cockpit in 3.7.4.  Also, many other ships are rendering completely white in the tech room, such as the Hercules (except for glowpoints).  Log attached.
[fs2_open.log.txt](https://github.com/scp-fs2open/fs2open.github.com/files/350800/fs2_open.log.txt)

**Comment by asarium** [comment]
```
ERROR: 0:395: Invalid call of undeclared identifier 'textureCubeLod'
ERROR: 0:399: Use of undeclared identifier 'envColour'
ERROR: 0:400: Use of undeclared identifier 'envColour'
```
The shader fails to compile so visual artifacts are likely. Also, `OpenGL Version   : 2.1 ATI-1.42.11`. That's a very old OpenGL version so I guess it's missing quite a few required OpenGL extensions.

**Comment by chief1983** [comment]
Well, it's a bit older so I'm not surprised.  But perhaps we should be looking at making sure individual graphics features disable themselves more gracefully when they aren't available?  After toggling some things in the F3 lab, I narrowed it down to the specular maps that seem to be causing the issues I see now.  The Ulysses, Hercules, etc go back to mostly normal without that channel enabled.  If I enable -nospec and don't enable shadows the tech room ships all render pretty much OK.

**Comment by SamuelCho** [comment]
I didn't have a Mac during the time when I was working on the physically-based lighting code so I admit that I shortsightedly didn't test this code as soon as I got my Mac machine a couple weeks ago. I'll probably smoke out the compilation issues on my new machine when I get home tonight.

**Comment by SamuelCho** [comment]
My hunch was correct. It was tied to an extension that wasn't enabled. https://github.com/scp-fs2open/fs2open.github.com/pull/642

**Pull request merged**
