### PR TITLE
Math cleanup

### PR DESCRIPTION
**Pull request by PeterMitsis**
Cleans up some of the math code.
 - Removes unnecessary checks
 - Applies const and static keywords to facilitate in understanding scope and use
 - Caches or pre-calculates various expressions to prevent unnecessary runtime calculations

### CODE REVIEW

**Comment by Goober5000** [comment]
There are several problems with this commit.  Something this fundamental to the codebase should have had a more thorough review by several different people before being merged.  There are a lot of changes here and the math library affects a large part of the code.

In the first place, all of those places where if (mag <= 0.0f) was changed to if (mag == 0.0f) need to be changed back to their original form.  This can be seen in the following snippet of original code:

	if (mag1 <= 0.0f) {
		return 0.0f;
	}

	return fl_sqrt(mag1);

Negative vector magnitudes should never ever happen, but due to round-off errors every now and then you'll find a vector with an extremely small negative magnitude such as -0.0000000000003243.  The original code treated this as zero, but the new code will attempt to take the square root as a negative number.  The result is a rogue NaN that starts cascading through the game state and wreaking havoc.

Second, in vm_vector_2_matrix, the code below the comment "// This had been commented out, but that's bogus. Code below relies on a valid zvec." was taken out, but the comment was not changed to reflect this.  You now have an incorrect and comment which will mislead people trying to understand the code.

Third, the comment specifically states that removing the following code is bogus, yet this pull request removes that code!  Even worse, it doesn't even explain why!  Why is there no justification for removing the check that a previous code review had concluded was necessary?

Fourth, several other checks in vm_vector_2_matrix and vm_vector_2_matrix_norm are removed without explanation.  The pull request states that they are unnecessary, but does not elaborate.  A cursory review does not indicate why they are unnecessary, and in fact indicates that they are indeed necessary.

Fifth, various other checks in the code (such as in vm_extract_angles_matrix) may be unnecessary from a mathematical perspective, but from a programming perspective they make the code more efficient.

Sixth, this should have been broken into multiple pull requests.  The const-correctness changes appear good, but 90% of the rest needs to be reverted.

**Comment by chief1983** [comment]
Since it appears that this was reverted, what's the next task for it?  Break it up into several requests of more similar functionality?

**Comment by PeterMitsis** [comment]
Thanks for your feedback and review.  I agree with your decision about the necessity of reverting the patch set.

I think that there is some value in the proposed changes (but certainly not all).  I would certainly like to try to fix things up so that I can make a contribution to this project.

I certainly understand your concern about taking the square root of a negative number and propagating NaN's.  However, I fail to see how a negative magnitude can be achieved due to rounding errors.  This is not to say that I do not understand the concept of rounding errors, but rather how that even applies to this particular case.  In order to get a negative value when calculating a vector magnitude, a sign flip would be required which would really be more indicative of a hardware failure.  Perhaps this is due to ignorance on my part, but I have never seen the following documented anywhere with respect to floating point calculations:
    1. multiplication of a number with itself resulting in a negative number
    2. sum of a series of positive numbers resulting in a negative number
    3. a sqrt() that results in a negative number (unless the number is -0.0f)

If this patch set were to broken up into multiple sets, how would you like to see it done?  I ask because I would like to learn how to be a better part-time contributor to this project.

Aside.
It wasn't until after I submitted this patch set that I discovered the computational efficiency of using <, <=, >, and >= over == and != when it comes to floating point.  I admit that I regrettably failed to perform disassembly to compare the generated code before and after when I messed with the comparator operators.  It shant recur.

**Comment by Goober5000** [comment]
Sorry about the delayed response.  I went on vacation shortly after The E reverted the commit and haven't been able to follow up until now.

I certainly agree that there is value in these proposed changes, and I would be happy to see them merged back in after a bit more thorough of a review.  And I would also welcome your contributions to the project, as you've certainly put quite a bit of thought into the changes even if you made a few mistakes.  (In fact, my comment originally contained six bullet points.  I edited it to remove three of them after I discovered that you had sufficiently addressed my concerns in your commit messages.)

Regarding comparing the generated code of one set of operators versus another, that is a commendable investigation but rather more intensive than I had anticipated!  I had based my comments on first principles of software design, but if you have empirical data on operator performance, I would be very interested to see it.  I also appreciate the validation of my conclusion using an independent chain of reasoning. ;)

Regarding breaking the set into multiple requests, it should only be necessary to divide it according to high-level categories.  As I suggested above, the most important one should be isolating const-correctness in a pull request by itself.  Once reviewed for compilation problems and API suitability, that can be approved with a minimum of fuss.  The rest of the breakdown is more flexible.  It might actually be possible to get away with only the two pull requests, but it would be worth looking into making one pull request for each category (removal/refactor/cosmetic).

Regarding achieving a negative magnitude, it is not that I actually saw negative magnitudes being returned (for such an occurrence would be exceedingly difficult to notice) but rather that I recognized the pattern.  In the first place, Volition was checking for negative values already, and one should not gainsay a Volition design decision without a careful consideration of the factors involved.  In the second place, I had actually experienced the generation of NaNs in a work project involving taking the square root of the statistical variance (another variable which cannot be negative) to obtain the standard deviation.  Fortunately this incident was rather easier to spot because the values were directly saved to a spreadsheet, not used to propagate game state.  The solution was to treat very small negative values as equivalent to zero.  I therefore concluded that Volition had anticipated a similar problem and was engaging in defensive programming.

**Comment by PeterMitsis** [comment]
Regarding the generation of x86 code with respect to comparing floats using == and <= ...

Consider the following code ...

int equal(float x, float y)
{
    if (x == y)
        return 1;
    else
        return 0;
}

int less_or_equal(float x, float y)
{
    if (x <= y)
        return 1;
    else
        return 0;
}

On my system (Ubuntu 12.04, 64-bit) with the GCC 4.6.3 compiler,  this yields the following assembly code when built using ...

gcc -c if-equal.c -O2 -msse2 -o if-equal.o

0000000000400520 <equal>:
  400520:   31 d2                   xor    %edx,%edx
  400522:   b8 00 00 00 00          mov    $0x0,%eax
  400527:   0f 2e c1                ucomiss %xmm1,%xmm0
  40052a:   0f 9b c2                setnp  %dl
  40052d:   0f 44 c2                cmove  %edx,%eax
  400530:   c3                      retq
<snip> 

0000000000400540 <less_or_equal>:
  400540:   31 c0                   xor    %eax,%eax
  400542:   0f 2e c8                ucomiss %xmm0,%xmm1
  400545:   0f 93 c0                setae  %al
  400548:   c3                      retq
<snip>

One of the most obvious differences is that not only does less_or_equal() have fewer assembly instructions, it is also smaller in size.  At best, equal() might yield the same performance as less_or_equal().  However, based upon the dependencies between instructions, less_or_equal() would be expected to give slightly better performance for a smaller footprint.

**Comment by Goober5000** [comment]
Interesting.  Can you try the same thing with a hard-coded 0.0f?  Often constants will produce different code from variables.

**Comment by PeterMitsis** [comment]
Below, I have pasted the generated assembly for two more routines--these compare a variable against hard coded value--0.0f and 1.0f.  In the original samples I provided, the value we were comparing against was being passed into the routine so by the time we got into the routine the floating point values were already in the XMM registers (as per the ABI).  In the ones below, the routine has to get the hard coded value into the register, and that is where things differ.

The SSE instructions do not provide a mechanism for directly loading a constant into the XMM registers.  As a result, an x86 compiler will typically generate instructions that load the value from memory.  The value 0.0f is an exception to that rule as its hex representation is 0x00000000.  This allows the compiler to take a shortcut and fill the register with 0's by XOR'ing the register with itself.

0000000000400550 is_less_than_or_equal_to_zero:
  400550:   0f 57 c9                xorps  %xmm1,%xmm1
  400553:   31 c0                   xor    %eax,%eax
  400555:   0f 2e c8                ucomiss %xmm0,%xmm1
  400558:   0f 93 c0                setae  %al
  40055b:   c3                      retq
  40055c:   0f 1f 40 00             nopl   0x0(%rax)

0000000000400560 is_less_than_or_equal_to_one:
  400560:   f3 0f 10 0d 84 01 00    movss  0x184(%rip),%xmm1        # 4006ec <_IO_stdin_used+0x34>
  400567:   00
  400568:   31 c0                   xor    %eax,%eax
  40056a:   0f 2e c8                ucomiss %xmm0,%xmm1
  40056d:   0f 93 c0                setae  %al
  400570:   c3                      retq
  400571:   66 66 66 66 66 66 2e    data32 data32 data32 data32 data32 nopw %cs:0x0(%rax,%rax,1)
  400578:   0f 1f 84 00 00 00 00 
  40057f:   00 

If I remember correctly, the classic x86 FPU instruction set also has similar issues with respect to floating point constants.  However, it has a few dedicated instructions for pushing constants such as pi,  0.0f, 1.0f, and a couple of logs.

**Comment by Goober5000** [comment]
Cool.  Well I think that is probably enough exploring into the rabbit hole.  I see you're working on a new pull request for the static and const keywords.  Make another pull request for the optimizations and cleanup (sans the <= changes and the comment ninja'ing), and we can call this resolved.

**Pull request merged**
