### PR TITLE
Always use high resolution timers

### PR DESCRIPTION
**Pull request by asarium**
Currently the timer system uses `SDL_GetTick()` for keeping track of frametimes but that uses millisecond precision. `timer_get_fixed_seconds` converts that into a `fix` (aka 1/65536 of a second) which means that ~6 bits of information are completely useless. These changes always use the high precision timer which allows to get timer values with microsecond precision and that allows to use the remaining 6 bits of information in the `fix`.

I wanted to fix the timer issues at high framerates with this but it doesn't seem like that has changed with these changes. I decided to submit this anyway because it should improve the frametime computation a bit.

### CODE REVIEW

**Comment by MageKing17** [comment]
Most of the problem is with timestamps (which also have millisecond resolution, but made even worse by being affected by time compression) rather than the timers themselves, and this PR doesn't change timestamp-related code at all.

**Comment by asarium** [comment]
Good point. I think we changed that at some point to milliseconds because but now using a fix could be better. I'll try that.

**Comment by asarium** [comment]
I converted the timestamp code to use microseconds internally so that less precision is lost when incrementing the timestamp ticker.

**Comment by SamuelCho** [comment]
Should we even keep timer_get_microseconds()? I'd say just rename timer_get_high_res_microseconds to timer_get_microseconds(). When I wrote timer_get_high_res_microseconds(), I was concerned about rollover issues and therefore only made the profiler dependant on it. But if you think that's no longer a concern, just kill timer_get_microseconds and have high_res take its place.

**Comment by asarium** [comment]
I have removed `timer_get_microseconds()` and replaced it with the old high resolution variant.

**Comment by SamuelCho** [comment]
It looks like mveplayer and oggplayer are still using the old high_res_microseconds function variant.

**Comment by asarium** [comment]
The code was hidden inside Windows specific code blocks so the rename didn't catch that. I replaced that platform specific code with cross-platform compatible code since we now have a reliable microsecond timer available.

I tested video playback and all timing seems to be normal.

**Comment by chief1983** [comment]
As a post-mortem comment, I'd suggest that git grep always be used to verify a global rename performed through an IDE in the future.

**Comment by asarium** [comment]
Luckily we now have the CI servers to verify that a rename was done properly. I didn't know about `git grep` that seems to be very useful for the future...

**Pull request merged**
