### PR TITLE
More file types for data/config

### PR DESCRIPTION
**Pull request by X3N0-Life-Form**
Adds .tbl, .tbm, .xml and .csv to the list of supported /config file types.

### CODE REVIEW

**Comment by asarium** [comment]
GitHub is having a few issues which breaks the travis and probably also the appveyor builds. I'll restart them when that stuff is working again.

**Comment by asarium** [comment]
I restarted the CI builds since the DNS issues should be solved by now.

**Comment by asarium** [comment]
Have you tested if FSO is able to use the new file extensions properly?

**Comment by X3N0-Life-Form** [comment]
Just wiped a up a quick test script to double checked : All 4 new file types can be read, while the nighlty from oct. 17 can't find any of them.

**Comment by asarium** [comment]
Good, thank you for testing that.

**Pull request merged**
