### PR TITLE
Changed require exact los to track from the exact firing point instead of center

### PR DESCRIPTION
**Pull request by SelfGamer**
As this feature is very new, it's probably fine to change it instead of adding a new flag.
This change make the actual firing point of the turret / secondary bank matter and not just raycast center to center, which should help for large capital ships using this flag.
While it seems to work for me, I'd like some help with testing. Pinging @EatThePath, as he requested this change for a specific mission it seems.

### CODE REVIEW

**Comment by SelfGamer** [comment]
Made to draft to investigate if we can make beams respect this flag.
General change seems to have worked

**Comment by SelfGamer** [comment]
Seemed to work fine, with primaries now also respecting LoS

**Review by EatThePath — COMMENTED** [review]
I don't feel equipped to comment on the code quality itself, but I will say that I've tested this flag+branch on a handful of decently crowded missions, and as far as I can see it is stable and causes no noticeable behaviour changes outside of what it is supposed to.

**Review by Baezon — APPROVED** [review]
LGTM

**Pull request merged**
