### PR TITLE
Resolve CID 1093624

### PR DESCRIPTION
**Pull request by FSCyborg**
Instead of comparing the array, compare the first element.

### CODE REVIEW

**Comment by FSCyborg** [comment]
This one seems simple.  Could someone confirm that this makes logical check worthwhile?

**Comment by asarium** [comment]
Oh no, that's not how it works.
1. I am pretty sure that if should actually check the parameter for `NULL` as the contents of the name array are going to be overwritten anyway
2. Character comparision against `NULL` are a bad thing™ as `NULL` is meant for pointer checks and not for integral comparisions

**Comment by FSCyborg** [comment]
So it's completely useless.  Is there any way that we can actually check what it's trying to check.

**Comment by asarium** [comment]
I have no idea, my best guess would be that it's a typo and it should actually check `ìn_name` for `NULL` as that's the only thing that actually makes sense in this situation.

**Comment by FSCyborg** [comment]
Ok.  Let's close this sucker.

**Pull request closed without merging**
