### PR TITLE
Clarified a warning message about wave tresholds (Mantis 3153)

### PR DESCRIPTION
**Pull request by downwash**

### CODE REVIEW

**Comment by MageKing17** [comment]
While the clarification is good, I'd like to see FRED made unable to specify the invalid values in the first place.

**Comment by downwash** [comment]
Good point - fixed on the branch.

**Comment by asarium** [comment]
@MageKing17: Is there anything else that should be changed? IMO the code looks good.

**Comment by MageKing17** [comment]
Not that I can think of. :P

**Pull request merged**
