### PR TITLE
 Fix? Issue #1791

### PR DESCRIPTION
**Pull request by FSCyborg**
Requesting testing!  Looks like the simplest fix for this issue could be to add the checks for the flags to both branches of the involved if statement in aiturret.cpp .

#1791

### CODE REVIEW

**Comment by FSCyborg** [comment]
Sorry about the messy commit history.  Will try to avoid that in the future.

**Comment by chief1983** [comment]
You can clean up the commit history and force push over the branch to fix that if you want.  I'd recommend it even. Don't like reverts in a commit history.  Easiest way would be to cherry pick the last commit hash into a new branch based on master.

**Comment by FSCyborg** [comment]
Github is pretty much an obstacle course for newer coders. :|

I'll try to manage that.

**Comment by Goober5000** [comment]
Looks reasonable, but you should make sure that the commented `nprintf` remains next to the line it describes.

**Pull request closed without merging**
