### PR TITLE
add no-disabled-self-destruct ship flag

### PR DESCRIPTION
**Pull request by Goober5000**
Normally, ships whose weapons or engines subsystems are destroyed will self-destruct after 90 seconds if they are part of a wing (see ai_maybe_self_destruct).  This adds a ship flag to prevent that from happening.

### CODE REVIEW

**Comment by Karajorma** [comment]
Can you add this to Ship_flag_names so that the alter-ship-flag SEXP can be used with it please?

**Comment by MageKing17** [comment]
Seconded; also, I'm not fond of how cluttered that fred.rc diff is, but I know how much of a pain avoiding nonfunctional changes with the form editor.

Otherwise, looks fine to me; add the SEXP support and it should be good.

**Comment by Goober5000** [comment]
I think it's highly unlikely that anyone would ever want to use this during a mission; it's a configuration flag more than a transient flag.  But okay.

**Comment by Goober5000** [comment]
Merging due to review.

**Comment by Karajorma** [comment]
I don't disagree with you, but adding it to the list is so cheap that there is not really much of a reason not to do it.

**Pull request merged**
