### PR TITLE
Add built-in xstrs for SCP-added controls

### LINKED ISSUE #4611: New controls not translatable
New controls added by SCP are apparently not bound to any XSTR ID in strings.tbl and so cannot be translated.
It involves the following controls:
- Glide when pressed
- Toggle gliding
- Cycle primary weapon firing rate
- Top-down view
- Target padlock view
- Toggle auto pilote
- Cycle nav points

### PR DESCRIPTION
**Pull request by MjnMixael**
These controls, added by SCP were never given XSTRs for localization. This PR adds them. Fixes #4611

- 1799, Glide When Pressed
- 1800, Toggle Gliding
- 1801, Cycle Primary Weapon Firing Rate
- 1802, Top-Down View
- 1803, Target Padlock View
- 1804, Toggle Auto Pilot
- 1805, Cycle Nav Points
- 1806, Toggle HUD Drop Shadows

Note that built-in xstrs were required to be sequential and fit within a fixed sized array at the time that bug was reported. That is no longer the case and a deep dive to find unused xstr IDs is not necessary anymore.

### CODE REVIEW

**Review by BMagnu — APPROVED** [review]

**Review by TRBlount — CHANGES_REQUESTED** [review]
Putting this on hold until review for #5622 is covered.

**Comment by MjnMixael** [comment]
> Putting this on hold until review for #5622 is covered.

Already altered taking that PR into account

**Review by TRBlount — CHANGES_REQUESTED** [review]
With the final version of #5622 ready, the IDs need to be shifted back so 1774 is occupied. XSTR_SIZE can be left as is here.

**Comment by MjnMixael** [comment]
> With the final version of #5622 ready, the IDs need to be shifted back so 1774 is occupied. XSTR_SIZE can be left as is here.

done

**Review by TRBlount — APPROVED** [review]

**Pull request merged**
