### PR TITLE
Sync Antipodes

### PR DESCRIPTION
**Pull request by asarium**

### CODE REVIEW

**Comment by asarium** [comment]
Windows builds have been fixed but apparently the XCode project files have been broken by a previous sync (at least as far as I can tell). I cannot fix that because I don't have a Mac.

**Comment by The-E** [comment]
That's obviously not something we would want.

**Comment by asarium** [comment]
@The-E I agree. I hope someone can figure this out soon.

I merged the latest master into this again to get the APNG changes. This required some changes to the Cursor class because now a bitmap handle is required for getting the right frame.

@niffiwan Could you take a look at cursor.cpp and check if I used `bm_get_anim_frame` correctly?

**Comment by The-E** [comment]
I think @SamuelCho also did some work on this

**Comment by niffiwan** [comment]
@asarium yep, that use of `bm_get_anim_frame` looks fine.

**Comment by asarium** [comment]
@niffiwan Good, thanks for looking at it.

**Comment by chief1983** [comment]
Merging in my PR to this branch should fix this PR's building on Mac.

**Comment by asarium** [comment]
PR merged, let's see what Travis says about it.

**Comment by asarium** [comment]
I merged master into this PR again so it includes the PBR changes.

**Comment by niffiwan** [comment]
all the CI builds passed, are we waiting on anything else?

**Pull request merged**
