### PR TITLE
Mantis 1826 Clean Patch Part 1

### PR DESCRIPTION
**Pull request by FSCyborg**
Most up to date version of the fix Mantis 1826, sans random whitespace edits and erroneous reverse commits.

Please hold on committing until I've posted all three and the Appveyor results are in just to be safe since I'm on my work computer.

### CODE REVIEW

**Comment by FSCyborg** [comment]
Please wait for part three.....  *sighs*  I need to revert all those commit.

**Comment by chief1983** [comment]
I suppose that by itself this isn't really doing anything useful, so we can just close this one until you get your Git figured out as well?

**Comment by FSCyborg** [comment]
Sounds good. It could be a while since my computer charger broke and I need
to wait to get a new one.

**Comment by MageKing17** [comment]
Let's close it, then.

**Pull request closed without merging**
