### PR TITLE
Rectified jump nodes not rendering in FRED. Fixes Mantis 3162.

### PR DESCRIPTION
**Pull request by SamuelCho**

### CODE REVIEW

**Comment by Goober5000** [comment]
That's a simple fix if I ever saw one.

**Comment by chief1983** [comment]
You would think that something named render_all would include render_outlines or any other render_whatever.

**Comment by SamuelCho** [comment]
Originally the draw_list class wasn't supposed to even handle arcs, outlines, and insignias. render_all was going to be the only method.

So, as what happens in software development, plans change and assumptions are challenged. I had to pull the miscellaneous rendering crap into the draw_list system. render_all should've been renamed to render_meshes. I mean if you really want me to do that, I'll do it.

**Comment by chief1983** [comment]
Lol, wasn't aware that was your doing :)  If you think it'll lead to more maintainable code, sure, go for it.  Otherwise it's probably fine.

**Pull request merged**
