### PR TITLE
Update Settings for movie subtitles #6064

### PR DESCRIPTION
**Pull request by Dark-Visor**
Update mod_table and movie files to include settings for the color and transparency of the subtitles.

Implements #6064

### CODE REVIEW

**Review by Goober5000 — COMMENTED** [review]
Will check it out again after tomorrow's changes

**Comment by MjnMixael** [comment]
If this is meant to address visibility issues with specific cutscenes, shouldn't this be a setting in cutscenes.tbl instead of a mod-wide parameter?

**Comment by Dark-Visor** [comment]
> If this is meant to address visibility issues with specific cutscenes, shouldn't this be a setting in cutscenes.tbl instead of a mod-wide parameter?

Thanks MjnMixael, the mod-wide approach seemed the best one for now based on that $Movie subtitle font is already in game_settings.tbl and it made most sense to have them together. Maybe at a later stage both font and color could be added to cutscenes.tbl , potentially along with font position settings as well.

**Review by Goober5000 — APPROVED** [review]
This looks good now.  I'll get a test build to @Achille44.

**Review by Goober5000 — CHANGES_REQUESTED** [review]
Build sent.  There is one more usability change we should make; I'll wait for the test results in case there are others.

**Review by Goober5000 — APPROVED** [review]
Nice work. 👍

**Pull request merged**
