### PR TITLE
Make beams respect 'check hull' and 'can damage shooter' flags

### PR DESCRIPTION
**Pull request by Baezon**
Yes, this will change behavior for mods using these options. But I hopefully should not need to mention how incredibly unintuitive and annoying it would be to have flags that are very explicit on what they do, only to just magically not work in certain situations, and magically require you to know to enable a completely different flag in a completely different file, otherwise.

EDIT: To clarify, with the new 'check hull' handling this will only early interrupt a beam that started unobscured and became obscured during its firing. 'check hull' as it is will prevent a beam from starting to fire if it is obscured.

### CODE REVIEW

**Review by Goober5000 — COMMENTED** [review]
I'm a little wary of this.  It's a good change, but `"check hull"` is a pretty old flag and there are a lot of mods that use it.  Do we know how much of a balance impact this may have?

**Comment by Baezon** [comment]
Not really, no. I suspect it's low, but I don't know.

I'd want to get lots opinions on this, from modders especially, since I really really don't want to make this flag.

**Comment by JohnAFernandez** [comment]
I'm fine with the change, because even if old mods use this flag, I'm not anticipating it making a big difference.

**Comment by Baezon** [comment]
To clarify, since this wasn't immediately obvious to me, with the new 'check hull' handling this will only early interrupt a beam that started unobscured and became obscured during its firing. 'check hull' as it is will prevent a beam from starting to fire if it is obscured.

**Comment by JohnAFernandez** [comment]
I had that behavior in mind when I made my comment.

**Review by JohnAFernandez — APPROVED** [review]
It seems like most people think that this change makes sense.  I think overall, the impact of this will be very low, since the beam would hit the parent ship anyway, if not turned off, and it's not likely to start hitting the target again afterward, at least for long.  

IMHO, balance is not greatly affected by low probability events.

**Review by Goober5000 — APPROVED** [review]
Agreed

**Pull request merged**
