### PR TITLE
Play directive completion sounds for clients

### PR DESCRIPTION
**Pull request by JohnAFernandez**
This allows multiplayer clients to hear the directive completion sound at the right time and to also see when a directive has been failed.

### CODE REVIEW

**Comment by Goober5000** [comment]
It looks as it the code you added is duplicating some stuff that is already run on the client side - setting `satisfied_time` for example.

Since you already call `send_event_update_packet(event);`, can the client function that receives that packet play the directive sound?

**Comment by JohnAFernandez** [comment]
> It looks as if the code you added is duplicating some stuff that is already run on the client side -- setting `satisfied_time` for example.
> 
> Since you already call `send_event_update_packet(event);`, can the client function that receives that packet play the directive sound?

The original bug was that they weren't playing it.  So I found where it was playing on the server, and that part of the function was not playing on the client.  But let new look again at `satisfied_time` to see if there's another place where it just wasn't following the correct code path.

**Comment by JohnAFernandez** [comment]
Ok. I see what you're saying now.  Yes, that would be a lot more optimal.  Let's see if I can write something cleaner.

**Review by Goober5000 — APPROVED** [review]
That looks like it makes much more sense.

**Comment by Goober5000** [comment]
I think @notimaginative should take a look at it just as a general multiplayer sanity check.

**Review by notimaginative — APPROVED** [review]
LGTM

**Pull request merged**
