### PR TITLE
Sync Antipodes

### PR DESCRIPTION
**Pull request by asarium**

### CODE REVIEW

**Comment by Echelon9** [comment]
So this is a rebase of the antipodes branch against master? If so, looks fine.

**Comment by asarium** [comment]
Yeah, just a simple merge and a small change to fix linux compilation.

**Comment by chief1983** [comment]
When I ran git merge master on antipodes I ended up with lots of conflicts, how did this end up smoother?  Also, echelon9, this appears to be a merge, not a rebase.

**Comment by asarium** [comment]
I just told SourceTree to merge master into antipodes and fixed the few conflicted files. There was one change that broke compilation on linux but I fixed that pretty quickly.

**Pull request merged**
