### PR TITLE
Add OpenDDL/OpenGEX support

### PR DESCRIPTION
**Pull request by bryansee**
This is an effort to implement the Open Game Engine Exchange (OpenGEX) format as an alternative to the POF model format. The OpenGEX format is a text-based file format built upon the data structure concepts defined by the Open Data Description Language (OpenDDL), a generic language for the storage of arbitrary data in human-readable format.

The reason behind this is to overcome the limitations of the POF format. These OpenGEX files would be read via tables, as well as scripts and within the engine itself.

Those who aren't aware, the OpenGEX format was created because Collada, the open standard that we should have used to replace the POF, has proven to be an unreliable mess. The most common source of problems has been the poor quality of the Collada export plugins available for modeling tools and Collada's over-engineered design and its mutating under-specified format.

### CODE REVIEW

**Comment by bryansee** [comment]
I need review of the OpenGEX and OpenDDL code ASAP.

**Comment by Baezon** [comment]
The specifics are a bit beyond me, I'm sure others can weigh in there, but firstly I'd be very interested to know if you've actually tested this, and successfully imported a fully functioning model in this format into FSO.

**Comment by bryansee** [comment]
> 
> 
> The specifics are a bit beyond me, I'm sure others can weigh in there, but firstly I'd be very interested to know if you've actually tested this, and successfully imported a fully functioning model in this format into FSO.

You can check it out [here](https://opengex.org/), Baezon.

**Comment by Baezon** [comment]
I'll take that as a 'no'. Until you can successfully test this with an actual model first (or get it to pass the checks), I highly doubt this will be merged any time soon

**Comment by TRBlount** [comment]
This PR can't be merged even if it passed the build checks. There's tons of licensing issues here since you just dumped a bunch of source files from external libraries into the project and changed a few build configs. I will be closing this PR as you obviously didn't put any effort to making something that works and is legally viable. If you want this to be reconsidered, properly implement the code changes and provide ***in game*** test cases in the OP.

**Comment by The-E** [comment]
And just to put this entire thing to bed, @bryansee:
* OpenGEX/OpenDDL are licensed under GPL v3. We _can not_ use that code under any circumstances.
* Even if we _could_ use that code, OpenGEX itself isn't suitable for ingame use, as models made in it are unbelievably huge, parsing them is slow, and the work required to make them usable by the rest of the engine (work that you, @bryansee, did _not_ do in this PR) is prohibitive and better done in a bespoke asset conversion tool

**Pull request closed without merging**
