### PR TITLE
Use 64 bit build for appveyor

### PR DESCRIPTION
**Pull request by asarium**
Nightly builds are still compiled as 32-bit build though.

### CODE REVIEW

**Comment by chief1983** [comment]
I know it may extend test times a bit but would having both 64 and 32 bit builds tested for now maybe be a good idea?

**Comment by asarium** [comment]
They are already tested. Visual Studio 2013 compiled 32 bit builds, VS 2015 compiles 64-bit builds.

**Comment by MageKing17** [comment]
The 2013 configuration is still 32-bit; I don't think there's much to be gained from having CI do 32/64 of both 2013 and 2015.

**Comment by chief1983** [comment]
But isn't there a chance that compiler differences could lead to warnings in one that don't occur in the other?  Or are any warnings about bit size likely going to be pretty universal?

**Comment by asarium** [comment]
The most warnings will probably happen on the 64-bit configuration and most warnings that happen with 32-bit also happen with 64-bit. Appveyor build times are already pretty high, I would like to avoid increasing that even more.

**Pull request merged**
