### PR TITLE
[Antipodes] Update SDL to version 2.0.3

### PR DESCRIPTION
**Pull request by asarium**
This version now works out of the box with FRED although I don't know exactly why, if it breaks in the future SDL_HINT_VIDEO_WINDOW_SHARE_PIXEL_FORMAT could help fix it.

### CODE REVIEW

**Comment by chief1983** [comment]
Any reasons we left the compiled libraries this time?  Doesn't look like we had them before.

**Comment by asarium** [comment]
We still need SDL2.lib/.dll and SDL2main.lib is still used by some projects.

**Comment by chief1983** [comment]
So where did we store them before this?  At least the .libs I mean, the .dll I thought we provided as a separate download link.

**Comment by asarium** [comment]
The Windows binaries (both .dll and .lib) were stored in the source tree.

**Pull request merged**
