### PR TITLE
Move build system to CMake

### PR DESCRIPTION
**Pull request by asarium**
I compiled a list of how to do common operations in the wiki of my repository: https://github.com/asarium/fs2open.github.com/wiki/CMake

Once this gets merged I'll move that article into the main wiki.

### CODE REVIEW

**Comment by chief1983** [comment]
I don't have working TTS with these builds.  The fs2_open.ini contains the following:
SpeechTechRoom=1
SpeechBriefings=1
SpeechIngame=1
So I believe it should be told to enable itself.  It is working in 3.7.4 builds on this PC.  I can't get Voice Rec to start either but I can't get it running with 3.7.4 so that appears to be an issue with my machine.  If someone with working voice recognition in 3.7.4 could test this branch it would be helpful.

**Comment by asarium** [comment]
That's odd. I tested it yesterday and it worked flawlessly.

**Comment by MageKing17** [comment]
I tested voice recognition successfully with this branch (with a 64-bit build, no less). I'll test TTS as well.

**Comment by chief1983** [comment]
Ok, I just tested the last nightly and I don't have TTS in the tech room there either.  So it's not a CMake change but probably something in the SDL2 merge causing the issue for me.

**Comment by asarium** [comment]
What else needs to be tested before merging this?

**Pull request merged**
