### PR TITLE
Soft shadows, deferred lighting, and various graphics improvements and optimizations

### PR DESCRIPTION
**Pull request by SamuelCho**

### CODE REVIEW

**Comment by niffiwan** [comment]
Compiles fine on Linux; but I've noticed a couple of issues:

1) There's something odd occurring with cockpit glass reflections. They seems to unpredictably switch between OK and sort of light green matte. Sometime changing the external camera view angle changed the reflection type, but sometimes it didn't.  I thought that green-beam fire could have caused the odd behaviour, but it didn't seem to be linked, i.e. it was sometimes good when beams were firing, and sometimes bad when no beams (seemed) to be firing)
[Good Reflections](http://i.imgur.com/a97NHx6.png)
[Green Matte Reflections](http://i.imgur.com/OOb2WQf.png)

2) The boxes around the ship icons in the ship & weapon loadout screens seem to be thick white now instead of thin and green.
[Current master with green](http://i.imgur.com/CnOnjCp.png)
[White](http://i.imgur.com/kSXT8Tj.png)

**Comment by SamuelCho** [comment]
If that's it, can we just merge this in now and file these as issues?

**Comment by chief1983** [comment]
Was it adjusted to disable the things on OS X that won't work well automatically for now?  Just wondering if we need to manually disable shadows or if we'll just not enable them on OS X for now, he mentioned going back to a previous method to simplify the code since the new method didn't even fix all the OS X platforms.

**Comment by SamuelCho** [comment]
There have been no attempts to disable any features on a specific platform unless the platform doesn't have the proper OpenGL extension.

**Comment by The-E** [comment]
I think this can be merged, then.

**Comment by chief1983** [comment]
Hmm, maybe this was premature.  I know the shader_transform_deferred branch or whatever was compiling on my mac fine, but I guess I hadn't tested this one yet.
```
Ld build/FS2_Open.build/Release/FS2_Open.build/Objects-normal/x86_64/FS2_Open\ 3.7.3 normal x86_64
    cd /Users/cliff.gordon/fs2_open_git_0/projects/Xcode4
    export MACOSX_DEPLOYMENT_TARGET=10.6
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -L/Users/cliff.gordon/fs2_open_git_0/projects/Xcode4/build/Release -F/Users/cliff.gordon/fs2_open_git_0/projects/Xcode4/build/Release -FFrameworks -filelist /Users/cliff.gordon/fs2_open_git_0/projects/Xcode4/build/FS2_Open.build/Release/FS2_Open.build/Objects-normal/x86_64/FS2_Open\ 3.7.3.LinkFileList -Xlinker -rpath -Xlinker @loader_path/../Frameworks -mmacosx-version-min=10.6 -dead_strip -fobjc-link-runtime -framework Cocoa -framework OpenGL -framework GLUT -framework OpenAL -framework SDL -lcode -ljansson -ljpeg -llua -lmongoose -lpng -lzlib -framework Ogg -framework Vorbis -framework Theora -Xlinker -dependency_info -Xlinker /Users/cliff.gordon/fs2_open_git_0/projects/Xcode4/build/FS2_Open.build/Release/FS2_Open.build/Objects-normal/x86_64/FS2_Open\ 3.7.3_dependency_info.dat -o /Users/cliff.gordon/fs2_open_git_0/projects/Xcode4/build/FS2_Open.build/Release/FS2_Open.build/Objects-normal/x86_64/FS2_Open\ 3.7.3
Undefined symbols for architecture x86_64:
  "draw_list::init()", referenced from:
      obj_render_queue_all() in libcode.a(objectsort.o)
  "draw_list::render_outlines()", referenced from:
      obj_render_queue_all() in libcode.a(objectsort.o)
  "model_render_params::set_warp_params(int, float, vec3d&)", referenced from:
      shockwave_render(object*, draw_list*) in libcode.a(shockwave.o)
      warpin_queue_render(draw_list*, object*, matrix*, vec3d*, int, float, float, float, int) in libcode.a(warpineffect.o)
  "submodel_render_queue(model_render_params*, draw_list*, int, int, matrix*, vec3d*)", referenced from:
      shipfx_queue_render_ship_halves_and_debris(draw_list*, clip_ship*, ship*) in libcode.a(shipfx.o)
      debris_render(object*, draw_list*) in libcode.a(debris.o)
```
Is there a missing include or did I need to bump the target to something higher than 10.6?

**Comment by SamuelCho** [comment]
You're going to have to check if your project files have modelrender.cpp, modelrender.h, and shadows.cpp, shadows.h. Please update the project files if they're missing.

**Comment by chief1983** [comment]
Ah, I thought that had already been committed to your branch.  I'll take care of that then.

**Comment by asarium** [comment]
The main fragment shader currently fails to compile with the following message:
```
Compiling new shader:
	Model Rendering
   Loading built-in default shader for: main-v.sdr
   Loading built-in default shader for: main-f.sdr
Fragment shader failed to compile:
Fragment shader failed to compile with the following errors:
ERROR: 0:331: error(#143) Undeclared identifier: blend_alpha
ERROR: error(#273) 1 compilation errors.  No code generated


ERROR! Unable to create fragment shader!
```

The shader currently references `blend_alpha` when `FLAG_FOG` is defined but that requires `FLAG_DIFFUSE_MAP` to be defined which in most cases isn't the case when  `FLAG_FOG` is defined.

**Pull request merged**
