### PR TITLE
Whitespace and commenting tweaks

### PR DESCRIPTION
**Pull request by ln-zookeeper**

### CODE REVIEW

**Comment by Echelon9** [comment]
A number of these whitespace changes don't look correct once rendered here. Do you have a locally set `core.whitespace` in your Git?

**Comment by MageKing17** [comment]
GitHub uses a tab width of 8; FSO source uses a tab width of 4. I checked a few lines in question in Sublime Text, and the spacing looks correct to me.

**Comment by z64555** [comment]
...and we're likely to have another similar whitespace augment. I like the general rule of having tabs for indents, and spaces for everything else, since tabs will always cause issues like this. Naturally this'll increase the character count on files but I don't believe it significantly slows down any compilers.

**Comment by chief1983** [comment]
Yes, using tabs for anything other than indentation of the whole line is generally a bad idea, but it's what's been done.  We've agreed that a tab should be four spaces across FSO to get the tabs-in-lines to line up correctly, and this does seem to address a lot of issues.  Some issues I have seen though:

model.h:
Lines 133 and 135 still have mixed tabs and spaces for indentation
Lines 137-142 have a spaces before the opening ( instead of a tab.
The comments in lines 152-157 don't line up. (Ok, many comments of this style in the file don't line up, but this set looks like it sort of tried to at one point)
Lines 226-227 use spaces instead of tabs mid-line, and their alignment doesn't coincide with anything else around them.
Line 330 *bsp_data is one tab too far over
Line 336 rad is one tab too far over
line 369 arc_type is one tab too far over

etc etc...
I could probably keep making a list, but I guess what I realized when trying to make this list is that instead of doing piecemeal commits periodically that muck up the history when no other related changes are being made, shouldn't we wait and do a serious overhaul of formatting that is much more comprehensive?

**Comment by The-E** [comment]
I would agree. I'd much prefer running the codebase through clang-format or something similar to enforce standards than these sort of piecemeal commits.

**Comment by MageKing17** [comment]
So shall we just close this PR, then, or is that more of admonishment against *further* piecemeal commits (or keep the comment commit and ditch the whitespace commit)?

**Comment by z64555** [comment]
I think we should go with keeping the comment commit and ditch the whitespace commit for now.

**Comment by chief1983** [comment]
Makes sense to me.

**Comment by Echelon9** [comment]
I agree.

**Pull request merged**
