### PR TITLE
Adds Accept Mission Outcome as new Conditional Hook

### PR DESCRIPTION
**Pull request by wookieejedi**
Adds Accept Mission Outcome Event to Game Events, so LUA scripts can be called when a campaign mission is accepted. This addresses Issue #1857.

### CODE REVIEW

**Comment by wookieejedi** [comment]
Not sure why the tea build failed with '-- Check size of unsigned int - failed' on only the x64 debug version...

**Comment by wookieejedi** [comment]
Ah you're right, it wasn't actually being called. So I should define a hook in scripting.h and then add it in scripting.cpp?

**Comment by asarium** [comment]
Yes, you can use the existing hooks as a template to see how that is done.

**Comment by wookieejedi** [comment]
Sounds good thanks. I figured I would want to use a hook template similar to CHA_MISSIONEND, but I can't find any reference to it other then in the initial Script_actions[] list, though I will keep looking. : )

**Comment by asarium** [comment]
It's used in `game_level_close` in `freespace.cpp`.

**Comment by wookieejedi** [comment]
I've added the hook, CHA_CMISSIONACCEPT to the appropriate lists in scripting.ccp and .h. Just had a quick question though, would it be more appropriate to use these lines at the end of the function game_level_close() in freespace.cpp?

"
	if ( Game_mode & GM_CAMPAIGN_MODE ){
		mission_num = Campaign.current_mission;
		if ( Campaign.next_mission != mission_num ) {
			Script_system.RunCondition(CHA_CMISSIONACCEPT);
			} 
	}
"

Or 

Should I simply add the line <Script_system.RunCondition(CHA_CMISSIONACCEPT);> in the appropriate place in missioncampaign.cpp and then just include the scripting(.ccp and .h) in top include list for missioncampaign.cpp?

**Comment by wookieejedi** [comment]
Looks like that should do it, as long as that is an appropriate place to add the hook run condition.

**Pull request merged**
