### PR TITLE
Add unified dialog handling

### PR DESCRIPTION
**Pull request by asarium**
This unifies the way the engine handles warning and error dialog by using the functions supplied by SDL without having to use platform specific functions.

Tested on Linux and Windows (VS 2015).

### CODE REVIEW

**Comment by MageKing17** [comment]
The new files were only added to the 2015 folder, causing the AppVeyor failures.

How do the SDL dialog boxes work? Do the button names need to be from a specific pool, or can we rename the Warning buttons to something more descriptive and get rid of the confusing "yes to debug, no to continue" behavior and message?

Is there really all that much point to making the behavior identical on all platforms when Int3() does nothing on non-Windows platforms?

**Comment by asarium** [comment]
The build failures are expected as I don't have a VS version capable of editing those project files.

The names of the buttons can be names however we want. What are your suggestions for better names?

Having different behavior for different platforms is stupid especially if we have the capability of displaying the same dialogs without much effort.

**Comment by MageKing17** [comment]
> Having different behavior for different platforms is stupid especially if we have the capability of displaying the same dialogs without much effort.

I'm not saying that displaying dialogue boxes on all platforms is a bad idea; I'm just wondering if it's going to be counter-intuitive to people not on Windows to indicate that they want to debug something only to have the program close on them, because that's basically all Int3() does in osapi_unix.cpp (well, after logging it).

Is there a reason to keep the Messagebox_active variable, but remove every instance of it being set to true?

**Comment by asarium** [comment]
SDL provides a cross-platform version of Int3(), we can use that instead of our current solution. I'll also change the button texts to better describe what will be done.

I removed a few unused variables from windebug.cpp.

**Comment by asarium** [comment]
That should be sufficient, Int3 now uses the SDL function for triggering a breakpoint so it should work on all platforms (but the actual behavior may differ).
I also changed the labels to better describe what will happen.

**Pull request merged**
