### PR TITLE
Multilock Patch

### PR DESCRIPTION
**Pull request by JohnAFernandez**
Multiplayer Compatibility Portion Of Multilock.

Please get the reviews in now so we can get this merged.

*The reason it's in draft is to be extra careful and I would able to test after addressing feedback but before it's merged.*

### CODE REVIEW

**Comment by JohnAFernandez** [comment]
If I get another pair of eyes, even if it's just for readability or to do general checkinhg would be good

**Comment by Goober5000** [comment]
I looked at it yesterday.  I didn't see anything wrong with it but I'm not too familiar with the multi code.

**Comment by JohnAFernandez** [comment]
Thanks to everyone who looked it over!

**Comment by wookieejedi** [comment]
Looks like this is good to merge now?

**Comment by TRBlount** [comment]
Agreed.

**Pull request merged**
