### PR TITLE
[rename_2011] Rename MSVC_2011 to MSVC_2012

### PR DESCRIPTION
**Pull request by chief1983**
This probably isn't easy to figure out unless you remember that VS 2012 was going to be VS 2011 until it was delayed.

### CODE REVIEW

**Comment by niffiwan** [comment]
This is probably a silly question - but you have successfully built from the renamed project?

**Comment by chief1983** [comment]
Actually, no, I generated the PR on my Mac :P

Guess I'll give that a shot soon.

**Comment by asarium** [comment]
VS 2012 fails to link with unresolved symbols. The project files currently don't contain the shadow files.

**Comment by chief1983** [comment]
Ok, I fixed the 2011 files in master and merged that in, this does compile in 2012 now.  Should be safe to merge.

**Comment by chief1983** [comment]
Ok, I fixed the appveyor config to handle the rename, but it looks like VS 2012 and VS 2013 builds are failing in AppVeyor for some other reason.  Odd, since the VS 2013 nightly just ran fine, and many of these don't even change the code.

**Comment by chief1983** [comment]
Ok, travis seems messed up right now but AppVeyor passed the VS 2012 build which is all that should matter here.

**Pull request merged**
