### PR TITLE
add mouseButtonDownCount and flushMouse

### PR DESCRIPTION
**Pull request by Goober5000**
Implements #4429.

### CODE REVIEW

**Comment by Goober5000** [comment]
Looking at @z64555 's latest comment on #4429, isMouseButtonDown might be useful after all and we may not want to deprecate it.

**Comment by z64555** [comment]
> Looking at @z64555 's latest comment on https://github.com/scp-fs2open/fs2open.github.com/issues/4429, isMouseButtonDown might be useful after all and we may not want to deprecate it.

yeah, which I've said at least a few times that some consideration has to be put in to consider if isMouseButtonDown would still be useful.  mouseButtonDownCount appears to be able to emulate isMouseButtonDown by passing false to the reset argument, but I can't say for certain if that's enough of a nail for isMouseButtonDown's coffin.

**Comment by Goober5000** [comment]
Ok, this is ready for review.  It looks like the `isMouseButtonDown` function is useful on its own, so I've un-deprecated it.

**Comment by z64555** [comment]
After some thought I've decided that `isMouseButtonDown()` should be kept to detect if a mouse button is currently down and `mouseButtonDownCount()` should be used to detect the number of times a button went down.

There's two primary types of controls in the codebase, one is a continuously firing control (such as weapons) and the other is a one-shot control (such as comms, secondary weapon selection, etc).

Continuous controls need to check the button state, as it should be triggering every frame that the control is down.  One-shots however need to check the falling edges of the button state (when the button goes down), and potentially trigger for each of those edges so that "Press X a certain number of times, downscroll the same number of times" holds true.

Although `mouseButtonDownCount()` may be able to emulate `isMouseButtonDown()` by being told to not reset the counter and thus return true, it won't be able to detect when the button is let up.

**Review by z64555 — APPROVED** [review]
Mousewheel directions are not included, but those are a separate problem I hope to addressed Soon(TM).

**Pull request merged**
