### PR TITLE
Review and refactor #include's

### PR DESCRIPTION
**Pull request by Echelon9**
This PR improves compile time (c.1-2%), reduces code complexity and improves readability.

It does this by:
* Scripted approach to sort and uniq the internal project #include's;
* Properly guard .h header files against multiple inclusion in a compile unit;
* Removing duplicated includes within paired .cpp and .h; and
* Simplifies where possible #include's within a common feature, say, the nebula code.

A few duplicated #include's were found and an overall reduction in the spaghetti linkage within compile units. The performance improvement will depend upon your compiler and development hardware.

For my clang and non-SSD system this was a c.1-2% time improvement for `make clean && make`. Almost entirely in system time, the speed up is likely the avoided disk access and file seek time this PR delivers.
```
master
==========
real	4m14.735s
user	3m58.612s
sys	    0m18.584s


fix/sort-uniq-includes
==========
real	4m12.598s
user	3m57.315s
sys	    0m16.013s
```

Reduced code complexity from (i) alphabetical sorting, and (ii) having only the minimal required #include files, makes the resultant code easier to understand.

By avoiding unnecessary #includes all together, partial rebuilds will also improve for developers. For certain edits this could be significantly more than a 1-2% speed up.

### CODE REVIEW

**Comment by Echelon9** [comment]
AppVeyor's windows buildbot error makes no sense. The code/mm/ folder wasn't touched by this PR.
Can a fellow Windows dev confirm?

**Comment by asarium** [comment]
Apparently mmreg.h needs to have `windows.h` included but by reordering the includes that doesn't happen anymore. Moving the windows.h include to the top of the include definitions in the files where AppVeyor complains should fix that.

**Comment by chief1983** [comment]
Is this likely to have any strange consequences when attempting to merge it into Antipodes?  It seems a bit far-reaching to do with another major restructure waiting to be merged in.

**Comment by Echelon9** [comment]
@asarium Have pushed a new commit which adds `#include <windows.h>` prior to the only spot in fs2open where we include mm/mmreg.h.

@chief1983 Whilst there might be merge conflicts and interactions with Antipodes branch, this is a great example of how git's branching-is-cheap approach works well. I'm much happier to resolve merge commits to this PR while awaiting Antipodes merge, than have a stale SVN patch sitting on my HDD ready to be lost.

**Comment by Goober5000** [comment]
Wow.  I did much the same thing on the #includes way back in 2003 or 2004 -- although I didn't alphabetize them.  It's interesting to see how spaghettified they've become since then.

**Comment by Echelon9** [comment]
So much spaghetti...

**Comment by z64555** [comment]
I approve. :+1:

**Comment by Goober5000** [comment]
Everyone approves on principle, all checks pass, and presumably nothing aside from the actual include statements have been changed.  (I barely skimmed the diff.)  I will venture to go ahead and merge this.

**Pull request merged**
