### PR TITLE
Flush the mouse state after toggling between Use_mouse_to_fly states

### LINKED ISSUE #4173: controls are not flushed when weapons are unlocked
Prior to the controls merge, if the player's primaries and secondaries were locked, any "fire weapon" control presses would be ignored or flushed.  After the controls merge, the control presses are no longer ignored - unlocking the primary and/or secondary weapons will cause a delayed weapons fire.

I tested this with the "primaries-locked" and "secondaries-locked" flags, although it's possible it happens with "afterburners-locked" as well.

### PR DESCRIPTION
**Pull request by z64555**
Fixes #4173 

...Was it really that simple? 😩

### CODE REVIEW

**Comment by z64555** [comment]
@Goober5000 @Kiloku Please test this PR to verify the fix works on your end.

**Comment by z64555** [comment]
Flushing the mouse state at the toggle clears out the button_pressed members of the mouse.

This is probably a stop-gap measure, but it does grealy narrow down where the phenomenon happens.

**Comment by Kiloku** [comment]
Tested and it works here

**Review by Goober5000 — APPROVED** [review]
Tested and works 👍

**Comment by z64555** [comment]
Lua checks mouse_flags to see if a button is down or not, but does not clear the respective button counter when doing so.  So, when the original script rolls around to unlocking the mouse, the controls code checks if a mouse button is currently down *and* if the any of the down counters are non-zero.

**Pull request merged**
