### PR TITLE
Bitset flags

### PR DESCRIPTION
**Pull request by The-E**
Okay, this is a big one.

Originally, we used a simple mechanism for dealing with flag data. Take an int, use bitwise operators to read and write to them, and done. But, while this is simple and easy to understand, it can result in errors when the programmer isn't careful. Since any #defined flag can be compared against any integer, there is no immediate way for a programmer to know whether what the code is doing is what the code is intended to do; several instances of this have been found while writing this and have subsequently been fixed.

Now, what does this actually do?
At the basis of this is a new template class called SCP_flagset. It's basically an std::bitset that uses enum classes as indexers; this allows for type safety and compile/edit-time type checking.

Do note that this has not been tested for speed or multiplayer workability; it is however guaranteed that this breaks multiplayer compatibility.

### CODE REVIEW

**Comment by SamuelCho** [comment]
This is sorely needed. The code seems sound. I apologize for the ugly merge in the model rendering code.

**Comment by The-E** [comment]
Unfortunately,as long as clang and gcc are unable to digest this, this isn't going anywhere.

**Comment by chief1983** [comment]
Looks like it still doesn't like VS 2010 or 2012 apparently.

**Comment by The-E** [comment]
Well, at least gcc and clang seem happy now. I have another commit ready to go (albeit on my Laptop, which I won't be able to hook up to internet for a few hours) that should address one issue VS2010 has (that being "incomplete" support for enum classes), so we'll have to see what happens there.

**Comment by chief1983** [comment]
I think AppVeyor has been choking unnecessarily on some of the VS projects, I can double check the compilation success on 2010 and/or 2012 if necessary.

**Comment by chief1983** [comment]
Ok, the errors it's throwing in 2010 and 2012 are legit, lots of syntax errors in the _flags.h files basically.  2010 threw 65000 of them before I quit the build, 2012 is only showing me 100 errors for some reason.  Doesn't like 'ZERO_VECTOR' in ship.h for example.  Lots of things aren't defining successfully.  This is after merging latest master into your branch to fix existing 2012 compilation issues.

**Comment by MageKing17** [comment]
VS 2010 and 2012 don't support initializer lists.

**Comment by chief1983** [comment]
Ah.  Also, 2012 seems to be missing ai_flags.h from its set of additions.

**Comment by chief1983** [comment]
And 2010 wasn't updated with the new files at all so I guess I shouldn't have expected it to build either.  But if it doesn't support what's already breaking 2012, then there's no point in messing with it I guess.

**Comment by chief1983** [comment]
And, some of these new .h files seem to have mixed line endings.  Normalizing those all to LF would be ideal.

**Comment by The-E** [comment]
Okay, so I tried a few potential fixes (as you can see in the commit log), plus a few I did not commit, and basically, my verdict is that this thing will not be possible to pull off using VS2010's standard compiler. Any solution that would allow this to compile on that thing would necessitate moving away from the use of enum classes, and I think that that compromises the guarantees this makes to an unacceptable degree.

**Comment by asarium** [comment]
I managed to compile FSO on GCC (and probably clang as well but I haven't tested) with a few changes: https://github.com/asarium/fs2open.github.com/tree/build/windowsGCC

That means that a dev who wants to use XP (which is the only reason we still keep VS2010) can use that as that compiler implements the required C++11 features.

**Comment by chief1983** [comment]
So that would leave the XP devs with no debugger if I understand, since I don't think GDB works with PDB files, which is all VS can generate.

**Comment by asarium** [comment]
If you compile with GCC you can debug with gdb, no PDB files needed.

**Comment by chief1983** [comment]
Ah, ok, maybe I had it backwards, you wouldn't be able to debug natively in VS because it only understands PDB.

**Pull request closed without merging**
