### PR TITLE
Fix weapon flag parsing

### LINKED ISSUE #853: #851 breaks weapons.tbl loading
Starting with git 127976cd74e2205f928e7de79c5d89ad555f7796 (#851), FSO fails to start, displaying an error. Reverting the commit fixes the issue.

From fs2_open.log
```
weapons.tbl(line 100): Error: Reading string list.  Found [$].  Expecting '('.


Error: weapons.tbl(line 100):
Error: Reading string list.  Found [$].  Expecting '('.

File: parselo.cpp
Line: 290
```

My weapons.tbl: 
[weapons.tbl.txt](https://github.com/scp-fs2open/fs2open.github.com/files/426898/weapons.tbl.txt)

Backtrace below:
```
#0  debug_int3 (file=0xd818a0 "/home/risto/fs2/fs2open.github.com/code/osapi/dialogs.cpp", line=350)
    at /home/risto/fs2/fs2open.github.com/code/osapi/osapi.cpp:388
#1  0x0000000000ad2a57 in os::dialogs::Error (
    text=0x48a7978 "Error: weapons.tbl(line 100):\nError: Reading string list.  Found [$].  Expecting '('.\n\nFile: parselo.cpp\nLine: 290\n") at /home/risto/fs2/fs2open.github.com/code/osapi/dialogs.cpp:350
#2  0x0000000000ad270b in os::dialogs::Error (filename=0xd99606 "parselo.cpp", line=290, 
    format=0xd99637 "%s(line %i):\n%s: %s") at /home/risto/fs2/fs2open.github.com/code/osapi/dialogs.cpp:291
#3  0x0000000000b2a8df in error_display (error_level=1, 
    format=0xd9aad0 "Reading string list.  Found [%c].  Expecting '('.\n")
    at /home/risto/fs2/fs2open.github.com/code/parse/parselo.cpp:290
#4  0x0000000000b2feff in stuff_string_list (slp=0x48a6f28, max_strings=64)
    at /home/risto/fs2/fs2open.github.com/code/parse/parselo.cpp:2708
#5  0x0000000000cae40f in parse_string_flag_list<Weapon::Info_Flags, flagset<Weapon::Info_Flags, 76ul> > (
    dest=..., defs=0x1155d20 <Weapon_Info_Flags>, n_defs=64, unparsed_or_special_strings=0x7ffe4e15e8c0)
    at /home/risto/fs2/fs2open.github.com/code/parse/parselo.h:155
#6  0x0000000000c944ac in parse_wi_flags (weaponp=0x1f68540 <Weapon_info>, wi_flags=...)
    at /home/risto/fs2/fs2open.github.com/code/weapon/weapons.cpp:578
#7  0x0000000000c975b4 in parse_weapon (subtype=0, replace=false, filename=0xde8a10 "weapons.tbl")
    at /home/risto/fs2/fs2open.github.com/code/weapon/weapons.cpp:1510
#8  0x0000000000c9bf68 in parse_weaponstbl (filename=0xde8a10 "weapons.tbl")
    at /home/risto/fs2/fs2open.github.com/code/weapon/weapons.cpp:2816
#9  0x0000000000c9e30b in weapon_init () at /home/risto/fs2/fs2open.github.com/code/weapon/weapons.cpp:3434
#10 0x000000000072358b in game_init () at /home/risto/fs2/fs2open.github.com/freespace2/freespace.cpp:2020
#11 0x000000000072d1a5 in game_main (argc=1, argv=0x7ffe4e15fd58)
    at /home/risto/fs2/fs2open.github.com/freespace2/freespace.cpp:6977
#12 0x000000000072f797 in actual_main (argc=1, argv=0x7ffe4e15fd58)
    at /home/risto/fs2/fs2open.github.com/freespace2/freespace.cpp:8609
#13 0x000000000072f8b8 in main (argc=1, argv=0x7ffe4e15fd58)
    at /home/risto/fs2/fs2open.github.com/freespace2/freespace.cpp:8650
```

### PR DESCRIPTION
**Pull request by rtoijala**
Starting with git 127976c (#851), FSO fails to start, displaying an
error. This is my attempt to fix it. FSO starts, but I do not know how
to check that the flags are parsed correctly.
Fixes #853

### CODE REVIEW

**Comment by The-E** [comment]
This is not quite right. Flags have to be parsed _after_ checking whether "+override"  is specified. Doing it before that point will cause parse errors for any table that uses +override.

**Comment by rtoijala** [comment]
Thanks for the feedback. I amended the commit, which seems to have removed your comment, @The-E.

**Comment by The-E** [comment]
Sorry about that, I removed my comment because it was actually wrong :( 
Your initial patch was fine as it was, I just got confused.

**Comment by rtoijala** [comment]
Ah. In that case, I'll just re-amend my commit again.

**Comment by rtoijala** [comment]
Right, I hope it is correct now.

**Pull request merged**
