### PR TITLE
Minor cleanup to Verify and loading bar

### PR DESCRIPTION
**Pull request by Goober5000**
Some small changes:
a) Fix admonishment about commenting Assert and fix spelling
b) rename VerifyEx to Verification to be similar to Assertion
c) remove old pre-2005 MSVC code
d) update `COUNT_ESTIMATE` to provide a more accurate loading bar, per discussion in Discord

### CODE REVIEW

**Comment by MageKing17** [comment]
> d) update `COUNT_ESTIMATE` to provide a more accurate loading bar, per discussion in Discord

You clearly remember that conversation differently than I do; the only opinion I saw expressed was that the idea of `COUNT_ESTIMATE` itself is fucked up, not that the number is too low (it works pretty well, for retail). If anything, I'd think adding some sort of field to the mission file that overrides `COUNT_ESTIMATE` would make far more sense than just bumping the `#define`.

**Comment by Goober5000** [comment]
I was referring to Discord only inasmuch as it alerted me to the issue, not to any potential course of action.  The purpose of that change isn't to authoritatively fix the loading bar, it's to bring the estimate up to date.

**Comment by MageKing17** [comment]
Up to date with what, though? It's only a useful estimate if it's the approximate value a majority of missions will have; if it's just "this is the highest number I personally saw", it's equally as arbitrary as the current number.

**Comment by Goober5000** [comment]
See the comment.  According to the Volition coders, "it seems to always be about the same", so it should indeed be approximate for a majority of missions.

**Comment by The-E** [comment]
The original V comment only made sense in the context of FS2 though, as the retail missions aren't all that complex (and, generally speaking, fall into a relatively narrow band of complexity in terms of assets used). I would like to know where this "719" number is now coming from; Which mods did you survey in order to get it?

The larger point being that it makes little sense to me to bump this number; IMHO, if this is an area that we want to improve, we should improve it by making the load bar actually accurate by incrementing it for each ship or weapon model loaded or pre-mission scripting hook executed.

**Comment by Goober5000** [comment]
Good grief, this is bikeshedding.  As I said, this is just to bring the estimate more in line with the current state of the code, it's not supposed to be an authoritative fix.  If anyone wants to submit a PR with a more comprehensive rewrite of the loading bar, he is welcome to do so.  That is outside the scope of this particular PR.

I looked at one mission log, loading a retail mission on MVPs 4.0, to get the 719 number.  I just checked a log from Scroll and the number there is 781.  The difference between 425 and 719 is almost 70%, while the difference between 719 and 781 is 8.6%.  The point is that there is a dramatic mismatch between the retail estimate and the current state of the code, while there is a much smaller mismatch between different mods which run on the current state of the code.

Given @CasparKielwein 's approval, I'm merging this.  Again, if anyone wishes to do a more comprehensive upgrade of the loading bar, by all means please do so.

**Pull request merged**
