### PR TITLE
handle parse objects that are out of order

### PR DESCRIPTION
**Pull request by Goober5000**
Occasionally, FRED can save a mission with a wing's ships out of order; this can happen if ships are deleted and FRED finds a free index in the middle of the ship list.  This can cause benign but confusing mismatches in the ship registry, the hotkey list, and other places -- and it's also possible some mismatches may not be so benign, e.g. in multiplayer.  Anyway, it's better for the ships to appear in the order the wing expects them, so this adds a routine to swap them around if necessary.

Due to a change in indentation, I recommend viewing the diff while hiding whitespace changes.

### CODE REVIEW

**Comment by JohnAFernandez** [comment]
@notimaginative Do you think multi relies on the old order?  Maybe for in-game joining?  Do you think we need a multi bump here?

**Comment by notimaginative** [comment]
Not sure really. I planned to do some testing on this but haven't gotten the chance so far.

The in-game join crashes were just sort of random so it's hard to say whether they're actually related to this issue or not. But when those crashes did happen it was just a constant barrage of them all of a sudden over multiple quick sessions. The Terran Gauntlet was one mission I tested a lot with so we just need to see if it has an order problem.

Either way I'll try and do at least some testing this afternoon with and without this change to see what happens. Maybe trigger some of the new warnings too and hope the helps pin something down so we can stop guessing.

**Comment by Goober5000** [comment]
This wouldn't require a multi bump.  It's just rearranging parse objects on the fly as they are being loaded from the mission.  It would have the same effect as going into the mission in a text editor and swapping the objects

**Comment by Goober5000** [comment]
The Terran Gauntlet does indeed have a wing with fighters out of order: Pisces 5 comes before Pisces 4.

**Comment by JohnAFernandez** [comment]
It would matter if the parse object order was relied on to be the same.  You never know what obscure thing that multi relies on since it is such a tacked on system.  That's why I asked Taylor.  He's knows the packets which transmit loadouts and in-game joining better, which are the most likely to rely on the parse object code to be the same.

In fact, I may have just thought of an area that does.

**Comment by notimaginative** [comment]
I'm getting a variety of completely unrelated crashes (like `vsnprintf()` no longer taking `nullptr` for size check). Possibly Sonoma upgrade related since this is the first real play testing I've done since the upgrade. But I have a free day tomorrow so I'll try and get it sorted out.

**Comment by Goober5000** [comment]
> It would matter if the parse object order was relied on to be the same. You never know what obscure thing that multi relies on since it is such a tacked on system. That's why I asked Taylor. He's knows the packets which transmit loadouts and in-game joining better, which are the most likely to rely on the parse object code to be the same.

Since the swapping happens during parsing, and the ordering is well-defined, then every multi participant would see a consistent order.  And don't worry, I also messaged Taylor about this PR as it relates to multiplayer.

> Edit: Thankfully, after checking, it looks like net signature is assigned as objects are parsed and the intra-wing swap happens after, so they retain the correct net signatures.

This raises a good point: does the order of the net signatures matter?  With this PR, if you sorted by net signature the order would not match the order of `Parse_objects`.  It would be possible to fix this if we need to.

**Comment by notimaginative** [comment]
I haven't gotten to test this set of changes yet, but I do see where it could cause an issue with net signatures. However that might be primarily due to issues with the current code which we've simply not noticed previously.

Net signatures are assigned in order to the parse object in `parse_create()`, and this signature is later copied to the respective `Object` in `parse_create_object_sub()`. When an object is created in multi the `Object` signature is updated to be what the server says, but the signature for the parse object is never changed from what it was at mission load. So the net signatures can end up different causing issues with stuff like `mission_parse_get_parse_object()` where the server signature is one thing and it tries to match with a signature that was created by the client during mission load. This can lead to an object not being found, or an entirely different object being returned instead.

I think this is the main issue that in-game is running in to. And is almost certainly lead to a previous "fix" that I now believe was incorrect.

Cyborg will need to check me on this, but it might cause (or be causing?) an issue with rollback too. Since the object is loaded into rollback with the parse order signature during `parse_create_object_sub()` and then again with a possibly different net signature after the `Object` signature is changed to match the server.

And I haven't even gotten to really looking at signature handling for wings or other non-ship object types yet.

So I don't think this PR would create a new problem, but would likely exacerbate an existing one. At the least I believe a multi bump will be required to fix the underlying issue.

This is probably going to need a lot more testing to really sort out.

**Comment by JohnAFernandez** [comment]
I didn't even think about rollback.  I can check that today, but I am hoping I relied on net signatures well enough that they wouldn't be affected, if net signatures are properly synced.

You know, as much as Volition tried to avoid sending ship names to assign net signatures, that might be the better long term option, as that would gaurantee that all ships would be synced up. (The mission files dont even need to have ships in the same order in that case)

**Comment by Goober5000** [comment]
If the parse objects are swapped, it's easy enough to swap back the net signatures so that they are in their originally assigned order.

**Review by notimaginative — APPROVED** [review]
LGTM

**Pull request merged**
