### PR TITLE
IPv6 support

### PR DESCRIPTION
**Pull request by notimaginative**
Adds IPv6 support and related changes. Leaving as draft until some final testing of the newest fixes are done.

NOTE: Drops support for Windows XP!

### CODE REVIEW

**Comment by JohnAFernandez** [comment]
Just one more test case to make sure this works.  IPv6 connecting with IPv6.  Dahblount and I had a partial success, but we hit another bug that I'm tracking down.

**Comment by JohnAFernandez** [comment]
No issues in testing.  The only thing Keeping this from merging is a review and the build issues on Travis and Appveyor

**Comment by asarium** [comment]
I'm going to push some changes to hopefully fix the CI failures by switching to the non-XP toolset.

**Comment by asarium** [comment]
The Mac build fails with this error:
```
/Users/travis/build/scp-fs2open/fs2open.github.com/code/network/psnet2.cpp:2349:53: error: use of undeclared identifier 'IPV6_ADD_MEMBERSHIP'
                if ( setsockopt(Psnet_mcast_socket, IPPROTO_IPV6, IPV6_ADD_MEMBERSHIP, reinterpret_cast<const char *>(&mRequest), sizeof(mRequest)) ) {
```

**Comment by notimaginative** [comment]
Ah, okay. It's a BSD thing, so I just need to tweak the `#ifdef` that fixes it for FreeBSD.

**Review by asarium — APPROVED** [review]
To be honest, I do not know enough about this code to effectively review it but I could not find anything that stood out significantly.

Once this is merged we should probably make an announcement on the forums that we are officially dropping XP support (finally).

**Pull request merged**
