### PR TITLE
Scpui loadout pools

### PR DESCRIPTION
**Pull request by MjnMixael**
API access to the ship and weapon loadout pools. Relies on #4694

### CODE REVIEW

**Review by BMagnu — CHANGES_REQUESTED** [review]
Hmm, I think it'd be better if you could pass Ship_class / Weapon_class userdata objects here instead of just an int. You should be able to easily get the index from those on the C++ side, and it'd easily allow to get shipclasses by name or from specific objects for example for these methods.

**Comment by MjnMixael** [comment]
That seems like unnecessary complexity for this specific case, though. These values are only valid after running initSelect() for the current mission. Seems like the script should do exactly what FSO does here; iterate over the entire list of weapons to build the icon list once. I don't see much use in trying to do that arbitrarily by name or object.

**Comment by MjnMixael** [comment]
> Hmm, I think it'd be better if you could pass Ship_class / Weapon_class userdata objects here instead of just an int. You should be able to easily get the index from those on the C++ side, and it'd easily allow to get shipclasses by name or from specific objects for example for these methods.

That seems like unnecessary complexity for this specific case, though. These values are only valid after running initSelect() for the current mission. Seems like the script should do exactly what FSO does here; iterate over the entire list of weapons to build the icon list once. I don't see much use in trying to do that arbitrarily by name or object.

**Review by BMagnu — APPROVED** [review]
Not too much a fan of the resulting API inconsistency to other places that need ship / weapon classes, but fair enough, regarding this specific use case

**Comment by MjnMixael** [comment]
Bah. Hold off on merging this. FSO writes to the pool directly as weapons and ships are out into the loadout and that is recalled if player_loadout is saved. I'm going to have to redo these as indexers so they can be written to also.

**Comment by MjnMixael** [comment]
Sorry to have you review this only to realize that I needed to change it. It's ready for real this time. Changed it from Func to Indexer and made the pools writable. Tested and working.

**Review by BMagnu — APPROVED** [review]

**Pull request merged**
