### PR TITLE
Don't search for empty sound names

### PR DESCRIPTION
**Pull request by Baezon**
If a sound entry is left completely blank, literally just
```
	+WarmupSound:
```
It will match the first index with an empty sound definition! This is bad.

### CODE REVIEW

**Comment by Goober5000** [comment]
Wouldn't empty sounds be called `empty` or `none` instead of being completely blank?

Also, would it be better to do a quick out on the blank name, rather than using the blank name to look through a bunch of entries that are going to be skipped anyway?

**Comment by Baezon** [comment]
When 'empty' is found it takes that to mean the filename should be literally empty i.e. the empty string. And its true I suppose, an empty string probably shouldn't get this far to start searching since with this it won't find anything anyway.

**Comment by Goober5000** [comment]
If you check at the top of the function whether `name` is a blank string, that should be sufficient I think.

**Review by Goober5000 — CHANGES_REQUESTED** [review]
Good, but make sure `name` isn't null before you dereference `name[0]`.  Null names also return -1.

**Review by Goober5000 — APPROVED** [review]

**Pull request merged**
