### PR TITLE
OpenGL: Refactor GLSL setup and remove DirectX Shader Model concept

### PR DESCRIPTION
**Pull request by Echelon9**
This patch set resulted from an initial desire to remove the engine's legacy use of a DirectX concept, Shader Models. On review of the relevant code there were a series of related refactors that could be made.

**Before merging, this patch set will require testing on diverse hardware and drivers**
*Whilst coded to strive for greater OpenGL and GLSL language specification conformance, we know drivers implement non-overlapping subsets of the standards.*

Tested on:
- [x] Linux (Mesa open source i965)
- [x] Linux (Mesa open source LLVMpipe)
- [ ] Linux (Mesa open source nv50 / nvc0)
- [x] Linux (Mesa open source r600 / radeonsi)
- [x] Linux (NVIDIA proprietary blob)
- [x] Linux (AMD proprietary blob)
- [x] Apple (NVIDIA)
- [ ] Apple (AMD)
- [x] Apple (Intel)
- [x] Windows (NVIDIA)
- [x] Windows (AMD)
- [x] Windows (Intel)

---

**Background**

On reviewing the OpenGL GLSL setup code in fs2open, it was apparent we use the `Use_GLSL` variable to encapsulate three different concepts. This is a mess.

At present, depending on the value, this variable is used for:

* Zero: Implies all GLSL shaders are disabled.
* One: Implies a deliberately partial GLSL shader support, as set by `-disable_glsl_model` command line option.
* Two+: Implies a "Shader Model" level, which is a DirectX concept and not relevant to OpenGL.

The last bullet point is important, as the code readability is improved by removing legacy references to DirectX-only concepts. A broad mapping between DirectX Shader Model versions and GLSL versions can be found [here](https://www.opengl.org/wiki/Detecting_the_Shader_Model).

**Implementation: Refactoring `Use_GLSL` variable**

So, in order to do something about this, I've refactored the `Use_GLSL` global variable to properly encapsulate only one concept. The branch does this by splitting the concept of (a) the GLSL version reported by the driver, and (b) whether a command line option has been used to disable GLSL shaders all together.

The third option, `-disable_glsl_model` appears less relevant today than when it was added. Today, most driver and GPU combinations will happily support > OpenGL GLSL 3.30 (cf. Steam Hardware Survey). There are a small number of users on older hardware that won't support GLSL shaders at all. There are significantly less in between, with partially working driver implementations. So I've taken this opportunity to remove a little used command line option.

The #version directive, which is required for standards conformance, is added in a dynamic manner. Am hoping this works across implementations, but I don't have all the hardware to test.

I'd be keen to see how users with a variety of GPUs and drivers handle this branch. Please test away.

Particularly keen to see if errors along the lines of "varying no longer support", or "global variable gl_TexCoord is removed after version 140".

**Mesa open source drivers**

Importantly, this branch was developed on an Intel GPU using the Linux Mesa open source drivers. The tooling and infrastructure is frankly fantastic. I want to be clear that the support and ability to see how the driver is internally handling the shaders is very helpful, and hopefully dispel some long-held, but now unsupported negative views on recent Intel GPUs.

There is further discussion in [this thread on the HLP forums](http://www.hard-light.net/forums/index.php?topic=90348.0).

### CODE REVIEW

**Comment by Echelon9** [comment]
This will fix #235.

**Comment by Echelon9** [comment]
Feedback from a Linux NVIDIA proprietary driver user (4.5.0 NVIDIA 352.41). Shader compile errors cause significant visual corruption.
```
  OpenGL Vendor    : NVIDIA Corporation
  OpenGL Renderer  : GeForce GTX 970/PCIe/SSE2
  OpenGL Version   : 4.5.0 NVIDIA 352.41
...
Compiling new shader:
	Particle Effects
   Loading built-in default shader for: effect-v.sdr
   Loading built-in default shader for: effect-particle-f.sdr
Vertex shader failed to compile:
0(3) : warning C7555: 'attribute' is deprecated, use 'in/out' instead
0(9) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(10) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(24) : error C7616: global function ftransform is removed after version 140
0(25) : error C7616: global variable gl_ModelViewMatrix is removed after version 140
0(25) : error C7616: global variable gl_Vertex is removed after version 140
0(30) : error C7616: global variable gl_TexCoord is removed after version 140
...
Compiling new shader:
	Video Playback
   Loading built-in default shader for: video-v.sdr
   Loading built-in default shader for: video-f.sdr
Vertex shader failed to compile:
0(5) : error C7616: global variable gl_TexCoord is removed after version 140
0(5) : error C7616: global variable gl_MultiTexCoord0 is removed after version 140
0(6) : error C7616: global variable gl_ProjectionMatrix is removed after version 140
0(6) : error C7616: global variable gl_ModelViewMatrix is removed after version 140
0(6) : error C7616: global variable gl_Vertex is removed after version 140
0(7) : warning C7533: global variable gl_FrontColor is deprecated after version 120
0(8) : warning C7533: global variable gl_FrontSecondaryColor is deprecated after version 120
```
This refactor has identified some limitations with how scalable our shaders are at present.

**Comment by Echelon9** [comment]
There's probably scope here to bifurcate some of the changes here into two separate patch sets. i.e. 
* those refactors that are going to be easier to coral through various drivers, and
* those which are proving problematic.

I'll consider.

**Comment by Echelon9** [comment]
OK, so I've backed out the most problematic commit. I'll ask testers to re try this branch

**Comment by Echelon9** [comment]
To resolve the FXAA shader compile error some have seen, I've pushed a further commit to my testing branch. Could those who saw this issue please retest?

**Comment by chief1983** [comment]
Ran the branch with latest master merged in on my MacBook Pro 15" with Intel Iris Pro (unsure which Iris Pro, just says it has 1536MB RAM).  Everything looked all right in game that I could tell, but there do seem to be some errors in the log output.  I was running just MediaVPs 2014.

```
Passed cmdline options:
  -missile_lighting
  -nomotiondebris
  -soft_particles
  -post_process
  -fxaa
  -fb_explosions
  -brief_lighting
  -enable_shadows
  -no_vsync
  -ballistic_gauge
  -dualscanlines
  -rearm_timer
  -targetinfo
  -3dwarp
  -snd_preload
  -mod MediaVPs_2014
  -no_set_gamma
  -window
...
Initializing OpenGL graphics device at 1024x768 with 32-bit color...
  Initializing SDL...
  Requested SDL Video values = R: 8, G: 8, B: 8, depth: 24, stencil: 8, double-buffer: 1, FSAA: 0
  Actual SDL Video values    = R: 8, G: 8, B: 8, depth: 24, stencil: 8, double-buffer: 1, FSAA: 0
  OpenGL Vendor    : Intel Inc.
  OpenGL Renderer  : Intel Iris Pro OpenGL Engine
  OpenGL Version   : 2.1 INTEL-10.6.33

  Using extension "GL_EXT_fog_coord".
  Using extension "GL_ARB_multitexture".
  Using extension "GL_ARB_texture_env_add".
  Using extension "GL_ARB_texture_compression".
  Using extension "GL_EXT_texture_compression_s3tc".
  Using extension "GL_EXT_texture_filter_anisotropic".
  Using extension "GL_ARB_texture_env_combine".
  Unable to find extension "GL_EXT_compiled_vertex_array".
  Using extension "GL_EXT_draw_range_elements".
  Using extension "GL_ARB_texture_mirrored_repeat".
  Using extension "GL_ARB_texture_non_power_of_two".
  Using extension "GL_ARB_vertex_buffer_object".
  Using extension "GL_ARB_pixel_buffer_object".
  Using extension "GL_SGIS_generate_mipmap".
  Using extension "GL_EXT_framebuffer_object".
  Using extension "GL_ARB_texture_rectangle".
  Using extension "GL_EXT_bgra".
  Using extension "GL_ARB_texture_cube_map".
  Using extension "GL_EXT_texture_lod_bias".
  Using extension "GL_ARB_point_sprite".
  Using extension "GL_ARB_shading_language_100".
  Using extension "GL_ARB_shader_objects".
  Using extension "GL_ARB_vertex_shader".
  Using extension "GL_ARB_fragment_shader".
  Using extension "GL_ARB_shader_texture_lod".
  Using extension "GL_ARB_texture_float".
  Using extension "GL_ARB_draw_elements_base_vertex".
  Using extension "GL_EXT_framebuffer_blit".
  Using extension "GL_EXT_geometry_shader4".
  Using extension "GL_EXT_texture_array".
  Unable to find extension "GL_ARB_uniform_buffer_object".
  Using extension "GL_EXT_transform_feedback".
  Using extension "GL_ARB_draw_instanced".
  Unable to find extension "GL_ARB_texture_buffer_object".

Compiling new shader:
	Particle Effects
   Loading built-in default shader for: effect-v.sdr
   Loading built-in default shader for: effect-particle-f.sdr
Shader Variant Features:
Compiling new shader:
	Particle Effects
   Loading built-in default shader for: effect-v.sdr
   Loading built-in default shader for: effect-particle-f.sdr
   Loading built-in default shader for: effect-screen-g.sdr
Shader Variant Features:
	Geometry shader point-based particles
Compiling new shader:
	Distortion Effects
   Loading built-in default shader for: effect-distort-v.sdr
   Loading built-in default shader for: effect-distort-f.sdr
Shader Variant Features:
Compiling new shader:
	Deferred Lighting
   Loading built-in default shader for: deferred-v.sdr
   Loading built-in default shader for: deferred-f.sdr
Shader Variant Features:
Compiling new shader:
	Clear Deferred Lighting Buffer
   Loading built-in default shader for: deferred-clear-v.sdr
   Loading built-in default shader for: deferred-clear-f.sdr
Shader Variant Features:

Compiling new shader:
	Post Processing
   Loading built-in default shader for: post-v.sdr
   Loading built-in default shader for: post-f.sdr
Shader Variant Features:
Compiling new shader:
	Bloom Brightpass
   Loading built-in default shader for: post-v.sdr
   Loading built-in default shader for: brightpass-f.sdr
Shader Variant Features:
Compiling new shader:
	Gaussian Blur
   Loading built-in default shader for: post-v.sdr
   Loading built-in default shader for: blur-f.sdr
Shader Variant Features:
	Horizontal blur pass
Compiling new shader:
	Gaussian Blur
   Loading built-in default shader for: post-v.sdr
   Loading built-in default shader for: blur-f.sdr
Shader Variant Features:
	Vertical blur pass
Compiling new shader:
	FXAA
   Loading built-in default shader for: fxaa-v.sdr
   Loading built-in default shader for: fxaa-f.sdr
Shader Variant Features:
Compiling new shader:
	FXAA Prepass
   Loading built-in default shader for: post-v.sdr
   Loading built-in default shader for: fxaapre-f.sdr
Shader Variant Features:
  Max texture units: 8 (16)
  Max client texture states: 8 (8)
  Max elements vertices: 1048575
  Max elements indices: 150000
  Max texture size: 16384x16384
  Max render buffer size: 16384x16384
  Can use compressed textures: YES
  Texture compression available: YES
  Post-processing enabled: YES
  Using trilinear texture filter.
  OpenGL Shader Version: 1.20
... OpenGL init is complete!
```

**Comment by Echelon9** [comment]
Thanks @chief1983 for testing, that looks like a solid i965 graphics card.

However, your extract of fs2open.log looks fine i.e. nothing out of the ordinary that I would have expected. Can you elaborate on what you meant by "but there do seem to be some errors in the log output"?

**Comment by chief1983** [comment]
I thought the 'Unable to find...' were bad things.  If not, then cool.  Gonna test my new Nvidia card on my Windows box shortly.

**Comment by Echelon9** [comment]
The fs2open engine is just reporting with that line that it can't find a given OpenGL extension that was either (a) never in Core, or (b) not in the OpenGL version you have available with your driver/hardware combo.

i.e. Specifically for `GL_ARB_uniform_buffer_object` it is an OpenGL 3.1 extension so not surprising it is not found in your OpenGL 2.1 context.

Where it *might* be an issue is if the fs2open engine cannot gracefully degrade if that extension isn't found. But that's a whole separate issue.

I'll mark your testing as positive for the Apple (Intel) checkbox.

**Comment by chief1983** [comment]
So, I feel like I'm not seeing normal maps with this build in game, even though they show up in the F3 lab.  The Ravana on massive battle (beams) just looks flat no matter how I approach it.  The Orion almost does seem to have them though, as does the Hecate, so I'm not really sure what's going on here.

**Comment by Echelon9** [comment]
@chief1983 would be keen to see your fs2open.log on the Windows / NVIDIA setup with this branch.

**Comment by chief1983** [comment]
Sorry for the delay.  Almost forgot about this.  This should be the log from my run where I saw this a few days ago.  http://pastebin.com/1JDevCbw

**Comment by Echelon9** [comment]
Thanks @chief1983 nothing glaring stands out on an initial review, and certainly after entering state GS_EVENT_ENTER_GAME (i.e. in game), there are GLSL shaders with the normal mapping variant compiled.

I presume you have seen on this same setup normal maps in game with nightly builds (just checking, I'm sure you've already done this basic step @chief1983).

Perhaps if still not coming up with anything, I could diff two fs2open.log when running through the same stages. One run with this branch build and another with a recent nightly.

**Comment by chief1983** [comment]
I might have been imagining this.  The normal maps might just appear weak at very close range on a capital ship.  They render the same in the F3 lab on the Ravana specifically.  I was trying to verify for sure I saw them in game on the Ravana with the latest nightly when I got a 'Ship rotated too far' assertion.  But that's another story.  I think Windows nVidia is probably good to go.

**Comment by asarium** [comment]
I checked this branch on windows with an AMD card. No errors were reported in the log and visually everything was fine (although destroyed subsystems didn't show up but I'll have to check if this is also present in master).
OpenGL info below:
```
  OpenGL Vendor    : ATI Technologies Inc.
  OpenGL Renderer  : AMD Radeon (TM) R9 380 Series
  OpenGL Version   : 4.5.13416 Compatibility Profile Context 15.300.1025.0
```

**Comment by asarium** [comment]
I also tested the Windows Intel drivers. They have issues with batched model rendering but that is also present in master so it's not specific to these changes. Other than that everything looks fine.

That brings us to 10/12 tested configurations. I doubt anyone still has a nv50 GPU and at this point we could assume that Macs with AMD cards probably work so I think this is ready to be merged.

**Comment by Echelon9** [comment]
Thanks for the further testing @asarium. I agree this PR is ready for be merged.

**Comment by Echelon9** [comment]
OK, so this PR has been rebased and I'm happy for this to be merged (once the buildbots return green).

There's been a significant variety of GPUs and operating systems / drivers tested by users, and the issues resolved. If there are any further corner cases that are shaken out once this lands I will address them is a later commit.

My next step will be to consider if we can adopt any of the dropped changes from this patch set with some further tweaks.

**Comment by asarium** [comment]
LGTM

**Pull request merged**
