### PR TITLE
Add waypoint-path hook variable to `On Waypoints Done` Hook

### PR DESCRIPTION
**Pull request by wookieejedi**
Originally the scripting hook `On Waypoints Done` only provided the ship or wing. This PR adds the the `Waypointpath` that was completed as an additional hook variable (ie hv.Waypointpath). Also, I tested and can confirm the new hook variable works as expected. 

Expands on PR #1985.

### CODE REVIEW

**Comment by wookieejedi** [comment]
Hmm only one section of travis failed, and the warning message doesn't seem that informative. Anyone have an insight as to why it failed?

**Comment by Goober5000** [comment]
Here's the failed section:

```
$ ./ci/travis/clang_tidy.sh

Running clang-tidy on changed files

error: PCH file uses an older PCH format that is no longer supported [clang-diagnostic-error]

Errors or warnings were detected in the clang-tidy output!
```

This is caused by an upgrade to clang-tidy in a previous PR that isn't playing well with our continuous integration.  We (mostly @asarium) are in the process of fixing it.  We've merged other PRs with integration errors this week, so we won't hold this one up if clang-tidy isn't completely fixed by then.

**Comment by wookieejedi** [comment]
Ah sounds good, thanks!

**Comment by wookieejedi** [comment]
Good idea, just updated.

**Pull request merged**
