### PR TITLE
Update .gitignore to include voice recognition files

### PR DESCRIPTION
**Pull request by asarium**

### CODE REVIEW

**Comment by MageKing17** [comment]
Eventually they should just stop being put in /code/sound/, but this can always be removed from .gitignore when that happens and, in the meantime, this *is* annoying.

**Comment by chief1983** [comment]
LGTM

**Comment by chief1983** [comment]
Darn, ninja'd

**Comment by asarium** [comment]
This will be fixed when CMake becomes the standard build system as those files are generated outside the source directory there.

**Pull request merged**
