### PR TITLE
Project removal 2016-01

### PR DESCRIPTION
**Pull request by chief1983**
After discussion at http://www.hard-light.net/forums/index.php?topic=91093.0, it seems like it should be safe enough to remove the following project files:

MSVC 6
MSVC 2005
MSVC 2008
MSVC 2012
Xcode

Of those 5, only one might possibly still work, but no one seems to care to keep the MSVC 2012 project around so I don't see a reason to keep maintaining it in the interim until CMake happens.  I have also renamed Xcode4 to Xcode in the second commit since it's actually more oriented to the latest Xcode available now.

### CODE REVIEW

**Comment by MageKing17** [comment]
Can we get VS 2015 in the AppVeyor configuration, if we're dropping 2012?

**Comment by chief1983** [comment]
Looks like the 2015 AppVeyor configuration worked fine, that makes me excited.  What say we all?  I'll be able to update the Mac nightly config once this is approved and merged so it can find the project in the new location.

**Comment by MageKing17** [comment]
Looks good to me, but I think we should have a few more eyes on something like this before merging.

**Comment by chief1983** [comment]
Definitely, just glad all the passes still worked.  I also bumped the thread on HLP but still no replies.

**Comment by asarium** [comment]
This has been sitting here for a week and the thread on HLP also didn't receive any replies. I think it's safe to merge this.

**Pull request merged**
