### PR TITLE
These std moves were suggested by Coverity as optimizations

### PR DESCRIPTION
**Pull request by JohnAFernandez**
I'm not even listing the issue numbers as there were more than 5.  Also, if we switch to c++14 in the future, there would more that we could do in Lambda expressions.

### CODE REVIEW

**Review by Goober5000 — APPROVED** [review]

**Comment by TRBlount** [comment]
I would practice caution here. Have these changes been tested? I did some digging and while it looks safe at a glance, I would not count on any compilers to catch if the moved variables get reused anywhere.

**Comment by JohnAFernandez** [comment]
Just going to leave it in draft until I can get a smoke test done.

**Comment by JohnAFernandez** [comment]
Smoke test done.  Everything that I can run seems to work after the change.

**Comment by JohnAFernandez** [comment]
Smoke test complete, with nothing to report.  Merging.

**Pull request merged**
