### PR TITLE
remove WF_NEVER_EXISTED

### PR DESCRIPTION
**Pull request by Goober5000**
See #379 for discussion and background.

### CODE REVIEW

**Comment by Goober5000** [comment]
Despite extensive discussion in #380, I still want to sanity check this with a test mission, in case there are any unknown unknowns lurking about.

**Comment by MageKing17** [comment]
Could maybe test it by flying through the retail campaign with cheats enabled and take out any enemy ships that want to launch fighters before they get a chance... see whether anything breaks (well, anything not related to ships dying too quickly).

**Comment by Goober5000** [comment]
Testing seems to validate the approach.  I built a simple mission with multiple waves of fighters arriving from an Orion, with a directive testing `is-destroyed-delay` for that wing.  I then traced through the code when the first wave of fighters had arrived but the Orion had departed / been destroyed before the second wave could launch.

In both cases, the code left the `sexp_query_has_yet_to_arrive()` function and returned `SEXP_FALSE` instead of the old `SEXP_CANT_EVAL`.  These have the same logical effect, except that the new `SEXP_FALSE` means that some sexps which previously registered as incomplete will now register as complete.

This change will actually have no effect on either directives or mission goals, because both of those rely on checking the mission log (i.e. `LOG_SHIP_DESTROYED`), which is not affected by the flag removal.

I'm trying to think of any possibility that an existing mission would be broken by this change, and I can't think of any realistic one.  A mission would have to have an event which tested a multiple-wave wing and relied on certain behavior *after* the first wave had arrived but *before* all waves had arrived.  The sexp would furthermore have to make a distinction between a sexp returning false and a sexp returning incomplete.  I don't think this is likely at all, especially since missions almost certainly never treat any wave different from any other wave.

**Comment by niffiwan** [comment]
LGTM

**Pull request merged**
