### PR TITLE
handle mod subfolders on unix

### PR DESCRIPTION
**Pull request by rtoijala**
Mod paths given using the -mod cmdline parameter currently cannot contain subfolders on unix.
This is stopping me putting all mods in a "mods" folder and the writing e.g
    -mod mods/fsport-mediavps_2014,mods/fsport,mods/MediaVPs_2014

This patchset allows mod subfolders and also backslashes instead of slashes for compatibility with mod.inis that are written for Windows.

The following modlist then works:
    -mod Mods/fsport-MediaVPs_2014,mods\fsport,mods\mediavps_2014
with the following directory structure
main folder
--- mods
------ fsport
------ fsport-mediavps_2014
------ MediaVPs_2014

Note that I wrote most of this code while taking part in a sleep deprivation experiment so I would appreciate a thorough review.

Edit: don't know how that one commit slipped in, nor how to remove it...

### CODE REVIEW

**Comment by asarium** [comment]
The code looks good to me but AFAIK @niffiwan had some changes that involved the mod system so I'll wait for him to comment before merging this.

**Comment by niffiwan** [comment]
OK, I've had a look through this and I can see a couple of issues, and I've got an observation :)

1) You should use ```vm_malloc```, ```vm_free``` & ```vm_strdup``` instead of the normal variants; we've added memory tracking to them in DEBUG.

2) You've removed an important feature, namely to find & include all the directories that match a case insensitive comparison. The mediavp_3612 mod is a prime example of why we need this.  The FSO installer downloads the main files (zipped in mediavps_3612) and a patch (zipped in MediaVPS_3612). If we grab just one directory, then some people will miss out on the patch, and others will have a broken mod because they've only found the patch dir (because the order dirs are returned from ```readdir``` is essentially random to the average user). 


Lastly the observation, I wonder if using C++ SCP_string's would be easier to write/maintain than C-style strings with all the attendant malloc/free/pointer arithmetic.

**Comment by rtoijala** [comment]
Thanks for the feedback, I'll look into this (though I'm not really comfortable with C++, never having learned it properly...)

**Comment by rtoijala** [comment]
Can I freely use C++11 features when implementing this?

**Comment by asarium** [comment]
You can use C++11 but currently we still support Visual Studio 2010 so there are some features you can't use (e.g. range based for loops or `enum class`).

The easiest way to test compatibility is to write code using the features you need and then letting AppVeyor check if VS 2010 can compile it. That way you don't need a VS 2010 install.

**Comment by rtoijala** [comment]
I started the implementation from scratch on a new branch, sol I'll open a new pull request to replace this one.

**Comment by MageKing17** [comment]
Let's close this one, then.

**Pull request closed without merging**
