### PR TITLE
Mantis 1826 Clean Patch Part 3

### PR DESCRIPTION
**Pull request by FSCyborg**
Most up to date version of the fix Mantis 1826, sans random whitespace edits and erroneous reverse commits.

Please hold on committing until Appveyor results are in so I can double check that I copied it correctly.

Final section.  I'm going to try pulling my local code directly from the SCP repository and then pushing commits to my fork before making a pull request.  That should avoid the awkward situation with updating my fork.

### CODE REVIEW

**Comment by FSCyborg** [comment]
Errors in this portion are caused by the fact that the new parts of the Netgame class are defined in Part 1.

**Comment by MageKing17** [comment]
Why can't you just... commit all three commits on the same branch, so there's only one pull request...?

**Comment by FSCyborg** [comment]
I was away from my main computer.  But I can do it now instead.

**Comment by Echelon9** [comment]
This PR should be cleaned up (i.e. closed), along with the associated #190.

**Pull request closed without merging**
