### PR TITLE
Allow for second-order lead indicator prediction

### PR DESCRIPTION
**Pull request by Baezon**
Adds a flag that will allow the lead indicator to predict changes in predicted position parabolically based on current rotvel. Allows for better prediction for turning targets but still limited by high time-to-target or fast turn speeds (a parabola can only approximate a circle so far). Might add circular prediction for high rotvel targets at some point but would be more complicated.

### CODE REVIEW

**Comment by z64555** [comment]
Hold up.  How well does this account for gliding targets, and targets that are side trusting during a turn?

**Comment by Baezon** [comment]
Velocity is luckily in world coords, so it is not affected by the actual forward heading of the ship in question, so it doesn't have any issues with gliding or sliding. Since the eventual newly predicted position of the ship is even more dependent on the current state of the ship, small changes _do_ have an exaggerated effect, causing the the lead indicator to be jitterier in question, and mitigating this is indeed part of the intention of the scalar.

**Comment by z64555** [comment]
Alright.  Looking at it again it assumes the rotvel has an effect on its vel, which as stated before is not the case during glide, but should work with normal mode/atmospheric modes of flight models, and with slower turning craft.

I'm conflicted about including this feature as a hardcode, because it has its flaws for gun sights, autoaim, and AI aiming.  I would reccomend running a test build with the changes in place to see how well the player and AI do vs. Standard in both player vs. AI and AI vs. Ai

**Comment by wookieejedi** [comment]
I'll also note some things I discovered when reviewing this. `polish_predicted_target_pos` is actually only used twice in the whole code. Once for predicting where a shot will land because of auto aim, and the other to draw the lead indicator. When it is called to draw the lead indicator it does not affect any shot placement only the hud gauge rendering position. Thus the only section that `polish_predicted_target_pos` is called where it could affect the angle of shots is line 11107 in `ship.cpp` and it is only checked if auto aim is enabled for the specific ship. Ultimately even if this flag behavior was set by a mod there would be not gameplay difference unless auto aim was also enabled.

**Comment by Baezon** [comment]
This is indeed not used by the AI it seems, I've updated the comment, since I thought it was, but should that be changed? It seems the AI is doing mostly things redundant with this function, and they could easily be updated to use this as well. Perhaps another flag?

**Comment by wookieejedi** [comment]
IIRC the AI does some extra things with the ai table values for `accuracy`, so it would be interesting to see where/how a new change like this would go into that logic flow. 

I'd vote that this stays as a separate flag just for auto-aim/lead indicator for the player. Many folks play with auto aim on and would appreciate the more accurate version, but they don't want the AI to get any more precise since that would break balance in previous missions. The AI related flag would be more useful for in progress missions or mods that have that enabled during mission development.

**Comment by Baezon** [comment]
> 
> 
> Alright. Looking at it again it assumes the rotvel has an effect on its vel, which as stated before is not the case during glide, but should work with normal mode/atmospheric modes of flight models, and with slower turning craft. Even though the phys_info is in the world frame, the way enemy_acc is calculated results in the same issue raised before.
> 
> I'm conflicted about including this feature as a hardcode, because it has its flaws for gun sights, autoaim, and AI aiming. I would reccomend running a test build with the changes in place to see how well the player and AI do vs. Standard in both player vs. AI and AI vs. Ai

Ah, I missed your response, but yes that is a good point, I did not consider that gliding would not result in changes to velocity based on rotvel, but I think this is ok. This is another good reason to not necessarily use 1 for your factor, as this effect would result in over-weighting effect of rotvel, but considering the status quo under-weights this effect, striking somewhere in between would be best. Given that a first-order approximation has done so well for so long, I think these flaws are ok in exchange for some  gain, as long as the flaws are at least noted. The modder should then be able to weight whether or not this kind of thing would be helpful for their situation, and by how much if so.

A better version of this code would use the change in velocity from last frame to this frame, which would also capture linear acceleration as well as being ambivalent towards gliding, but I wanted to avoid adding any extra fields to the state.

**Comment by wookieejedi** [comment]
Sounds like a good option for mods to have. I know Fate of the Galaxy will be using this feature, too.

@z64555 Sound good to you? If so I'll merge it.

**Pull request merged**
