### PR TITLE
My attempt to fix the HUD lock scoping issues raised by issue #456.

### PR DESCRIPTION
**Pull request by SamuelCho**
Eliminates unnecessary globals and conflicts of scope as raised by Goober. Also tries to address the issue that Yarn pointed out in issue https://github.com/scp-fs2open/fs2open.github.com/issues/456.

### CODE REVIEW

**Comment by Goober5000** [comment]
Good call on the `if(loop_locked_anim)` check.  I'll add that to my PR as well.

However I notice that you assign `Lock_anim.time_elapsed = 0.0f;` regardless of whether `Player_ai->current_target_is_locked` is true or not.  If it's false, you assign it on line 259, and if it's true, you assign it on line 274.  This occurs in the same frame, so I don't know that this fix will actually work.

Also, I kinda dislike the idea of assigning the Lock_ variables every frame, instead of once each in the init and reset methods.  It's less elegant.

**Comment by SamuelCho** [comment]
Are you sure that's right? `Lock_gauge.time_elapsed = 0.0f;` is the one that gets assigned in line 274, not `Lock_anim.time_elapsed`.

**Comment by Goober5000** [comment]
Whoops, you're right.  Sorry, it's 1am here. >.<

**Comment by SamuelCho** [comment]
So is there anything I can do to make this pull request better? Or do you prefer https://github.com/scp-fs2open/fs2open.github.com/pull/462 instead? I could track the state of `Player_ai->current_target_is_locked` and only change the HUD lock variables when `Player_ai->current_target_is_locked` is changed. 

I'm asking because I'm not 100% on-board with https://github.com/scp-fs2open/fs2open.github.com/pull/462/ having external `hud_lock` friend functions modifying the members of HudGaugeLock. I intended for the HUD code to mostly read state and handle itself for any setup regarding it's appearance. 

I mean, if you insist that your PR go in, I'll bite my tongue and merge it in. But just let it be known that, speaking as someone who designed the new HUD code (which let's be real, discredits my opinion more than it gives me credibility), I definitely prefer a solution that's managed within the scope of `HudGaugeLock`.

**Comment by The-E** [comment]
I would prefer a solution that is in line with the current architecture. If that architecture is flawed, then that is something that needs to be addressed, but that is outside the scope of a bugfix like this.

**Comment by Goober5000** [comment]
I prefer a solution that's managed within the scope of HudGaugeLock as well.  Almost everything about this PR is great, I just don't like the fact that certain values are being assigned identical values over and over and over again, every frame.

Part of the problem is that some of the functions are scoped within the HudGaugeLock class and some of them aren't.  Can you shed any light on the rationale for this?

**Comment by SamuelCho** [comment]
`HudGaugeLock::render()` is only supposed to handle the rendering logic. So stuff like `Lock_anim`, `Lock_gauge`, `Lock_gauge_draw_stamp`, and `Lock_gauge_draw` belong in the class because they exclusively handle what the gauge looks like. Those being declared outside was a mistake. A sheepish mistake. I fucked up when writing that code and that wasn't supposed to happen. Let's be clear about that.

`hud_do_lock_indicator` is the gameplay logic. It handles when the lock happens and when the player is able to fire. Any gameplay logic `hud_do_lock_indicator` touches is read by `HudGaugeLock`. `HudGaugeLock` should only read outside variables while only modifying itself based off what it needs to show what the state of the gameplay lock logic is. So that involves updating timers and switches accordingly based off of `Player_ai->current_target_is_locked` and `lock_world_pos`.

So getting back to what we were talking about. `Lock_gauge.time_elapsed = 0.0f;` was already in the original HUD code. If we're locked on a target, that will repeatedly get assigned every frame. `Lock_anim`, `Lock_gauge_draw_stamp`, and `Lock_gauge_draw` just happen to fall in the opposite case.

If we want to make sure those are only set once upon `Player_ai->current_target_is_locked` changing state, sure, I'll be more than happy to oblige.

**Comment by Goober5000** [comment]
I meant to look at this yesterday... and then the Internet went out. :sigh: I'll check it out this evening.

**Comment by Goober5000** [comment]
So the design is that the class only encapsulates rendering and relies on the game logic to handle state.  Okay, that all makes sense and sounds reasonable.

> If we want to make sure those are only set once upon Player_ai->current_target_is_locked changing state, sure, I'll be more than happy to oblige.

How would you propose to do this?

And while I'm here, @Yarn366, does this fix all the problems you noticed in #456?

**Comment by Yarn366** [comment]
Yes, this fixes the lock animation.

**Comment by SamuelCho** [comment]
>How would you propose to do this?

Probably by saving the last changed value of `Player_ai->current_target_is_locked`. Do a simple compare. If `Player_ai->current_target_is_locked` has changed from what we currently have, then we do the appropriate action based on what the new value is.

>Yes, this fixes the lock animation.

Cool, thanks for checking that.

**Comment by Goober5000** [comment]
> Probably by saving the last changed value of `Player_ai->current_target_is_locked`.

K.  That's what I was thinking too, but I was wondering if there was some secret function call I hadn't noticed. :)

I was wondering if it would be appropriate to add another field to the `ai_info` struct, but we already have `last_dist`, `last_speed`, `last_target`, and `last_subsys_target`, so a `last_locked` field wouldn't be unprecedented.  Let's go ahead and do that.

**Comment by SamuelCho** [comment]
Lock timers and switches now won't reset willy nilly every frame. That should fulfill the requests stipulated to me to get this PR approved.

**Comment by Goober5000** [comment]
Yeah, that works.  I guess `Last_lock_status` doesn't have to be part of `ai_info` after all.

This is good enough to be merged, IMHO.  I have two more minor requests, more for cleanup than anything pressing:

a) Move `Last_lock_status = locked;` inside the if() block immediately preceding it, since it only needs to be assigned if the values are different
b) Remove lines 283-290, since that's obsolete and commented-out code that looks left-over from FS1 days.  (Then remove the whole `hud_draw_diamond()` function since it's the only place that's used.)

Feel free to decline if you're sick of working on this PR though. :)

Afterwards we can merge this, close #462, and resolve #456.

**Comment by Goober5000** [comment]
@SamuelCho can you make those last two tweaks for us to merge this PR?  You shouldn't need a dev environment; they are both quite simple.

Or I can try doing them, if you're okay with me pushing to your branch...

**Comment by SamuelCho** [comment]
I finally had time to do the requested revisions.

**Comment by MageKing17** [comment]
Changes look good to me.

**Pull request merged**
