### PR TITLE
Adding parsing to player_tips_init()

### PR DESCRIPTION
**Pull request by maingotj**
proposed fix for #4648

### CODE REVIEW

**Review by Goober5000 — COMMENTED** [review]
Did you omit any files from your commit?  This is either a typo or a reference to a nonexistent function.

**Comment by EatThePath** [comment]
@maingotj  This change is outside my wheelhouse so I'll leave it for someone else to review, but I wanted to say hello and welcome! Thank you for submitting code. 
After any PR is submitted there's some automatic compilation checks that run on submissions, and it looks like they hit a snag in your code. Digging the actual errors out of the compile logs can be a pain, so I've copied it out in this case.
```
/__w/fs2open.github.com/fs2open.github.com/code/menuui/playermenu.cpp: In function 'void player_tips_init()':
/__w/fs2open.github.com/fs2open.github.com/code/menuui/playermenu.cpp:1394:62: error: 'transstuff_and_malloc_string' was not declared in this scope; did you mean 'stuff_and_malloc_string'?
 1394 |    Player_tips[Num_player_tips++] = message_translate_tokens(transstuff_and_malloc_string(F_NAME, NULL));
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                              stuff_and_malloc_string
/__w/fs2open.github.com/fs2open.github.com/code/menuui/playermenu.cpp:1394:37: error: 'message_translate_tokens' was not declared in this scope
 1394 |    Player_tips[Num_player_tips++] = message_translate_tokens(transstuff_and_malloc_string(F_NAME, NULL));
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by z64555** [comment]
@maingotj Welcome, please be sure the [Contribution Guidelines](https://github.com/scp-fs2open/fs2open.github.com/wiki/Code-Contributions) our wiki.

**Review by Goober5000 — COMMENTED** [review]
You're assigning a SCP_string to a char* here.  This doesn't compile.

You are conceptually on the right track, but you'll need to switch between C-strings and SCP_strings as necessary, plus ensure that the final string is malloc'd so that it can be freed later.

**Comment by wookieejedi** [comment]
#4648 was fixed with #4808 so I'll close this soon unless there are any objections?

**Pull request closed without merging**
