### PR TITLE
Integrate Coverity with Travis CI

### PR DESCRIPTION
**Pull request by niffiwan**
This should let Coverity run a scan via Travis whenever commits
are pushed to the "coverity_scan" branch.
Some hackery is required to avoid submitting too many builds to
Coverity. See travis-ci/travis-ci#1975 for details.

### CODE REVIEW

**Comment by asarium** [comment]
Can you merge with with the recent travis changes?

**Comment by niffiwan** [comment]
yep, will do

**Comment by niffiwan** [comment]
and done; tested [here](https://travis-ci.org/niffiwan/fs2open.github.com/builds/77436278), expected output is that build 1 fails because my fork is not setup in Coverity; the rest of the builds abort because they're not the 1st build

**Comment by asarium** [comment]
GitHub still says that there are merge conflicts.

**Comment by niffiwan** [comment]
:confused: it looks good to me? 

    This branch is up-to-date with the base branch
    Merging can be performed automatically.

**Comment by asarium** [comment]
:confused: I see the same now. Even the changes were outdated the last time I checked.
Well, doesn't matter now. Looks good to me.

**Pull request merged**
