### PR TITLE
Fix or suppress warnings in stb_image

### LINKED ISSUE #1244: Nanovg warnings on Debian Stretch
I set up a Debian VPS and set it to upgrade to stretch, so along with that came GCC 6.3.0.  I think that's newer than anything we've been testing for, but it looks like the nanovg library we added recently has quite a few complaints with it.
```
[ 25%] Building C object code/CMakeFiles/code.dir/graphics/paths/nanovg/nanovg.c.o
In file included from /usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/nanovg.c:25:0:
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h: In function 'stbi__convert_format':
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1360:44: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
       #define CASE(a,b)   case COMBO(a,b): for(i=x-1; i >= 0; --i, src += a, dest += b)
                                            ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1364:10: note: in expansion of macro 'CASE'
          CASE(1,2) dest[0]=src[0], dest[1]=255; break;
          ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1364:49: note: ...this statement, but the la tter is misleadingly indented as if it is guarded by the 'for'
          CASE(1,2) dest[0]=src[0], dest[1]=255; break;
                                                 ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1360:44: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
       #define CASE(a,b)   case COMBO(a,b): for(i=x-1; i >= 0; --i, src += a, dest += b)
                                            ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1365:10: note: in expansion of macro 'CASE'
          CASE(1,3) dest[0]=dest[1]=dest[2]=src[0]; break;
          ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1365:52: note: ...this statement, but the la tter is misleadingly indented as if it is guarded by the 'for'
          CASE(1,3) dest[0]=dest[1]=dest[2]=src[0]; break;
                                                    ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1360:44: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
       #define CASE(a,b)   case COMBO(a,b): for(i=x-1; i >= 0; --i, src += a, dest += b)
                                            ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1366:10: note: in expansion of macro 'CASE'
          CASE(1,4) dest[0]=dest[1]=dest[2]=src[0], dest[3]=255; break;
          ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1366:65: note: ...this statement, but the la tter is misleadingly indented as if it is guarded by the 'for'
          CASE(1,4) dest[0]=dest[1]=dest[2]=src[0], dest[3]=255; break;
                                                                 ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1360:44: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
       #define CASE(a,b)   case COMBO(a,b): for(i=x-1; i >= 0; --i, src += a, dest += b)
                                            ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1367:10: note: in expansion of macro 'CASE'
          CASE(2,1) dest[0]=src[0]; break;
          ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1367:36: note: ...this statement, but the la tter is misleadingly indented as if it is guarded by the 'for'
          CASE(2,1) dest[0]=src[0]; break;
                                    ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1360:44: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
       #define CASE(a,b)   case COMBO(a,b): for(i=x-1; i >= 0; --i, src += a, dest += b)
                                            ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1368:10: note: in expansion of macro 'CASE'
          CASE(2,3) dest[0]=dest[1]=dest[2]=src[0]; break;
          ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1368:52: note: ...this statement, but the la tter is misleadingly indented as if it is guarded by the 'for'
          CASE(2,3) dest[0]=dest[1]=dest[2]=src[0]; break;
                                                    ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1360:44: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
       #define CASE(a,b)   case COMBO(a,b): for(i=x-1; i >= 0; --i, src += a, dest += b)
                                            ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1369:10: note: in expansion of macro 'CASE'
          CASE(2,4) dest[0]=dest[1]=dest[2]=src[0], dest[3]=src[1]; break;
          ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1369:68: note: ...this statement, but the la tter is misleadingly indented as if it is guarded by the 'for'
          CASE(2,4) dest[0]=dest[1]=dest[2]=src[0], dest[3]=src[1]; break;
                                                                    ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1360:44: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
       #define CASE(a,b)   case COMBO(a,b): for(i=x-1; i >= 0; --i, src += a, dest += b)
                                            ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1370:10: note: in expansion of macro 'CASE'
          CASE(3,4) dest[0]=src[0],dest[1]=src[1],dest[2]=src[2],dest[3]=255; break;
          ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1370:78: note: ...this statement, but the la tter is misleadingly indented as if it is guarded by the 'for'
          CASE(3,4) dest[0]=src[0],dest[1]=src[1],dest[2]=src[2],dest[3]=255; break;
                                                                              ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1360:44: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
       #define CASE(a,b)   case COMBO(a,b): for(i=x-1; i >= 0; --i, src += a, dest += b)
                                            ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1371:10: note: in expansion of macro 'CASE'
          CASE(3,1) dest[0]=stbi__compute_y(src[0],src[1],src[2]); break;
          ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1371:67: note: ...this statement, but the la tter is misleadingly indented as if it is guarded by the 'for'
          CASE(3,1) dest[0]=stbi__compute_y(src[0],src[1],src[2]); break;
                                                                   ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1360:44: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
       #define CASE(a,b)   case COMBO(a,b): for(i=x-1; i >= 0; --i, src += a, dest += b)
                                            ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1372:10: note: in expansion of macro 'CASE'
          CASE(3,2) dest[0]=stbi__compute_y(src[0],src[1],src[2]), dest[1] = 255; break;
          ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1372:82: note: ...this statement, but the la tter is misleadingly indented as if it is guarded by the 'for'
          CASE(3,2) dest[0]=stbi__compute_y(src[0],src[1],src[2]), dest[1] = 255; break;
                                                                                  ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1360:44: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
       #define CASE(a,b)   case COMBO(a,b): for(i=x-1; i >= 0; --i, src += a, dest += b)
                                            ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1373:10: note: in expansion of macro 'CASE'
          CASE(4,1) dest[0]=stbi__compute_y(src[0],src[1],src[2]); break;
          ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1373:67: note: ...this statement, but the la tter is misleadingly indented as if it is guarded by the 'for'
          CASE(4,1) dest[0]=stbi__compute_y(src[0],src[1],src[2]); break;
                                                                   ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1360:44: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
       #define CASE(a,b)   case COMBO(a,b): for(i=x-1; i >= 0; --i, src += a, dest += b)
                                            ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1374:10: note: in expansion of macro 'CASE'
          CASE(4,2) dest[0]=stbi__compute_y(src[0],src[1],src[2]), dest[1] = src[3]; break;
          ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1374:85: note: ...this statement, but the la tter is misleadingly indented as if it is guarded by the 'for'
          CASE(4,2) dest[0]=stbi__compute_y(src[0],src[1],src[2]), dest[1] = src[3]; break;
                                                                                     ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1360:44: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
       #define CASE(a,b)   case COMBO(a,b): for(i=x-1; i >= 0; --i, src += a, dest += b)
                                            ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1375:10: note: in expansion of macro 'CASE'
          CASE(4,3) dest[0]=src[0],dest[1]=src[1],dest[2]=src[2]; break;
          ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1375:66: note: ...this statement, but the la tter is misleadingly indented as if it is guarded by the 'for'
          CASE(4,3) dest[0]=src[0],dest[1]=src[1],dest[2]=src[2]; break;
                                                                  ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h: In function 'stbi__build_fast_ac':
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:1580:33: warning: left shift of negative val ue [-Wshift-negative-value]
             if (k < m) k += (-1 << magbits) + 1;
                                 ^~
In file included from /usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/nanovg.c:25:0:
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h: In function 'stbi__create_png_image_raw':
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4086:17: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
                 for (k=0; k < nk; ++k)
                 ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4090:13: note: in expansion of macro 'CASE'
             CASE(STBI__F_sub)          cur[k] = STBI__BYTECAST(raw[k] + cur[k-filter_bytes]); break;
             ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4090:95: note: ...this statement, but the la tter is misleadingly indented as if it is guarded by the 'for'
             CASE(STBI__F_sub)          cur[k] = STBI__BYTECAST(raw[k] + cur[k-filter_bytes]); break;
                                                                                               ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4086:17: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
                 for (k=0; k < nk; ++k)
                 ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4091:13: note: in expansion of macro 'CASE'
             CASE(STBI__F_up)           cur[k] = STBI__BYTECAST(raw[k] + prior[k]); break;
             ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4091:84: note: ...this statement, but the la tter is misleadingly indented as if it is guarded by the 'for'
             CASE(STBI__F_up)           cur[k] = STBI__BYTECAST(raw[k] + prior[k]); break;
                                                                                    ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4086:17: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
                 for (k=0; k < nk; ++k)
                 ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4092:13: note: in expansion of macro 'CASE'
             CASE(STBI__F_avg)          cur[k] = STBI__BYTECAST(raw[k] + ((prior[k] + cur[k-filter_bytes])>>1)); break;
             ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4092:113: note: ...this statement, but the l atter is misleadingly indented as if it is guarded by the 'for'
             CASE(STBI__F_avg)          cur[k] = STBI__BYTECAST(raw[k] + ((prior[k] + cur[k-filter_bytes])>>1)); break;
                                                                                                                 ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4086:17: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
                 for (k=0; k < nk; ++k)
                 ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4093:13: note: in expansion of macro 'CASE'
             CASE(STBI__F_paeth)        cur[k] = STBI__BYTECAST(raw[k] + stbi__paeth(cur[k-filter_bytes],prior[k],prior [k-filter_bytes])); break;
             ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4093:139: note: ...this statement, but the l atter is misleadingly indented as if it is guarded by the 'for'
             CASE(STBI__F_paeth)        cur[k] = STBI__BYTECAST(raw[k] + stbi__paeth(cur[k-filter_bytes],prior[k],prior [k-filter_bytes])); break;
                                                                                                                                            ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4086:17: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
                 for (k=0; k < nk; ++k)
                 ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4094:13: note: in expansion of macro 'CASE'
             CASE(STBI__F_avg_first)    cur[k] = STBI__BYTECAST(raw[k] + (cur[k-filter_bytes] >> 1)); break;
             ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4094:102: note: ...this statement, but the l atter is misleadingly indented as if it is guarded by the 'for'
             CASE(STBI__F_avg_first)    cur[k] = STBI__BYTECAST(raw[k] + (cur[k-filter_bytes] >> 1)); break;
                                                                                                      ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4086:17: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
                 for (k=0; k < nk; ++k)
                 ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4095:13: note: in expansion of macro 'CASE'
             CASE(STBI__F_paeth_first)  cur[k] = STBI__BYTECAST(raw[k] + stbi__paeth(cur[k-filter_bytes],0,0)); break;
             ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4095:112: note: ...this statement, but the l atter is misleadingly indented as if it is guarded by the 'for'
             CASE(STBI__F_paeth_first)  cur[k] = STBI__BYTECAST(raw[k] + stbi__paeth(cur[k-filter_bytes],0,0)); break;
                                                                                                                ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4104:20: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
                    for (k=0; k < filter_bytes; ++k)
                    ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4106:13: note: in expansion of macro 'CASE'
             CASE(STBI__F_none)         cur[k] = raw[k]; break;
             ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4106:57: note: ...this statement, but the la tter is misleadingly indented as if it is guarded by the 'for'
             CASE(STBI__F_none)         cur[k] = raw[k]; break;
                                                         ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4104:20: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
                    for (k=0; k < filter_bytes; ++k)
                    ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4107:13: note: in expansion of macro 'CASE'
             CASE(STBI__F_sub)          cur[k] = STBI__BYTECAST(raw[k] + cur[k- output_bytes]); break;
             ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4107:96: note: ...this statement, but the la tter is misleadingly indented as if it is guarded by the 'for'
             CASE(STBI__F_sub)          cur[k] = STBI__BYTECAST(raw[k] + cur[k- output_bytes]); break;
                                                                                                ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4104:20: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
                    for (k=0; k < filter_bytes; ++k)
                    ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4108:13: note: in expansion of macro 'CASE'
             CASE(STBI__F_up)           cur[k] = STBI__BYTECAST(raw[k] + prior[k]); break;
             ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4108:84: note: ...this statement, but the la tter is misleadingly indented as if it is guarded by the 'for'
             CASE(STBI__F_up)           cur[k] = STBI__BYTECAST(raw[k] + prior[k]); break;
                                                                                    ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4104:20: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
                    for (k=0; k < filter_bytes; ++k)
                    ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4109:13: note: in expansion of macro 'CASE'
             CASE(STBI__F_avg)          cur[k] = STBI__BYTECAST(raw[k] + ((prior[k] + cur[k- output_bytes])>>1)); break ;
             ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4109:114: note: ...this statement, but the l atter is misleadingly indented as if it is guarded by the 'for'
             CASE(STBI__F_avg)          cur[k] = STBI__BYTECAST(raw[k] + ((prior[k] + cur[k- output_bytes])>>1)); brea  ;
                                                                                                                  ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4104:20: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
                    for (k=0; k < filter_bytes; ++k)
                    ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4110:13: note: in expansion of macro 'CASE'
             CASE(STBI__F_paeth)        cur[k] = STBI__BYTECAST(raw[k] + stbi__paeth(cur[k- output_bytes],prior[k],prio r[k- output_bytes])); break;
             ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4110:141: note: ...this statement, but the l atter is misleadingly indented as if it is guarded by the 'for'
             CASE(STBI__F_paeth)        cur[k] = STBI__BYTECAST(raw[k] + stbi__paeth(cur[k- output_bytes],prior[k],prio r[k- output_bytes])); break;
                                                                                                                                              ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4104:20: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
                    for (k=0; k < filter_bytes; ++k)
                    ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4111:13: note: in expansion of macro 'CASE'
             CASE(STBI__F_avg_first)    cur[k] = STBI__BYTECAST(raw[k] + (cur[k- output_bytes] >> 1)); break;
             ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4111:103: note: ...this statement, but the l atter is misleadingly indented as if it is guarded by the 'for'
             CASE(STBI__F_avg_first)    cur[k] = STBI__BYTECAST(raw[k] + (cur[k- output_bytes] >> 1)); break;
                                                                                                       ^~~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4104:20: warning: this 'for' clause does not  guard... [-Wmisleading-indentation]
                    for (k=0; k < filter_bytes; ++k)
                    ^
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4112:13: note: in expansion of macro 'CASE'
             CASE(STBI__F_paeth_first)  cur[k] = STBI__BYTECAST(raw[k] + stbi__paeth(cur[k- output_bytes],0,0)); break;
             ^~~~
/usr/share/games/fs2source/fs2_open/code/graphics/paths/nanovg/stb_image.h:4112:113: note: ...this statement, but the l atter is misleadingly indented as if it is guarded by the 'for'
             CASE(STBI__F_paeth_first)  cur[k] = STBI__BYTECAST(raw[k] + stbi__paeth(cur[k- output_bytes],0,0)); break;
                                                                                                                 ^~~~~
```

### PR DESCRIPTION
**Pull request by asarium**
This fixes #1244.

### CODE REVIEW

**Comment by chief1983** [comment]
Not really a fan of globally disabling another warning type without a written explanation.  With all the changes to the .h is that even necessary though?  Looks like you updated what is a third party header?

**Comment by asarium** [comment]
I wouldn't have disabled the warning if it would have been fixed by the updates. The reason I disabled that warning is that left shifting of negative values is undefined by the standard and, as far as I know, there is no way to fix this issue without major changes to the code and I don't want to do that in a third-party library.

**Comment by chief1983** [comment]
Any way to avoid disabling a third party lib warning globally for our project?  That's the result if I understand it correctly?

**Comment by asarium** [comment]
I could disable the warning where the header is included but that is also in a third-party file but I guess I could to that.

**Comment by asarium** [comment]
I removed the global suppression again and made it only appear for the stb_image header.

**Comment by chief1983** [comment]
Hmm, gcc5 didn't seem to like that pragma line.

**Comment by asarium** [comment]
I fixed the error by doing a version check before the `#pragma`. Now it works again.

**Pull request merged**
