### PR TITLE
Ai chase ship class

### PR DESCRIPTION
**Pull request by Goober5000**
Implements the "chase any ship of a certain class" AI goal seen in TIE Fighter.  Also adds FRED and Lua support.

### CODE REVIEW

**Comment by Goober5000** [comment]
I recommending reviewing and merging #931 before this one, as it contains a number of infrastructure changes that are in this changeset but unrelated to ai-chase-ship-class.

**Comment by Goober5000** [comment]
Rebased on latest master, incorporating the changes from #931.

**Comment by bryansee** [comment]
Excuse me, can this be implemented in objecttypes.tbl?

**Comment by The-E** [comment]
Unless you explain what exactly you want this to do, no.

**Comment by bryansee** [comment]
I mean the +Player Orders: section.

**Comment by MageKing17** [comment]
Not easily; you'd need the ability to select a ship class to attack. Without that, this only makes sense for FREDers.

**Pull request merged**
