### PR TITLE
Make "Normal" the default option for Messages

### PR DESCRIPTION
**Pull request by JohnAFernandez**
Moves messages to the more suitable default of normal.  Also adds clarifying documentation.

As requested by @MjnMixael

### CODE REVIEW

**Review by wookieejedi — APPROVED** [review]
Good idea, and LGTM.

**Review by MageKing17 — APPROVED** [review]
A straightforward change, and a sensible one.

**Comment by JohnAFernandez** [comment]
With two good reviews on this simple patch, I'll go ahead and merge.

**Comment by Goober5000** [comment]
Erg, wish I had seen this before it was merged.  I'll add a proper fix to my implementation of send-message-chain.

**Pull request merged**
