### PR TITLE
Add option to dump pilot files in JSON format

### PR DESCRIPTION
**Pull request by niffiwan**
With current format settings, 1000x easier to read than raw files
Downside is that the files are much larger; ~33k-200k
    (size could be reduced by using a less readable format
    and relying on external JSON viewers)
Controlled by cmdline param -json_pilot
    (autoenabled in debug mode)
JSON format files use .plj & .csg as the extensions **NOTE** Commit log has a typo, should be .plj and .csj **END NOTE**
Could be extended in future to use JSON as pilotfile format
    (i.e. read in JSON)

### CODE REVIEW

**Comment by niffiwan** [comment]
I've finally got around to updating this for the latest master; it should now be ready for merging (pending review of course)

**Comment by asarium** [comment]
Just a few things I noticed:
1. jansson uses `malloc` and `free`, it may be a good idea to use the library mechanisms to inject our memory allocators.
2. We could use `json_dump_callback` to reduce memory usage by directly writing the file to disk.
3. Enabling it by default even if only in debug doesn't seem like a good idea if it creates files that have sizes between 50k and 200k.
4. We could use zlib to create gzip compressed files of this data. This may even make it possible to switch from binary files to compressed JSON in the future.

**Comment by niffiwan** [comment]
These all good points, it may just take me a little while to implement them :) For instance, by changing the output format to a less "pretty" one the file sizes dropped from 420kb (oops!) to 130kb, and 42kb to 17kb. Of course compression via zlib would be even better.

**Comment by asarium** [comment]
I'll try implementing the zlib compression but I'll have to read some documentation in order to create a file that can be read by standard archive programs. If that works there's no reason to keep using binary files (although it would introduce yet another migration step).

**Comment by chief1983** [comment]
For the ship info to json stuff I was working on, I was going to use a command line option to control it.  And personally I think uncompressed would be fine if that was the case, since right now debugging would be the primary purpose for this and compression is just another step in the way of the data.

**Comment by niffiwan** [comment]
OK, I'll implement the 1st three of @asarium's points in this PR and leave the zlib compression for a separate PR. I'll also leave the output pretty for now to minimise the data transformations required when debugging, but this can be reviewed once zlib is implemented and we can see the impact that pretty output has on the size of the compressed files.

**Comment by chief1983** [comment]
If you're going to make it configurable via a command line option, you can look at what I was working on in the commit https://github.com/scp-fs2open/fs2open.github.com/commit/7040c4c17e378edbd51e7098318198ed6a88a054 since I was hoping to get that in at some point too.

**Comment by chief1983** [comment]
Also, making it configurable whether to do this or not might be easier with an approach like I took, where instead of having the JSON conversions interspersed within the existing parsing code, that a separate function could go over the pilot object after regular parsing and convert it to JSON.  I worry this approach could make the pilot code significantly more difficult to grok.

**Comment by niffiwan** [comment]
I thought about having the JSON dump in a separate set of functions as interspersed is kinda ugly. However I also thought that'd make it easier to forget to update the JSON dump if/when new pilot data is added. Anyway, I haven't looked at your code in detail yet, I'll make sure I do that before finalising this PR.

**Comment by niffiwan** [comment]
feature added in #854, closing

**Pull request closed without merging**
