### PR TITLE
Resolve order of precedence compiler warning.

### PR DESCRIPTION
**Pull request by Echelon9**
Fix issue #206

### CODE REVIEW

**Comment by Echelon9** [comment]
Looks like an unrelated change in MSVC_2013 causing compiler issue....

**Comment by Echelon9** [comment]
... and all clear from continuous integration. PR ready for merge.

**Comment by Goober5000** [comment]
Looks good.  But I would suggest also putting parentheses around obj->type == OBJ_FIREBALL, for consistency's sake.

**Comment by Echelon9** [comment]
Pushed to PR again, to reflect @Goober5000's code review comment.

**Comment by Goober5000** [comment]
Easy approval.

**Pull request merged**
