### PR TITLE
Ignore all OS events when loading a mission

### PR DESCRIPTION
**Pull request by asarium**
This should fix the "Application unresponsive" errors.

The initial version based on master (#491) had a few problems because the events were actually processed. This should fix those issues because the events are only retrieved but not processed.

### CODE REVIEW

**Comment by MageKing17** [comment]
Won't this result in some things potentially getting out of sync, like keyboard state if somebody starts  or stops holding down a key in the middle of loading?

**Comment by asarium** [comment]
Damn, of course that would cause issues.

How about saving the events in a vector and replaying them in the next `os_poll` call?

**Comment by MageKing17** [comment]
That would obviously more closely match current behavior, assuming the events are all ultimately processed in the same order they were received (need to make sure the buffered events all get processed before the normal event processing resumes).

**Comment by asarium** [comment]
I implemented the buffered events approach and it seems to be working fine.

**Comment by asarium** [comment]
Resubmitted as #664.

**Pull request closed without merging**
