### PR TITLE
Remove "not enough points in path" warning

### PR DESCRIPTION
**Pull request by The-E**
Change this warning to a log print. This is only an issue when it's an issue, and most of the time it's not

### CODE REVIEW

**Comment by Goober5000** [comment]
Why was this approved?  This has been an issue on every mod where I've seen the warning appear.  (I remember that a large number of fighters and bombers had this issue when I worked on the Inferno Classic rerelease a few months ago.)  If the path has too few points, the docking ship will start slewing too early, causing docking to be unnecessarily delayed, or will clip through the ship it is docking to.

The purpose of warnings is to alert mod designers to fix incorrect data in their mod, and bad docking paths are certainly worth fixing.  Warnings are only shown during debug builds, so end-users playing release builds will not see them.

**Comment by asarium** [comment]
Warnings are typically used for situations where the engine has detected that something is wrong with the mod data and corrected it. In this case no action is taken by the engine which makes it unusual to use a warning here. The warning is still there in the debug log so a mod author is still being notified that there *might* be an issue.

**Comment by Goober5000** [comment]
Warnings are used regardless of whether the engine has corrected the problem or not.  Sometimes the correction must be done manually by the mod designer, and this is one such case.

The engine still takes action in that it tries to accommodate the shortened path.  But as I said, this often leads to unnaturally slewing or too-close clipping.  The first case can interfere with event timing in the mission; the second case leads to blatant visual errors.

**Comment by asarium** [comment]
Again, it *can* lead to visual error but it doesn't have to. If the path happens to look ok then this is a false positive that would annoy modders needlessly.

**Pull request merged**
