### PR TITLE
update ffmpeg support for 5.0+ API changes

### LINKED ISSUE #3926: 21.4.1 fails to build with ffmpeg >= 5.0
21.4.1 while it builds fine with ffmpeg 4.4.1 it fails to build with the just released ffmpeg 5.0:

```
[...]
[ 51%] Building CXX object code/CMakeFiles/code.dir/cutscene/ffmpeg/VideoDecoder.cpp.o
cd /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/build/code && /usr/bin/x86_64-pc-linux-gnu-c++ -DANTLR4CPP_STATIC -DCMAKE_PCH -DNDEBUG -DROCKET_STATIC_LIB -DSCP_UNIX -DUSE_OPENAL -DVK_NO_PROTOTYPES -DVULKAN_HPP_DISPATCH_LOADER_DYNAMIC=1 -DWITH_FFMPEG -DWITH_OPENGL -DWITH_VULKAN -D_REENTRANT -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS=1 -I/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code -I/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/freespace2 -I/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/build/generated_source -I/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/build/generated_source/code -I/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/build/code -I/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/build/code/embedded_files -I/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/lib/discord/src/../include -I/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/lib/libRocket/Include -I/usr/x86_64-pc-linux-gnu/include/freetype2 -I/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/parsers -I/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/lib/antlr4-cpp-runtime/runtime/src -I/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/lib/mongoose -isystem /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/lib/opengl/gl/glad/include -isystem /usr/x86_64-pc-linux-gnu/include/AL -isystem /usr/x86_64-pc-linux-gnu/include/lua5.1 -isystem /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/lib/lz4 -isystem /usr/x86_64-pc-linux-gnu/include/SDL2 -isystem /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/lib -isystem /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/lib/utfcpp -isystem /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/lib/md5 -isystem /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/lib/libpcp/include -isystem /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/lib/vulkan-hpp -isystem /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/lib/mdns -isystem /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/lib/variant -march=native -O2 -pipe   -W -Wall -Wextra -Wno-maybe-uninitialized -funroll-loops -fsigned-char -Wno-unknown-pragmas -fdata-sections -ffunction-sections  -Wformat-security -Wreturn-type -Wno-deprecated -Wno-char-subscripts -Wno-stringop-truncation -Wno-stringop-overflow -O2 -Wno-unused-variable -Wno-unused-but-set-variable -Wno-array-bounds -Wno-empty-body -Wno-clobbered  -Wno-unused-parameter -std=gnu++11 -Winvalid-pch -include /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/build/code/CMakeFiles/code.dir/cmake_pch.hxx -MD -MT code/CMakeFiles/code.dir/cutscene/ffmpeg/VideoDecoder.cpp.o -MF CMakeFiles/code.dir/cutscene/ffmpeg/VideoDecoder.cpp.o.d -o CMakeFiles/code.dir/cutscene/ffmpeg/VideoDecoder.cpp.o -c /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/VideoDecoder.cpp
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/internal.cpp: In destructor 'cutscene::ffmpeg::DecoderStatus::~DecoderStatus()':
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/internal.cpp:15:17: error: 'avcodec_close' was not declared in this scope; did you mean 'avio_close'?
   15 |                 avcodec_close(videoCodecCtx);
      |                 ^~~~~~~~~~~~~
      |                 avio_close
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/FFMPEGDecoder.cpp: In function 'double {anonymous}::getFrameRate(AVStream*, AVCodecContext*)':
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/FFMPEGDecoder.cpp:59:44: error: invalid use of incomplete type 'struct AVCodecContext'
   59 |                 fps = 1.0 / av_q2d(codecCtx->time_base);
      |                                            ^~
In file included from /usr/x86_64-pc-linux-gnu/include/libavformat/avformat.h:313,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/libs/ffmpeg/FFmpegHeaders.h:10,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/libs/ffmpeg/FFmpegContext.h:8,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/FFMPEGDecoder.cpp:6:
/usr/x86_64-pc-linux-gnu/include/libavcodec/codec.h:195:8: note: forward declaration of 'struct AVCodecContext'
  195 | struct AVCodecContext;
      |        ^~~~~~~~~~~~~~
make[2]: *** [code/CMakeFiles/code.dir/build.make:1370: code/CMakeFiles/code.dir/cutscene/ffmpeg/AudioDecoder.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/FFMPEGDecoder.cpp: In function 'std::unique_ptr<cutscene::ffmpeg::DecoderStatus> cutscene::ffmpeg::{anonymous}::initializeStatus(std::unique_ptr<cutscene::ffmpeg::InputStream>&, std::unique_ptr<cutscene::ffmpeg::InputStream>&, const cutscene::PlaybackProperties&)':
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/FFMPEGDecoder.cpp:232:81: error: invalid conversion from 'AVCodec**' to 'const AVCodec**' [-fpermissive]
  232 |         auto videoStream = av_find_best_stream(ctx, AVMEDIA_TYPE_VIDEO, -1, -1, &status->videoCodec, 0);
      |                                                                                 ^~~~~~~~~~~~~~~~~~~
      |                                                                                 |
      |                                                                                 AVCodec**
In file included from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/libs/ffmpeg/FFmpegHeaders.h:10,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/libs/ffmpeg/FFmpegContext.h:8,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/FFMPEGDecoder.cpp:6:
/usr/x86_64-pc-linux-gnu/include/libavformat/avformat.h:2161:41: note:   initializing argument 5 of 'int av_find_best_stream(AVFormatContext*, AVMediaType, int, int, const AVCodec**, int)'
 2161 |                         const AVCodec **decoder_ret,
      |                         ~~~~~~~~~~~~~~~~^~~~~~~~~~~
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/FFMPEGDecoder.cpp:248:93: error: invalid conversion from 'AVCodec**' to 'const AVCodec**' [-fpermissive]
  248 |                 audioStream = av_find_best_stream(ctx, AVMEDIA_TYPE_AUDIO, -1, videoStream, &status->audioCodec, 0);
      |                                                                                             ^~~~~~~~~~~~~~~~~~~
      |                                                                                             |
      |                                                                                             AVCodec**
In file included from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/libs/ffmpeg/FFmpegHeaders.h:10,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/libs/ffmpeg/FFmpegContext.h:8,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/FFMPEGDecoder.cpp:6:
/usr/x86_64-pc-linux-gnu/include/libavformat/avformat.h:2161:41: note:   initializing argument 5 of 'int av_find_best_stream(AVFormatContext*, AVMediaType, int, int, const AVCodec**, int)'
 2161 |                         const AVCodec **decoder_ret,
      |                         ~~~~~~~~~~~~~~~~^~~~~~~~~~~
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/FFMPEGDecoder.cpp:324:33: error: 'avcodec_alloc_context3' was not declared in this scope; did you mean 'avio_alloc_context'?
  324 |         status->videoCodecCtx = avcodec_alloc_context3(status->videoCodec);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~
      |                                 avio_alloc_context
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/internal.cpp:17:17: error: 'avcodec_free_context' was not declared in this scope; did you mean 'avformat_free_context'?
   17 |                 avcodec_free_context(&videoCodecCtx);
      |                 ^~~~~~~~~~~~~~~~~~~~
      |                 avformat_free_context
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/FFMPEGDecoder.cpp:327:15: error: 'avcodec_parameters_to_context' was not declared in this scope; did you mean 'avcodec_parameters_copy'?
  327 |         err = avcodec_parameters_to_context(status->videoCodecCtx, status->videoStream->codecpar);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |               avcodec_parameters_copy
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/internal.cpp:27:17: error: 'avcodec_close' was not declared in this scope; did you mean 'avio_close'?
   27 |                 avcodec_close(audioCodecCtx);
      |                 ^~~~~~~~~~~~~
      |                 avio_close
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/FFMPEGDecoder.cpp:338:15: error: 'avcodec_open2' was not declared in this scope; did you mean 'avio_open2'?
  338 |         err = avcodec_open2(status->videoCodecCtx, status->videoCodec, nullptr);
      |               ^~~~~~~~~~~~~
      |               avio_open2
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/FFMPEGDecoder.cpp:382:61: error: invalid conversion from 'const AVCodec*' to 'AVCodec*' [-fpermissive]
  382 |                 status->subtitleCodec = avcodec_find_decoder(status->subtitleCodecPars.codec_id);
      |                                         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                             |
      |                                                             const AVCodec*
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp: In member function 'virtual void cutscene::ffmpeg::SubtitleDecoder::decodePacket(AVPacket*)':
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:24:20: error: aggregate 'AVSubtitle subtitle' has incomplete type and cannot be defined
   24 |         AVSubtitle subtitle;
      |                    ^~~~~~~~
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/internal.cpp:29:17: error: 'avcodec_free_context' was not declared in this scope; did you mean 'avformat_free_context'?
   29 |                 avcodec_free_context(&audioCodecCtx);
      |                 ^~~~~~~~~~~~~~~~~~~~
      |                 avformat_free_context
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:25:23: error: 'avcodec_decode_subtitle2' was not declared in this scope
   25 |         auto result = avcodec_decode_subtitle2(m_status->subtitleCodecCtx, &subtitle, &finishedFrame, packet);
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/internal.cpp:39:17: error: 'avcodec_close' was not declared in this scope; did you mean 'avio_close'?
   39 |                 avcodec_close(subtitleCodecCtx);
      |                 ^~~~~~~~~~~~~
      |                 avio_close
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/VideoDecoder.cpp: In member function 'virtual void cutscene::ffmpeg::VideoDecoder::decodePacket(AVPacket*)':
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/VideoDecoder.cpp:108:31: error: 'avcodec_send_packet' was not declared in this scope; did you mean 'avcodec_get_name'?
  108 |                 send_result = avcodec_send_packet(m_status->videoCodecCtx, packet);
      |                               ^~~~~~~~~~~~~~~~~~~
      |                               avcodec_get_name
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:30:17: error: 'avsubtitle_free' was not declared in this scope
   30 |                 avsubtitle_free(&subtitle);
      |                 ^~~~~~~~~~~~~~~
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp: In member function 'virtual void cutscene::ffmpeg::SubtitleDecoder::finishDecoding()':
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:40:20: error: aggregate 'AVSubtitle subtitle' has incomplete type and cannot be defined
   40 |         AVSubtitle subtitle;
      |                    ^~~~~~~~
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/internal.cpp:41:17: error: 'avcodec_free_context' was not declared in this scope; did you mean 'avformat_free_context'?
   41 |                 avcodec_free_context(&subtitleCodecCtx);
      |                 ^~~~~~~~~~~~~~~~~~~~
      |                 avformat_free_context
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/VideoDecoder.cpp:110:23: error: 'avcodec_receive_frame' was not declared in this scope; did you mean 'avcodec_profile_name'?
  110 |                 while(avcodec_receive_frame(m_status->videoCodecCtx, m_decodeFrame) == 0) {
      |                       ^~~~~~~~~~~~~~~~~~~~~
      |                       avcodec_profile_name
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:43:28: error: 'avcodec_decode_subtitle2' was not declared in this scope
   43 |                 auto err = avcodec_decode_subtitle2(m_status->subtitleCodecCtx, &subtitle, &finishedFrame, &nullPacket);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/VideoDecoder.cpp: In member function 'virtual void cutscene::ffmpeg::VideoDecoder::finishDecoding()':
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/VideoDecoder.cpp:129:9: error: 'avcodec_send_packet' was not declared in this scope; did you mean 'avcodec_get_name'?
  129 |         avcodec_send_packet(m_status->videoCodecCtx, nullptr);
      |         ^~~~~~~~~~~~~~~~~~~
      |         avcodec_get_name
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:51:17: error: 'avsubtitle_free' was not declared in this scope
   51 |                 avsubtitle_free(&subtitle);
      |                 ^~~~~~~~~~~~~~~
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp: In member function 'void cutscene::ffmpeg::SubtitleDecoder::pushSubtitleFrame(AVPacket*, AVSubtitle*)':
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:55:21: error: invalid use of incomplete type 'struct AVSubtitle'
   55 |         if (subtitle->format != 1) {
      |                     ^~
In file included from /usr/x86_64-pc-linux-gnu/include/libavformat/avformat.h:313,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/libs/ffmpeg/FFmpegHeaders.h:10,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/internal.h:5,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.h:3,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:4:
/usr/x86_64-pc-linux-gnu/include/libavcodec/codec.h:196:8: note: forward declaration of 'struct AVSubtitle'
  196 | struct AVSubtitle;
      |        ^~~~~~~~~~
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:60:21: error: invalid use of incomplete type 'struct AVSubtitle'
   60 |         if (subtitle->num_rects < 1) {
      |                     ^~
In file included from /usr/x86_64-pc-linux-gnu/include/libavformat/avformat.h:313,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/libs/ffmpeg/FFmpegHeaders.h:10,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/internal.h:5,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.h:3,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:4:
/usr/x86_64-pc-linux-gnu/include/libavcodec/codec.h:196:8: note: forward declaration of 'struct AVSubtitle'
  196 | struct AVSubtitle;
      |        ^~~~~~~~~~
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:64:31: error: invalid use of incomplete type 'struct AVSubtitle'
   64 |         int64_t pts = subtitle->pts;
      |                               ^~
In file included from /usr/x86_64-pc-linux-gnu/include/libavformat/avformat.h:313,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/libs/ffmpeg/FFmpegHeaders.h:10,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/internal.h:5,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.h:3,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:4:
/usr/x86_64-pc-linux-gnu/include/libavcodec/codec.h:196:8: note: forward declaration of 'struct AVSubtitle'
  196 | struct AVSubtitle;
      |        ^~~~~~~~~~
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:74:50: error: invalid use of incomplete type 'struct AVSubtitle'
   74 |         auto start_time = packet_time + (subtitle->start_display_time / 1000.0);
      |                                                  ^~
In file included from /usr/x86_64-pc-linux-gnu/include/libavformat/avformat.h:313,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/libs/ffmpeg/FFmpegHeaders.h:10,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/internal.h:5,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.h:3,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:4:
/usr/x86_64-pc-linux-gnu/include/libavcodec/codec.h:196:8: note: forward declaration of 'struct AVSubtitle'
  196 | struct AVSubtitle;
      |        ^~~~~~~~~~
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:75:48: error: invalid use of incomplete type 'struct AVSubtitle'
   75 |         auto end_time = packet_time + (subtitle->end_display_time / 1000.0);
      |                                                ^~
In file included from /usr/x86_64-pc-linux-gnu/include/libavformat/avformat.h:313,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/libs/ffmpeg/FFmpegHeaders.h:10,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/internal.h:5,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.h:3,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:4:
/usr/x86_64-pc-linux-gnu/include/libavcodec/codec.h:196:8: note: forward declaration of 'struct AVSubtitle'
  196 | struct AVSubtitle;
      |        ^~~~~~~~~~
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:76:21: error: invalid use of incomplete type 'struct AVSubtitle'
   76 |         if (subtitle->end_display_time == 0 && m_status->subtitleStream->time_base.num != 0) {
      |                     ^~
In file included from /usr/x86_64-pc-linux-gnu/include/libavformat/avformat.h:313,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/libs/ffmpeg/FFmpegHeaders.h:10,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/internal.h:5,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.h:3,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:4:
/usr/x86_64-pc-linux-gnu/include/libavcodec/codec.h:196:8: note: forward declaration of 'struct AVSubtitle'
  196 | struct AVSubtitle;
      |        ^~~~~~~~~~
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:82:38: error: invalid use of incomplete type 'struct AVSubtitle'
   82 |         auto subtitle_rect = subtitle->rects[0];
      |                                      ^~
In file included from /usr/x86_64-pc-linux-gnu/include/libavformat/avformat.h:313,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/libs/ffmpeg/FFmpegHeaders.h:10,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/internal.h:5,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.h:3,
                 from /var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:4:
/usr/x86_64-pc-linux-gnu/include/libavcodec/codec.h:196:8: note: forward declaration of 'struct AVSubtitle'
  196 | struct AVSubtitle;
      |        ^~~~~~~~~~
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/VideoDecoder.cpp:133:28: error: 'avcodec_receive_frame' was not declared in this scope; did you mean 'avcodec_profile_name'?
  133 |                 auto ret = avcodec_receive_frame(m_status->videoCodecCtx, m_decodeFrame);
      |                            ^~~~~~~~~~~~~~~~~~~~~
      |                            avcodec_profile_name
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:83:36: error: 'SUBTITLE_BITMAP' was not declared in this scope
   83 |         if (subtitle_rect->type == SUBTITLE_BITMAP) {
      |                                    ^~~~~~~~~~~~~~~
make[2]: *** [code/CMakeFiles/code.dir/build.make:1402: code/CMakeFiles/code.dir/cutscene/ffmpeg/internal.cpp.o] Error 1
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:87:43: error: 'SUBTITLE_TEXT' was not declared in this scope
   87 |         } else if (subtitle_rect->type == SUBTITLE_TEXT) {
      |                                           ^~~~~~~~~~~~~
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/VideoDecoder.cpp: In member function 'virtual void cutscene::ffmpeg::VideoDecoder::flushBuffers()':
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/VideoDecoder.cpp:162:9: error: 'avcodec_flush_buffers' was not declared in this scope
  162 |         avcodec_flush_buffers(m_status->videoCodecCtx);
      |         ^~~~~~~~~~~~~~~~~~~~~
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:90:43: error: 'SUBTITLE_ASS' was not declared in this scope
   90 |         } else if (subtitle_rect->type == SUBTITLE_ASS) {
      |                                           ^~~~~~~~~~~~
make[2]: *** [code/CMakeFiles/code.dir/build.make:1386: code/CMakeFiles/code.dir/cutscene/ffmpeg/FFMPEGDecoder.cpp.o] Error 1
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp: In member function 'virtual void cutscene::ffmpeg::SubtitleDecoder::flushBuffers()':
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/SubtitleDecoder.cpp:133:9: error: 'avcodec_flush_buffers' was not declared in this scope
  133 |         avcodec_flush_buffers(m_status->subtitleCodecCtx);
      |         ^~~~~~~~~~~~~~~~~~~~~
make[2]: *** [code/CMakeFiles/code.dir/build.make:1434: code/CMakeFiles/code.dir/cutscene/ffmpeg/VideoDecoder.cpp.o] Error 1
make[2]: *** [code/CMakeFiles/code.dir/build.make:1418: code/CMakeFiles/code.dir/cutscene/ffmpeg/SubtitleDecoder.cpp.o] Error 1
make[2]: Leaving directory '/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/build'
make[1]: Leaving directory '/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/build'
make[1]: *** [CMakeFiles/Makefile2:926: code/CMakeFiles/code.dir/all] Error 2
make: *** [Makefile:159: all] Error 2
```
Complete build log: [fs2_open-21.4.1-build.log](https://github.com/scp-fs2open/fs2open.github.com/files/7875564/fs2_open-21.4.1-build.log)

### PR DESCRIPTION
**Pull request by notimaginative**
Fixes #3926

### CODE REVIEW

**Comment by notimaginative** [comment]
This is untested with ffmpeg 5.0, but it is based on the 5.0 api example code. It has been tested with ffmpeg v4.4 however. From the docs it should work at least as far back as ffmpeg v2.

**Comment by tgurr** [comment]
@notimaginative Thanks I've tested your patch but there's still an occurance unhandled later in the code line 382 or with your patch applied line 395:

`status->subtitleCodec = avcodec_find_decoder(status->subtitleCodecPars.codec_id);` causing

```
/var/tmp/paludis/build/games-simulation-fs2_open-21.4.1/work/fs2_open-21.4.1/code/cutscene/ffmpeg/FFMPEGDecoder.cpp:395:61: error: invalid conversion from 'const AVCodec*' to 'AVCodec*' [-fpermissive]
  395 |                 status->subtitleCodec = avcodec_find_decoder(status->subtitleCodecPars.codec_id);
      |                                         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                             |
      |                                                             const AVCodec*
```

**Comment by notimaginative** [comment]
@tgurr Just pushed some more changes which should fix that. Hopefully that should get you going now.

**Comment by tgurr** [comment]
> @tgurr Just pushed some more changes which should fix that. Hopefully that should get you going now.

Indeed, thank you very much! Compiles fine now and at least the into/introduction cutscene is playing fine as well (I don't have any other cutscenes to test with unlocked).

**Review by Goober5000 — APPROVED** [review]

**Pull request merged**
