### PR TITLE
add additional parameters to warp-effect

### PR DESCRIPTION
**Pull request by Goober5000**
The warp-effect SEXP can now specify other animations from fireball.tbl that are not necessarily the standard or Knossos animations.  Additionally, the SEXP can now specify the duration for the opening and closing of the warp effect.

### CODE REVIEW

**Comment by Goober5000** [comment]
There is one problem that I haven't been able to figure out.  The warp animation has a bright circle of light generated at the very center.  I thought that the color of this could be changed using the $Light_color option in fireball.tbl, but it doesn't seem to work.  By tracing through a debug build, I can verify that the proper colors are being accessed at object.cpp:1308, but the bright light is nevertheless a different color.

**Comment by Goober5000** [comment]
Okay, that's warpglow01.  Will add some things to handle that.

**Comment by Goober5000** [comment]
Okay, just evaluate this PR as-is.  I have a different PR in progress to add a feature for custom warp glows.

**Comment by asarium** [comment]
@Goober5000 Just to confirm, is the current status of this PR ready for merging?

**Comment by Goober5000** [comment]
Yes, it is.  I'll go ahead and merge it since it's been approved.

**Pull request merged**
