### PR TITLE
Hud scale limit

### PR DESCRIPTION
**Pull request by Yarn366**
This implements my proposal in [this post](http://www.hard-light.net/forums/index.php?topic=89233.msg1777867#msg1777867), which aims to solve the problem of HUD gauges getting too tiny at high resolutions while still allowing gauges to shrink at lower resolutions.

### CODE REVIEW

**Comment by asarium** [comment]
I dislike introducing another parameter to the already pretty long function signatures just for passing it do the common loading function. I'll have to check the code to see if there is a better solution, maybe we could use a struct to hold that common data?

**Comment by Yarn366** [comment]
Using a struct sounds like a good idea to me. Should I go ahead and code it in?

**Comment by MageKing17** [comment]
May as well; if it doesn't work out, the commit can always be reverted or shoved into its own branch.

**Comment by Yarn366** [comment]
All right, I think it's finally ready--the code now passes around struct pointers instead of a load of values. The code looks cleaner as a result, and it should be easier to add common settings in the future.

**Comment by MageKing17** [comment]
Is there a reason for using this `get_default_gauge_settings()` function instead of some sort of `default_gauge_settings` constant?

**Comment by Yarn366** [comment]
Yeah, actually: because I somehow forgot that C++ defines work differently from Java constants. I'll change it.

**Comment by chief1983** [comment]
@MageKing17 @asarium as he's addressed those issues, was this good to merge now or were we waiting for more eyes to sign off on it?

**Comment by asarium** [comment]
I missed the update. The diff is too big to be shown here but I'll take a look at the changes later.

**Comment by asarium** [comment]
I don't like that a `#define` is used for setting the default values in the settings struct. Using the default constructor for that seems like the better way to solve that.

`force_scaling_above_res` is initialized with a default value of `-1, -1` but later it's set to `INT_MAX` if a negative value is encountered. Is that intentional? If not then the default value could just be initialized with `INT_MAX`.

Apart from those issues the changes look good to me.

**Comment by Yarn366** [comment]
I'm not sure what you mean by "default constructor." Do you mean not explicitly setting any of the values upon creation (which would mean everything in the struct is set to 0/false/NULL)? If so, then I don't think that's the best solution. If you look near the end of the define, two of the booleans default to `true`. Using the default constructor would mean these values would need to be explicitly set everywhere the struct is created. This may seem OK, but if a coder adds an instance of the struct in the future and doesn't set those defaults, then the game can behave unexpectedly. There are also some values at the beginning that don't use 0/false/NULL, and the same issues apply to those. That's why I used a define. (An even better solution is to set the default values in the struct itself, but since that's [not supported in Visual Studio 2010](https://msdn.microsoft.com/en-us/library/hh567368.aspx#corelanguagetable) [look for "Non-static data member initializers"], I didn't do that.)


I'll take a look at `force_scaling_above_res` and see whether there really is any reason to initialize it to -1 instead of `INT_MAX`. (I'm guessing there isn't.)

**Comment by asarium** [comment]
The default constructor is the constructor without arguments. It's called when you create an instance of a variable without specifying parameters.

Using that you can properly initialize values using the following syntax:
```C++
class foo {
    int bar;
    foo() : bar(42) {}
};
```

**Comment by Yarn366** [comment]
I knew what default constructors are, actually; I just didn't know that structs can have constructors until shortly after I read your explanation.

Anyway, I added the constructor. If there's a better way to initialize the arrays (other than using uniform initialization, which Visual Studio 2010 doesn't support), please let me know.

If the change looks good, then I'll check out `force_scaling_above_res` next.

**Comment by asarium** [comment]
Passing all the values for the struct in the constructor is bad for readability. The previous version where you initialized individual members was easier to read.
You shouldn't pass any parameters to the constructor and instead use the current default values you currently have to initialize the members.

You should also use `nullptr` instead of `NULL` to improve compile time safety.

**Comment by Yarn366** [comment]
How does it look now?

**Comment by asarium** [comment]
That's better. I think that covers everything.

LGTM.

**Pull request merged**
