### PR TITLE
Possible Solution for mantis 1826

### PR DESCRIPTION
**Pull request by FSCyborg**
Adds new functionality to Netgame_Info Class to be able to hold campaign description.  Also adds is_multi_camp to it which is a check for whether a netgame is a campaign game, based on the mission selection screen.  Tested and seems to work.

Please review and provide comments or pull if satisfactory.  Thank you.

### CODE REVIEW

**Comment by chief1983** [comment]
Your merge appears to have resulted in a merge conflict remaining in multiui.cpp, need to clean that up before this will compile.

**Comment by FSCyborg** [comment]
Do I need to fix this deprecation error?

**Comment by MageKing17** [comment]
What deprecation error is that?

**Comment by FSCyborg** [comment]
https://ci.appveyor.com/project/z64555/fs2open-github-com/build/3.7.3.11/job/bvbcly04w5w8h9l6/messages

**Comment by chief1983** [comment]
Looking forward to it, the current code even somehow managed to pass all the AppVeyor builds.

**Comment by FSCyborg** [comment]
I know this is minor, but any suggestions or comments?  After implementing the "more logical fix", I found that it worked as intended in all my test cases, except for when switching back and forth between files that had longer than the max description length.

**Comment by MageKing17** [comment]
If it doesn't work as intended, what does it do instead?

**Comment by FSCyborg** [comment]
It's hard to tell.  But I think it sometimes adds the second description to
the first description.  It will switch back to correct behavior when it
comes to a mission or campaign whose description is within the maximum.

But descriptions rarely get longer than 200 characters, much less hit 503.
   I had to more than double the campaign descriptions to get them that
long.  Is it something to worry about?

**Comment by MageKing17** [comment]
If it's known to do something wrong with overly-long descriptions, that should be fixed *before* this code hits master.

**Comment by FSCyborg** [comment]
Ok, I'll try to figure out what's going on.

**Comment by FSCyborg** [comment]
Worked off an educated guess, and it fixed the bug.  As far as I can tell there are no remaining issues.

**Comment by chief1983** [comment]
Anyone else object then?  Did the code pass scrutiny already?

**Comment by FSCyborg** [comment]
I'm making up a trio of patches which should pass a cleaner commit.

**Pull request closed without merging**
