### PR TITLE
Fix build on big-endian architectures

### PR DESCRIPTION
**Pull request by pkubaj**
swap_bsp_data() and swap_sldc_data() use those.

### CODE REVIEW

**Comment by pkubaj** [comment]
Is `-Wunused-parameter` really required?

It seems to break one of checks.

**Comment by chief1983** [comment]
I am wondering how related this is to the SLDC stuff that was investigated for ARM platform?  https://www.hard-light.net/forums/index.php?topic=96055.msg1890756#msg1890756

**Comment by chief1983** [comment]
Also seems like the checks won't pass as-is since it is unused on other platforms.  I think there is a comment syntax to tell the compiler to ignored the unused params on those lines, that or can the params themselves be behind an ifdef as well?

**Comment by CasparKielwein** [comment]
> Also seems like the checks won't pass as-is since it is unused on other platforms. I think there is a comment syntax to tell the compiler to ignored the unused params on those lines, that or can the params themselves be behind an ifdef as well?

Ont / the idiomatic way to mark an unused paramter is to "cast" it to void.
`(void)pm;`
`(void)model_ptr;`
and
`(void)buffer;`

Should do the trick.

**Comment by CasparKielwein** [comment]
looks good to me

**Pull request merged**
