### PR TITLE
[fix/osx_xcode] Xcode can finally compile SDL Everywhere

### PR DESCRIPTION
**Pull request by chief1983**
This is the last of the necessary changes to get Xcode compiling again in the Antipodes branch.  Also has all the commits to merge master into Antipodes rebased before my changes.

### CODE REVIEW

**Comment by Echelon9** [comment]
It is a bit hard to review with all the unrelated changes packaged in here, but the SDL2-related changes  look okay. Note I haven't actually done a test compile yet.

**Comment by chief1983** [comment]
I would just review the individual commits at the bottom instead of the changes as a whole.  Only things I touched outside of merging master was in projects/Xcode4.

**Comment by chief1983** [comment]
I suppose I _could_ split it into a merge master and then just the changes PR...but it really shouldn't be too hard to tell what the last commits in the PR do individually is it?

**Comment by Echelon9** [comment]
Thanks, have been able to review the patches on screen. I'd like to test on a real OS X system this weekend. 

Given other reports of our existing SDL1.2 framework not playing nice with Mac (http://www.hard-light.net/forums/index.php?topic=89642.0), I believe the move to SDL2 is rather urgent now. What more is required to get Antipodes merged to master?

**Comment by chief1983** [comment]
Other means of viewing just the changes I made would have been to git diff bfaf474 876af80, or git diff 876af80~ 876af80, git diff 876af80~2 876af80~, git diff 876af80~3 876af80~2, etc until you reach the end of my commits.  Also, yeah a test would be good.

**Comment by asarium** [comment]
@Echelon9 As far as I'm aware everything should be ready for merging Antipodes into master but we should expect some issues when the first nightlies get released as Antipodes hasn't been tested by a lot of users.

**Comment by chief1983** [comment]
Antipodes won't compile on FreeBSD currently.  Something about assigning nullptr_t to SDLtimerID types I think.  Still checking linux.

**Comment by asarium** [comment]
Apparently `NULL` is defined to `nullptr` on FreeBSD and the audio stream code assigns `NULL` to an integer value which is not valid if `nullptr` is used.

**Pull request merged**
