### PR TITLE
fix typo in AI flag conversion

### PR DESCRIPTION
**Pull request by Goober5000**
I noticed that there was one line in #922 where two flags were checked using the comma operator.  This is incorrect as the comma operator evaluates both expressions but only returns the value of the rightmost expression, resulting in only one flag being checked.  This PR fixes the Assert by copying the same condition as another Assert elsewhere in the file.

This PR is actually a no-op because the problematic code is commented out, but one never knows when it might be used again.

### CODE REVIEW

**Comment by Goober5000** [comment]
Addendum: Given that in all places the Asserts are found, the two indexes should both be valid, I changed the `||` to `&&`.

**Comment by asarium** [comment]
FYI, the comma operator for bitset flags use a bit of template magic to change that operator to a logical `|` which is noted in [the documentation](https://github.com/scp-fs2open/fs2open.github.com/wiki/Bitset-Flags). Since you changed the places where `||` or `,` was used to `&&` it doesn't make a difference but I wanted to let you know that the `,` operator actually makes sense with flagsets.

**Comment by Goober5000** [comment]
> FYI, the comma operator for bitset flags use a bit of template magic to change that operator to a logical `|` which is noted in [the documentation](https://github.com/scp-fs2open/fs2open.github.com/wiki/Bitset-Flags).

Hmm.  That's interesting, but I'm not sure I like that.  The comma operator has a well-defined function, and changing it like that seems like a recipe for misunderstanding (like what happened here).

**Comment by asarium** [comment]
It was discussed when I added the operator and we decided against using the `|` operator for some reason I can't remember. Anyway, that has nothing to do with these changes and I approved them already so I'm just going to merge these.

**Pull request merged**
