### PR TITLE
synchronize simulation timestamps across the entire frame

### PR DESCRIPTION
**Pull request by Goober5000**
Prior to the timer upgrade, all simulation timestamps shared identical timer and timestamp values for the duration of the frame, since they were only updated within the `game_set_frametime` function.  Since the timer upgrade depends on the system clock, timestamps evaluated near the end of the frame will be very slightly later than timestamps evaluated near the beginning of the frame.  It is desirable to keep them all in sync.

This PR tweaks the timestamp system to take a snapshot at the beginning of the frame, then use that snapshot for the entire duration of the frame.  This only affects simulation timestamps; real-time timestamps still use the live timer.

This is a redo of PR #5266, with some small additional tweaks.

Update: this now fixes the bug discovered in #5287.

### CODE REVIEW

**Comment by Goober5000** [comment]
Theoretically this should be susceptible to the same bug that #5287 discussed, but I have not been able to reproduce it.  Neither time compression nor `runAsync` show any problems.

**Comment by JohnAFernandez** [comment]
I highly recommend sending this to other testers who were having issues with the last version of this patch, because I honestly do not see a difference between the last attempt and this one.

**Comment by wookieejedi** [comment]
Fortunately, was able to set Goober up with a reproducible bug case, though in any case additional testing with others such as Durandal (who was testing before) will be needed too as the process progresses.

**Comment by Goober5000** [comment]
> I honestly do not see a difference between the last attempt and this one.

The first commit is exactly the same as before, and this PR adds two more polishing.  This is a starting point; I am using it as a basis for testing.  I'll put it in draft to be clear.

**Comment by Goober5000** [comment]
Ok, I found the cause of the bug and fixed it.  When time compression changes, the elapsed time must be consistent, even when the rate of time changes.  To keep this simple, the y-intercept of the current timeline is set to 0, and the new timeline starts from that point.  The introduction of timestamp snapshots caused inaccuracies because the calculations would be based on not-quite-instant values.  Normally it would be hard to notice this, but FotG had some scripts that made some very dramatic time compression changes in very quick succession.  We have to thank FotG here because, as hard as this was to track down, it would have been much worse without their script.

The solution is to always make sure the timer re-takes the snapshot whenever time compression changes.  This itself would make the snapshot inconsistent for the frame where the time compression change takes place, except for the fortuitous discovery that most time compression changes *also* take place at the start of the frame.  So this works out very nicely.  It was a relatively simple matter to change "most" to "all", so all methods of changing time compression now occur at precisely the same spot.

**Comment by wookieejedi** [comment]
Tested and works for me. The code update makes sense too, as it follows the similar logic to updating the booleans for `timestamp_get_raw` while also adding the dually important fix within `change_time_compression`. I'll send to Durandal for him to test and update with a review/approval if the build works for him, too.

**Review by wookieejedi — APPROVED** [review]
Additional tests from Durandal and myself and everything is working as expected. Overall code looks good too, as it follows the similar logic to updating the booleans for `timestamp_get_raw` while also adding the dually important fix within `change_time_compression`

**Pull request merged**
