### PR TITLE
Remove unused cmdline arguments

### PR DESCRIPTION
**Pull request by The-E**
While discussing the various lighting-related commandline arguments (see #1587), it became clear that two of them (-spec_exp and -ogl_spec) don't actually do anything at the moment. Removing them seems like a good idea.

### CODE REVIEW

**Comment by chief1983** [comment]
I guess I am curious about that because if they aren't functional but never intentionally disabled, this would seem to highlight an unintentional effect of one of our graphics upgrades over the last few years.  Perhaps they were intended to remain functional but their implementation in the new pipeline was omitted by mistake?

**Comment by asarium** [comment]
Only @SamuelCho can answer that question conclusively but my guess is that the parameters either became unnecessary of maybe even impossible to implement when we switched to the PBR pipeline.

**Comment by The-E** [comment]
The thing is, and this is something we should also discuss in #1587, what sort of customizability we want the lighting engine to have and how to expose it. I think that, rather than repurposing these old parameters, we should add new ones for whatever functionality we decide to implement. For now, cleaning up the code should take priority.

**Comment by SamuelCho** [comment]
Yeah I've had trouble figuring out how those parameters would translate to the new specular model. Specular power is essentially gloss/inverse roughness. I thought about scaling ogl_spec against 255.0 and using that 0.0-1.0 value for default gloss. But I don't know what spec_exp would correspond to. I could do a bit of code rewinding to figure that out.

**Comment by MageKing17** [comment]
Should we maybe deprecate them to be on the safe side?

**Pull request closed without merging**
