### PR TITLE
Expose Collision Rotation Factor to Players

### PR DESCRIPTION
**Pull request by wookieejedi**
Previously, there were hardcoded checks in place to make players have 0 rotational effects when colliding with another ship. This PR adds a new value, `+Player Multiplier for Rotation Factor:` that allows modders to have players experience rotational effects from collisions. Also performed some cleanup of the light and heavy collisional rotational calculations by removing older if-blocks following useful recommendation from @Baezon.

Tested and works as expected.

### CODE REVIEW

**Review by Baezon — COMMENTED** [review]
Hmm, I was thinking of a global value, rather than per ship. Does your use case have it be different on different ships?

**Comment by wookieejedi** [comment]
Ah yeah a global value is a better idea, will also help keep the current physics strut leaner.

**Comment by wookieejedi** [comment]
Updated to global value in AI profiles as requested, thanks!

**Review by Baezon — APPROVED** [review]

**Review by Goober5000 — APPROVED** [review]
👍

**Pull request merged**
