### PR TITLE
Fix linking error in unit tests

### PR DESCRIPTION
**Pull request by asarium**

### CODE REVIEW

**Comment by MageKing17** [comment]
When is `main` already defined?

**Comment by asarium** [comment]
It's from SDL which redefines `main` so that SDL can handle that to hide platform specific entry points.

**Comment by MageKing17** [comment]
How do unit tests ever work without this fix, then?

**Comment by asarium** [comment]
They work on Linux since SDL doesn't redefine `main` there. As far as I can tell the test were broken on Windows by some change in the past and it wasn't caught because, apparently, no one runs the test on Windows...

**Comment by chief1983** [comment]
Makes sense to me, seems like a good idea to get these fixed.

**Pull request merged**
