### PR TITLE
fix memory leak when reallocating ship subsystems

### PR DESCRIPTION
**Pull request by notimaginative**

### CODE REVIEW

**Review by JohnAFernandez — APPROVED** [review]
LGTM

**Review by Goober5000 — APPROVED** [review]
LGTM as well

**Comment by JohnAFernandez** [comment]
I'm willing to bet this memory issue was a possible cause for the subsystems not appearing in that ST:R mission.

**Comment by Goober5000** [comment]
That's an interesting theory, and quite plausible.

I'll tag #3147 so that the issue is linked.

**Pull request merged**
