### PR TITLE
Regression: Save Mouse control binds

### LINKED ISSUE #3322: User-bound mouse buttons are cleared or ignored
In recent nightlies, I effectively cannot bind any mouse button to seemingly any control. Default bindings for joy-0 work perfectly for the corresponding mouse buttons.

When I bind mouse buttons to anything, then accept,, and return to the controls screen from the first options screen where difficulty can be set, all mouse buttons stay bound.
If I instead bind mouse buttons and exit to the mainhall, then return to the controls screen, mouse buttons are no longer bound. The right column shows "None" bound even if I had replaced an existing joystick binding. 
If I bind mouse buttons mid-mission, the mouse buttons still don't do anything, but returning to the controls screen still shows that they are bound. The default joy-0 button bindings work for the mouse, but I don't know how to bind them to arbitrary keys.

### PR DESCRIPTION
**Pull request by BMagnu**
Should fix #3322 until controls4/5 rolls around.
Still, @z64555 should have a look at this as well.

### CODE REVIEW

**Review by MageKing17 — CHANGES_REQUESTED** [review]
I have no idea if this is the "correct" temporary solution, but I *do* know that it's definitely incomplete if it only applies to CSG files and ignores PLR files.

**Comment by z64555** [comment]
This fix shouldn't have any affect, Controls3 still has the mouse doubled up with the joystick, Controls5 is when they're split.

@BMagnu what are you trying to fix?

**Comment by BMagnu** [comment]
> This fix shouldn't have any affect, Controls3 still has the mouse doubled up with the joystick, Controls5 is when they're split.
> 
> @BMagnu what are you trying to fix?

So, what happens here is that if a control gets bound to the mouse, it obviously has CID_MOUSE (-1) as its CID. When it get's saved to the CSG file, it gets the bindings for CID_KEYBOARD (-2) and CID_JOY0 (0), which means mouse (button) bindings just get thrown away and will not be saved.

With this change, it will save the bindings to CID_MOUSE as well, and then apply them again on load, if they are not -1 (which they will be if the control has no mouse button bound).

At least in my tests, this actually fixes the behaviour of #3322 as with this change, it is possible to assign mouse buttons again, which it wasn't before.

**Comment by BMagnu** [comment]
> I have no idea if this is the "correct" temporary solution, but I _do_ know that it's definitely incomplete if it only applies to CSG files and ignores PLR files.

Good catch. Missed this since I only followed the code path of the controls code, which only seemed to read / save csg's and not plr's.

**Comment by z64555** [comment]
That may fix behavior in the controls config menu (being able to bind and retain mouse bindings), but what about in-game?

**Comment by BMagnu** [comment]
> That may fix behavior in the controls config menu (being able to bind and retain mouse bindings), but what about in-mission, does the control activate with the mouse bindings?

Indeed, that also doesn't work.
Seems like a bigger issue then.
Shall I leave you to it @z64555, or should I try to dig through the code?

**Comment by BMagnu** [comment]
Though, presumably a quick fix would be to add some code to every place where .get_btn(CID_JOY0) is, to add a check similar to the one for writing the CSG here, that checks if the mouse binding is not -1, use that instead of the CID_JOY0 binding

**Comment by z64555** [comment]
Yeah let me whip something up, I'll have it posted tomorrow.

Since the mouse is supposed to still be doubled up with the joystick, its completely moot to try to save the mouse binding or even be able to bind the mouse.  The fix will remove the instances of CID_MOUSE and replace them with CID_JOY0, and will be tested to ensure operation in-mission.

As an aside, Controls3 got as it is from me trying to piecemeal the overhaul project without prior knowledge of what practices and methods to use... so I feel responsible for breakages like this.

**Pull request closed without merging**
