### PR TITLE
Cleanup of controls_config and IO files

### PR DESCRIPTION
**Pull request by z64555**
Part of z64's Controls Code Overhaul (TM), this organizes, doxy's, and generally cleans up input related files to a more manageable state.

Also patches a minor bug with the mouse scroll wheel.

### CODE REVIEW

**Comment by chief1983** [comment]
`io/key.cpp:491:12: error: ‘int key_inkey_time(uint*)’ defined but not used [-Werror=unused-function]
io/key.cpp:662:12: error: ‘int key_numlock_is_on()’ defined but not used [-Werror=unused-function]
io/key.cpp:720:13: error: ‘void key_turn_off_numlock()’ defined but not used [-Werror=unused-function]`

Those are the three that failed GCC on Linux debug.  Also noticed the other fix for control_config_handle_conflict.  Instead of commenting out functions, would using the __UNUSED macro work here?  That way the unused code could still be left in place if it may serve future purpose, and still be compiled.  See accurate_square_root or rotate_z in math/fvi and math/vecmat, respectively.

**Comment by asarium** [comment]
`__UNUSED` should only be used if the relevant function absolutely needs to be compiled for some reason which is almost never the case.
If the code should remain in the source code the the whole function can be put in a block comment or if the code isn't needed anymore then the whole function should be removed.

Also, I am not certain if `__UNUSED` even works with functions. The [GCC documentation](https://gcc.gnu.org/onlinedocs/gcc-3.2/gcc/Function-Attributes.html) says that it is not supported for C++.

**Comment by chief1983** [comment]
```
code/globalincs/toolchain/clang.h:#define __UNUSED __attribute__((__unused__))
code/globalincs/toolchain/gcc.h:#define __UNUSED __attribute__((__unused__))
code/globalincs/toolchain/mingw.h:#define __UNUSED __attribute__((__unused__))
```

As I pointed out, we've already used it for two functions we intended to keep around for future use.  This allows the functions to still be in code intelligence for instance, instead of having to go uncomment them if you need them at a later date.  I agree, if these functions don't really make sense to keep around now, we should definitely delete them, but if they are part of a library of functions that just isn't happening to be completely used right now, commenting them out or deleting them might not be desired and __UNUSED allows us to mark them as such without having to globally turn off unused function warnings.  I'm mostly not a fan of block commenting functions though, as it would probably make them harder to find, and if you do want to use it, it could have somehow ended up in a state where it won't compile anymore, and the person wanting to use it would have to investigate why, etc.

**Comment by asarium** [comment]
The unused function warning is only generated for `static` functions which indicates that it's a function intended for internal use within a compilation unit. I agree that removing functions which are part of a larger collection should not be done but I can't determine if that's the case here.

**Comment by z64555** [comment]
**key_inkey_time()**: Volition's comment states that it is frankly a bogus number, but it might be used in the future whenever charging weapons or wire-guided missiles get implemented.

**key_numlock_is_on(), key_turn_numlock_off(), key_turn_numlock_on()**: These really should be used in the main loop to force the numlock to one state or the other. In the future, they *might* offer a toggleable set of keys, or we couuld force numlock off and repurpose the numlock key like we do with caps lock and scroll lock keys.

**Critical_key_set[]** sounds like something for multiplayer, might want to check with @jg18 and @Karajorma on this to see if it has any applications.

**Comment by z64555** [comment]
Current SDL versions do not have a method to set the Keyboard's lock states (Caps, Num, and Scroll), so **key_turn_numlock_off()** and **key_turn_numlock_on()** will be dead code until then. key_numlock_is_on() and any similar lock checking functions are potentially useable.

So, I suggest:
1. Delete **key_turn_numlock_off()** and **key_turn_numlock_on()**. Once SDL implements a method to set the keyboard state, then somebody can make a feature at that time.
2. Move **key_numlock_is_on()**'s declaration to key.h and remove the **static** keyword, thereby making it public. This can be used later on in FRED or perhaps the debug console.
3. Delete **key_inkey_time()**. I haven't found a use for it, the OS takes care of character repeat times, and we can determine how long a control has been active by other means.

**Comment by z64555** [comment]
Closing PR since antipodes has been merged with master.

**Pull request closed without merging**
