### PR TITLE
Team color glows

### PR DESCRIPTION
**Pull request by SamuelCho**
A refactor and port of glowing team color textures that were featured in JAD. I'd like to know if Axem can confirm these work before anyone attempts to merge.

### CODE REVIEW

**Comment by AxemP** [comment]
As the intended recipient I can indeed confirm that this PR enables the feature that I had been looking for.

For anyone who isn't in the know, this does a team color effect only on the glow map with the blue and alpha channel of a -misc map. Red and green still are used for the normal diffuse team color. JAD uses this for changing the color of ships for pretty and awesome.

**Comment by niffiwan** [comment]
Axem approved (tm)

**Comment by Goober5000** [comment]
Why is blue treated differently than the other two channels?

**Comment by MageKing17** [comment]
> Why is blue treated differently than the other two channels?

Because that's the whole point?

> For anyone who isn't in the know, this does a team color effect only on the glow map with the blue and alpha channel of a -misc map. Red and green still are used for the normal diffuse team color. JAD uses this for changing the color of ships for pretty and awesome.

**Comment by Goober5000** [comment]
Why are you just re-quoting something that was already posted?  Come on, I read Axem's comment. :rolleyes:

If a "normal diffuse team color" is limited to red and green, what happens if you want a team color that includes blue?  Hence my question.

**Comment by DahBlount** [comment]
In Colors.tbl, the colors to be used by each channel are defined with $Team Stripe Color: and $Team Base Color:. Perhaps it's also time to add additional arguments for glow colors as well?

**Comment by Goober5000** [comment]
See also this link, which explains how Team Colors are applied to the texture (at least, prior to this PR):
http://hard-light.net/wiki/index.php/Texturing#TextureName-misc-xxx

**Pull request merged**
