### PR TITLE
Update Turret_alt_math for moving subsystems

### PR DESCRIPTION
**Pull request by Baezon**
And renames it to what it *actually* means: a restricted fov, with limited elevation or base fov. Uses `model_instance_find_world_dir` for the original turret model's frame of reference vectors to produce a properly rotated turret matrix which the limited fov's can then be calculated from.

Additionally, most things that need the turret's normal or any direction based on the turret but *not* based on the turret's current 'angles', should not get `model_instance_find_world_dir` using the turret's subobject, but instead its parent. An optional parameter was added to `model_instance_find_world_dir` for this purpose so callers don't have to faff about with the polymodel.

### CODE REVIEW

**Review by Goober5000 — COMMENTED** [review]
My brain is too fried to review this properly right now, but I have one question.  Instead of adding a `parent` parameter to that function, why not make sure every invocation that needs the parent actually calls it with the parent submodel?

**Comment by Baezon** [comment]
Most callers don't have the `pm` handy (which is what you need to find the parent) and so let the overload of `model_instance_find_world_dir` do the lookup itself with the `model_instance_num` which cuts down on those repetitive lookups from all the callers. Its definitely kind of awkward, so if be happy to handle this however you'd think is best.

**Comment by Goober5000** [comment]
I guess that is fine.  But rename the parameter to something more explicit like `use_submodel_parent`.

**Review by Goober5000 — COMMENTED** [review]
Ok there is one difference here which might be a problem... or it might not.

Originally, `turret_matrix` was simply a representation of `turret_norm` as a matrix.  This matrix was fixed to the reference frame of the main model.  Upward-pointing turrets were one handedness and downward-pointing turrets were another handedness.

This is not the same concept as the turret frame-of-reference, which is the fvec/uvec defined in the POF.  In this sense, the `turret_norm` is always pointing "directly up" from its perspective, but its perspective orientation is defined by the fvec/uvec.

In this PR, you've taken a calculation based on the original sense of the turret matrix and rewritten it to use the fvec/uvec method.  This is fine -- and it's what this section of code needed -- but I want to make sure you understand the nuances of the different methods.

**Comment by Baezon** [comment]
Iirc `world_to_turret_matrix` was *not* equivalent to `turret_matrix` because, as you mentioned it was just the normal turned into a matrix. The restricted fov case really needs that separate fvec and uvec as defined in the pof in order for its restrictions to make sense, as they are from that point of view.

It should be noted that, at least for restricted Fov turrets, the turret normal *must* be the same as its uvec, or it violates several implicit assertions. We've touched on this briefly before in DMs , but its clearer to me now how this should work. If they aren't restricted, its less clear to me and probably not as harmful but I'm still not really sure how its supposed to work.

**Comment by wookieejedi** [comment]
Tested with restricted FOV turrets from FotG and it fixes things and works as expected.

**Review by Goober5000 — APPROVED** [review]
Looks good.  This might have something to do with #3299 as well.  We'll see.

**Pull request merged**
