### PR TITLE
Add option for writing pilot files in JSON format

### PR DESCRIPTION
**Pull request by asarium**
This is a new implementation of the JSON dumping which was already
proposed in #22 but this version tries to allow implementing both
reading and writing JSON files without having to change the existing
code too much. This is done by using an abstract class to hide the
differences between writing the JSON and binary files.

This is currently only capable of writing the files but not reading them
so if the option is enabled all changes to the pilot file are lost. I
will implement reading after this PR has been merged since I would like
to reduce the amount of changes that need to be reviewed.

### CODE REVIEW

**Comment by MageKing17** [comment]
> I will implement reading after this PR has been merged since I would like to reduce the amount of changes that need to be reviewed.

This sounds like a terrible idea.

**Comment by chief1983** [comment]
I didn't think reading was ever part of the plan, thought it was just going to be a sanity check for pilot data

**Comment by asarium** [comment]
> This sounds like a terrible idea.

If you are going to make such a statement then you should at least explain why it would be a terrible idea.

**Comment by MageKing17** [comment]
> If you are going to make such a statement then you should at least explain why it would be a terrible idea.

You are encouraging us to merge a PR that would intentionally leave the master branch in a state where it's not actually usable, in the hopes that the code to make it usable will then be *written in the first place*. I'm surprised I have to point out why this is inherently not a good idea.

Like, if you want to split it into multiple commits or even multiple PRs to make it easier to review individual changes, that's one thing, but not even *implementing* reading JSON-based save files until after this PR is merged? That is a **terrible idea**.

**Comment by asarium** [comment]
You do realize that the JSON writing is only enabled when setting a command line option, right?

**Comment by chief1983** [comment]
And even if it always happened, it doesn't break anything.  The files just get written to disk (at least that's how I thought it worked, it isn't replacing the binary writing yet right?)

**Comment by chief1983** [comment]
And even if it always happened, it doesn't break anything.  The files just get written to disk (at least that's how I thought it worked, it isn't replacing the binary writing yet right?)

**Comment by asarium** [comment]
@chief1983 If the option is enabled then no binary file will be written.

**Comment by MageKing17** [comment]
> You do realize that the JSON writing is only enabled when setting a command line option, right?

I did not, because you didn't mention it anywhere in your PR description. In that case, it should be fine.

**Pull request merged**
