### PR TITLE
various assertions to improve the sexp code

### PR DESCRIPTION
**Pull request by Goober5000**
A few asserts, a comment correction, and a removal of an Int3()

### CODE REVIEW

**Comment by MageKing17** [comment]
Not a fan of adding bare any bare Assert()s instead of Assertion()s which can include an explanation of what the assertion is there for.

**Comment by Goober5000** [comment]
What I did in this commit was use Asserts for the obvious checks, and Assertions for the ones that were not so obvious.

I think documentation should be meaningful, not something that's just added for its own sake.  What advantage does 
    Assertion(token != NULL, "The token argument must not be null!");
have over
    Assert(token != NULL);
?

**Comment by MageKing17** [comment]
None, which is why I'd write "get_operator_index() called with a null token; get a coder!\n" instead. I prefer that to the bare Assert().

For the other bare Assert(), you have a couple values that could be displayed in the message (namely, `node` and `Num_sexp_nodes`). Being able to see those in the message could help catch a problem sooner.

**Comment by Goober5000** [comment]
I still don't think that adds much, but it's quicker to make the change than continue arguing the point. :p

**Comment by Goober5000** [comment]
O.o did that push go to a sexp_assertions branch in the main repository instead of a branch in my fork?

**Comment by niffiwan** [comment]
It looks like the 1st commit (e1d3838) is in a branch within the main repo, the 1st & 2nd commit (2b032a1) are in a branch in your fork?

**Comment by Goober5000** [comment]
@niffiwan All of the commits were supposed to be to a branch in my fork.  But I think my git configuration got into a weird state.

The latest change should satisfy all concerns.

**Comment by MageKing17** [comment]
Still doesn't report the value of `Num_sexp_nodes`, but it's not worth waiting for another commit when it's perfectly serviceable as-is.

**Pull request merged**
