### PR TITLE
Detect concurrent container modification

### PR DESCRIPTION
**Pull request by jg18**
Detect attempts to call a mutation SEXP on a container while the container is being used as an argument to a `*-argument` SEXP.

Depends on PR #4305.

### CODE REVIEW

**Comment by z64555** [comment]
Whats the severity of this PR, and should it be included in 22.2?

**Comment by jg18** [comment]
@z64555 I'd put it at Critical, since the intent is to avoid crashes that could result from FREDders trying to modify a container while they're using it as an argument to a `*-of` SEXP.

As I put it in #scp-private, it's the FSO equivalent of Java's [`ConcurrentModificationException`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/ConcurrentModificationException.html).

**Comment by z64555** [comment]
Alright, is this PR ready for review then?

**Comment by jg18** [comment]
Hoping to get it in a reviewable state this weekend.

**Comment by jg18** [comment]
Here are two versions of the same test mission from Karajorma in #fred.

The ["bad" version](https://github.com/scp-fs2open/fs2open.github.com/files/8839051/Bad_Containers_As_Args.fs2.txt) triggers the new warning but the ["good" version](https://github.com/scp-fs2open/fs2open.github.com/files/8839052/Good_Containers_As_Args.fs2.txt) doesn't.

**Review by JohnAFernandez — APPROVED** [review]
It looks so simple and elegant.  It's odd that it took quite a few commits to get it to this state.

**Comment by jg18** [comment]
@JohnAFernandez the reason for all those commits is that it's a branch off two other PR branches (can't look up numbers at the moment).

**Comment by jg18** [comment]
The PR's commits are mostly left over from PR #4299 and PR #4305 which are now merged.

They'll all be eliminated in the squash/merge, of course.

**Comment by jg18** [comment]
For the record, this PR was also part of completing Issue #4298.

**Pull request merged**
