### PR TITLE
Greatly increase the generation speed of index buffers.

### PR DESCRIPTION
**Pull request by SamuelCho**

### CODE REVIEW

**Comment by The-E** [comment]
Following the discussion on the forums, this should also remove the ibx-related commandline options and the references to .bx files in cfile.

**Comment by SamuelCho** [comment]
Stuff related to IBX files have been removed.

**Comment by chief1983** [comment]
Isn't there a commandline list of removed features, to intercept them and prevent the unrecognized flag warnings?

**Comment by chief1983** [comment]
Scratch that.  The game actually crashed trying to load Diaspora on my Mac.

**Comment by SamuelCho** [comment]
Any idea where it crashed?

**Comment by chief1983** [comment]
Here's the last bit of the log (pastebin won't allow it in full)
```
Loading model 'Col_Raptor_Armed.pof'
Potential problem found: Unrecognized subsystem type 'Doora', believed to be in ship Col_Raptor_Armed.pof
Potential problem found: Unrecognized subsystem type 'debactivatea', believed to be in ship Col_Raptor_Armed.pof
Potential problem found: Unrecognized subsystem type 'Flight_Officera', believed to be in ship Col_Raptor_Armed.pof
Potential problem found: Unrecognized subsystem type 'Co_Pilota', believed to be in ship Col_Raptor_Armed.pof
Potential problem found: Unrecognized subsystem type 'Pilota', believed to be in ship Col_Raptor_Armed.pof
Potential problem found: Unrecognized subsystem type 'FTL', believed to be in ship Col_Raptor_Armed.pof
Found live debris model for 'Flight_Officera'
Found live debris model for 'Co_Pilota'
Found live debris model for 'Pilota'
Index Buffer created in 1 milliseconds
Index Buffer created in 7 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 2 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 2 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 8 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 6 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 3 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 2 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 4 milliseconds
Index Buffer created in 4 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 3 milliseconds
Index Buffer created in 3 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 2 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 2 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 0 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 1 milliseconds
Index Buffer created in 1 milliseconds
Submodel 'Hullb' is detail level 1 of 'Hulla'
Submodel 'Hullc' is detail level 2 of 'Hulla'
Submodel 'Hulld' is detail level 3 of 'Hulla'
Submodel 'EngSupportb' is detail level 1 of 'EngSupporta'
Submodel 'EngSupportc' is detail level 2 of 'EngSupporta'
Submodel 'Tailb' is detail level 1 of 'Taila'
Submodel 'Tailc' is detail level 2 of 'Taila'
Submodel 'Taild' is detail level 3 of 'Taila'
Submodel 'engine1b' is detail level 1 of 'engine1a'
Submodel 'engine1c' is detail level 2 of 'engine1a'
Submodel 'engine1d' is detail level 3 of 'engine1a'
Submodel 'Dradisb' is detail level 1 of 'Dradisa'
Submodel 'Dradisc' is detail level 2 of 'Dradisa'
Submodel 'Dradisd' is detail level 3 of 'Dradisa'
Submodel 'Doorb' is detail level 1 of 'Doora'
Submodel 'Doorc' is detail level 2 of 'Doora'
Submodel 'Cockpitb' is detail level 1 of 'Cockpita'
Submodel 'Cockpitc' is detail level 2 of 'Cockpita'
Submodel 'engine2b' is detail level 1 of 'engine2a'
Submodel 'engine2c' is detail level 2 of 'engine2a'
Submodel 'engine2d' is detail level 3 of 'engine2a'
Submodel 'engine1b-destroyed' is detail level 1 of 'engine1a-destroyed'
Submodel 'engine1c-destroyed' is detail level 2 of 'engine1a-destroyed'
Submodel 'engine1d-destroyed' is detail level 3 of 'engine1a-destroyed'
Submodel 'engine2b-destroyed' is detail level 1 of 'engine2a-destroyed'
Submodel 'engine2c-destroyed' is detail level 2 of 'engine2a-destroyed'
Submodel 'engine2d-destroyed' is detail level 3 of 'engine2a-destroyed'
Submodel 'Doorb-destroyed' is detail level 1 of 'Doora-destroyed'
Submodel 'Doorc-destroyed' is detail level 2 of 'Doora-destroyed'
Submodel 'debactivateb-destroyed' is detail level 1 of 'debactivatea-destroyed'
Submodel 'debactivatec-destroyed' is detail level 2 of 'debactivatea-destroyed'
Submodel 'debactivated-destroyed' is detail level 3 of 'debactivatea-destroyed'
Submodel 'debactivateb' is detail level 1 of 'debactivatea'
Submodel 'debactivatec' is detail level 2 of 'debactivatea'
Submodel 'debactivated' is detail level 3 of 'debactivatea'
Submodel 'chaingunsb' is detail level 1 of 'chaingunsa'
Submodel 'chaingunsc' is detail level 2 of 'chaingunsa'
Submodel 'chaingunsd' is detail level 3 of 'chaingunsa'
```
It may be that it crashed on the next model it attempted to load before getting to put a Loading line in the log, not sure.  I don't know what that model would be.

**Comment by SamuelCho** [comment]
I tried loading a bunch of models in the lab. I'm getting no crashes. You wouldn't happen to have a stack trace of this, would you?

**Comment by chief1983** [comment]
#include what?

Also, no stack trace yet, not sure I've ever gotten one on OS X actually.  Maybe I need to copy the .dsym alongside it, not sure.

**Comment by chief1983** [comment]
Would it be odd that in the debug status at the top of the screen, I seem to see the same model being loaded more than once during mission load?  Not sure if that's because of the bx removal specifically or that always happens, but maybe there's a memory override possibility somewhere with larger models?

**Comment by chief1983** [comment]
Ok, ran it a second time and it did crash.  Got an apple crash report though, maybe that's got enough stack info to help.  http://pastebin.com/f8TdLeri

The tail end of the log this time looks the same actually, the last model was Col_Raptor_Armed.pof.

**Comment by chief1983** [comment]
https://www.dropbox.com/home?preview=crash_log_NOIBX.txt  Here's the crash log in full, pastebin wouldn't allow it.  Seems like it doesn't like the sobek, although that's not where it seems to have crashed.

**Comment by SamuelCho** [comment]
Any specific mission you're running as well? I'm sure it doesn't matter but I'm asking just in case it may be a specific SEXP that's causing this issue. I mean, maybe I just need to rebase this branch with trunk and the problems may go away.

**Comment by chief1983** [comment]
Did I forget to mention?  I've been loading The Strike.

**Comment by chief1983** [comment]
I can also confirm niffiwan's issue, this is definitely failing to compile on Linux as-is, not sure what he was saying we need to include since I think the markdown ate his comment.

**Comment by SamuelCho** [comment]
it needs #include < algorithm >, that's what he was saying.

**Comment by chief1983** [comment]
Gotcha.  Yeah adding that to 2d.cpp fixed that compilation error.  Is that a cross-platform include then?

**Comment by niffiwan** [comment]
sorry about that, markdown did eat my comment :(
```<algorithm>``` is cross platform, I'm sure Swifty has included in the deferred render branch (for instance)
https://msdn.microsoft.com/en-us/library/yah1y2x8.aspx (2013)
https://msdn.microsoft.com/en-us/library/yah1y2x8%28v=vs.100%29.aspx (2010)
https://msdn.microsoft.com/en-us/library/yah1y2x8%28v=vs.80%29.aspx (2005)

**Comment by SamuelCho** [comment]
It seems like the game is needlessly loading and unloading the Sobek. I think zookeeper's commit was supposed to fix this (https://github.com/scp-fs2open/fs2open.github.com/commit/dc820fdfc1885e194db87ebb219ad73a90ce8b4a) but it was reverted because his commits didn't go through proper code review.

**Comment by chief1983** [comment]
Well, good to know there's a fix for that, it will speed up loading substantially I think.  But, should simply reloading a model lead to a segmentation fault?  Not even sure that's what caused it, since the crash report seemed to be neck deep in sexp functions.  I can try a few more times with master to see if I can make it crash though, apparently your branch doesn't generate a seg fault every run so master might have gotten lucky when I tested.  And if it's in master then this branch is unrelated to my crash.

**Comment by SamuelCho** [comment]
Yeah I noticed the SEXP weirdness too. Perhaps it's related to the bug I noticed in the issue involving a particular commit involving SEXP evaluation (https://github.com/scp-fs2open/fs2open.github.com/issues/84).

**Comment by chief1983** [comment]
Ok, crash happens on latest nightly so this is off the hook for causing it.  Probably is related to the SEXP weirdness then.  Guess I don't see a reason not to get this in but we definitely need to address #84 and zookeeper's missing double load issue.

**Comment by SamuelCho** [comment]
Sweet, thanks for testing, chief. And thanks to you, we managed to find a pretty significant bug even if it wasn't related to this, heh.

**Comment by MageKing17** [comment]
I've tracked down the cause of chief's segfault (my fault from 83b59fb76c1c60bb10777be49f9089b64d4c9ac4 again). Anybody found any issues with *this* code, or can we go ahead and merge?

**Comment by niffiwan** [comment]
I still can't see ```#include <algorithm>```, but otherwise this looks good

**Comment by SamuelCho** [comment]
It's now in there.

**Comment by niffiwan** [comment]
brilliant; & merging

**Pull request merged**
