### PR TITLE
Upgrade Mac Frameworks.tgz and the libsdl folder to SDL 2.0.4.

### PR DESCRIPTION
**Pull request by chief1983**
Remove "Only Active Archs" setting from Travis configuration to see if that's enough to get it to only build x64 now.

### CODE REVIEW

**Comment by SamuelCho** [comment]
So I managed to compile a build of SDL 2.0.4 as a universal binary. Would that solve the x64 exclusivity issue if I got that in?

**Comment by asarium** [comment]
@chief1983 If you removed the usage of `ARCHS=$MACOSX_ARCH` then you could also remove the relevant matrix configurations from `.travis.yml` which will reduce the build time of the CI builds.

**Comment by MageKing17** [comment]
> So I managed to compile a build of SDL 2.0.4 as a universal binary. Would that solve the x64 exclusivity issue if I got that in?

It's my understanding, from what @chief1983 said on IRC, that we no longer support any 32-bit versions of OSX anyway.

**Comment by chief1983** [comment]
Yup, since we moved to a 10.7 target, there couldn't be 32-bit machines running our builds now.  We had to move targets up because of the C++11x features we use now.  So if I'd been paying attention we could have cut down build sizes by half months ago.  And since that's the case, the official SDL2.framework with x64 only should do fine for us.  Guessing removing that line from the script meant that it ignored the i386 arch and just built x64 twice.  I'll remove the i386 stuff from the yml config as recommended, I didn't realize it was located outside of the ci folder until just now.

**Pull request merged**
