### PR TITLE
Remove unused timerbar files

### PR DESCRIPTION
**Pull request by asarium**

### CODE REVIEW

**Comment by chief1983** [comment]
Did we ever use the timerbar?

**Comment by asarium** [comment]
It wasn't referenced anywhere in the code (the VS2015 project files actually didn't contain the files and the executable still linked fine) but I don't know if that was always the case.

**Comment by chief1983** [comment]
I think it was in use at one point in time.  We should probably identify for sure why it was removed, but not completely.  https://code.google.com/p/freespace2wii/source/browse/code/graphics/gropengl.cpp?r=80836add0e92cad5d82353e5fb4207c624768f36 for instance seems to indicate that it was once in place in gropengl.cpp, as the Wii fork still has a reference to it.

**Comment by chief1983** [comment]
https://github.com/svn2github/fs2open/blob/master/trunk/fs2_open-unstable_old/code/graphics/grd3dsetup.cpp back from the d3d days, this still used a d3d version of the call.  Did the timerbar just stop working at some point?

**Comment by asarium** [comment]
@The_E removed the timerbar code in e23da70624848356e56792772ed7817d92f01889 and 273be5d2212b4d303107011f16444305a162fb2e added a message saying that -timerbar was deprecated.

I think it's safe to assume that it isn't needed anymore.

**Comment by chief1983** [comment]
Ok sounds good to me then.

**Comment by Goober5000** [comment]
It was used fairly extensively back in the day, but I don't recall that people have used it in the past few years.  Either Taylor or WMC used it IIRC.

**Pull request merged**
