### PR TITLE
add workaround for broken windows workflow

### PR DESCRIPTION
**Pull request by notimaginative**
Temporary fix for broken windows workflow. Hopefully a more permanent solution will be found soon and we can then remove this.

Reference: https://github.com/actions/runner-images/issues/8598

### CODE REVIEW

**Comment by notimaginative** [comment]
Setting this as a draft until there is a consensus as to whether to use this temporary fix or to wait for a proper solution from github. Also this isn't directly tested but a copy&paste for the recommended workaround from linked github issue.

**Comment by JohnAFernandez** [comment]
It would be nice to have this, so I can continue work on my github actions script.

**Review by Goober5000 — APPROVED** [review]
Well it fixed the automatic builds.  I say let's use it.  We can revert it easily enough if we need to.

**Comment by JohnAFernandez** [comment]
Confirmed: this does fix the issue in my script, so it should probably be merged.

**Pull request merged**
