### PR TITLE
Mantis#2129 Address Rare Multi Crash

### PR DESCRIPTION
**Pull request by JohnAFernandez**
Should fix rare multi crash where reserving net signatures for spawned munitions would cause an ushort overflow, triggering an assert in multi_set_network_signature.

Link to mantis issue: http://scp.indiegames.us/mantis/view.php?id=2129

@notimaginative if you could take a quick look to make sure I'm understanding the situation correctly.

In draft because this is not yet tested, because I do not have a multi testing solution yet.

### CODE REVIEW

**Comment by notimaginative** [comment]
I think it would be better to fix this in `multi_set_network_signature()` since that will work everywhere and no one should have to deal with it in the future. You should be able to get away with just removing the `Assert()` and doing `NPERM_SIG_MIN + signature`, taking advantage of the wrap-around. Just be sure it stays within the bounds of `NPERM_SIG_MIN` and `NPERM_SIG_MAX`.

**Comment by FSCyborg** [comment]
All right, let's try that instead.

**Comment by notimaginative** [comment]
Looks good to me. May want to add an `Assert()` checking that `NPERM_SIG_MIN + signature` is less than `NPERM_SIG_MAX` (might have to static_cast<uint> something, not sure). It shouldn't ever happen, but it technically can, so best to check for it so we'll know if the near-impossible happens in the future.

**Comment by JohnAFernandez** [comment]
Just finished testing.  Weapons and objects, appear to work as well as before the changes.

**Comment by wookieejedi** [comment]
Looks like everything is good to go then?

**Comment by JohnAFernandez** [comment]
Everything is ready

**Pull request merged**
