### PR TITLE
Improve consistency/flexibility of version-specific comments.

### PR DESCRIPTION
**Pull request by MageKing17**
`matches_version_specific_tag()` now uses the previously-FRED-only `scan_fso_version_string()` function, meaning it now supports version-specific comments with as few numbers as `;;FSO 3;;` to as many numbers as `;;FSO 3.7.3.20151106;;`, instead of you being required to supply exactly 3 numbers.

### CODE REVIEW

**Comment by The-E** [comment]
Didn't we decide to get rid of these things years ago?

**Comment by MageKing17** [comment]
We can't get rid of them without breaking backwards compatibility. If we're stuck with them, we might as well make them work properly.

**Comment by Goober5000** [comment]
We decided to prevent FRED from saving version-specific comments in the mission file (unless specifically in that save mode).  We didn't decide to get rid of the entire concept of version-specific comments in the first place.

**Comment by The-E** [comment]
Oh, right, I remember. LGTM, then.

**Pull request merged**
