### PR TITLE
Fix Modern-style Sounds Using Number Indices

### PR DESCRIPTION
**Pull request by wookieejedi**
PR #6112 protected retail sound indices from being overwritten with the intent of when modders used string names for sounds,. Though that PR ended up being a bit overprotective because it made it so that using the modern sound format but still using numbered names did not work. In other words, for mods that use the modern sound format but still use numbered names, FSO sees the new format but then sees the numbers are within a protected range and offsets them, which means the sound index values referenced in ships and weapons table now are not correct and thus do not play.

This PR fixes that edge-case. Tested and works as expected. Also, if folks would rather just rever the entire protective offset aspect I am fine with that and we can instead just make a warning to the modder that their sound name will overwrite a protected range (though the changes of this PR to check if the name is the index should still be included, since an overwrite warning is not needed if the index and name are already the same).

### CODE REVIEW

**Review by JohnAFernandez — APPROVED** [review]
Lgtm

**Review by Goober5000 — CHANGES_REQUESTED** [review]
I want to look at this closely and run some tests, so let's put this on hold for a bit.

**Comment by JohnAFernandez** [comment]
So, this is actually a pretty simple change.  The logic is changed in only two places, the rest is whitespace or optimization.  Wookie has already tested the changes as well.  I just don't think there's much risk in merging it.  If you want to investigate if any further changes need to be made, couldn't you do that after this is merged?

**Comment by Goober5000** [comment]
It's not a question of whether there will be any fixes needed after this PR, but whether this PR is in fact the correct fix.  It may pass wookieejedi's tests but it also needs to pass the Inferno tests that were the reason for the original PR.

My schedule had been pretty hectic the last few days but it's lighter today, so I expect to have an answer soon.

**Comment by Goober5000** [comment]
Root cause identified.  Unfortunately, this PR only hides the problem; it does not solve it.  PR #6212 has the proper fix.

**Pull request closed without merging**
