### PR TITLE
Bugfix event log flags

### PR DESCRIPTION
**Pull request by Karajorma**
Fix the bugs with event log flags, repeat count, etc mentioned in this thread. http://www.hard-light.net/forums/index.php?topic=90763.msg1801379#msg1801379

### CODE REVIEW

**Comment by asarium** [comment]
Can you rebase the branch onto the latest master? There are a few changes that shouldn't be in this PR.

**Comment by Karajorma** [comment]
It was a complete pain getting it this close to be honest. I have no idea how to rebase or why stuff got pulled in that shouldn't have been.

**Comment by asarium** [comment]
At this point using cherry-pick it probably the best solution.

Create a new branch based on master and then execute `git cherry-pick 4046a0a0a04a2cd5b68a31aee2e6f050da4131d2` (if you are using a GUI then there should be an option to do the same).

**Comment by MageKing17** [comment]
I think the problem was that his fork's master got out of sync; commit 99a7196 shouldn't have been a commit, it should have been a hard reset followed by a force push.

**Pull request closed without merging**
