### PR TITLE
Some User Interface API cleanup and generalization

### PR DESCRIPTION
**Pull request by MjnMixael**
These are useful in places beyond just Command Brief.

### CODE REVIEW

**Review by Goober5000 — COMMENTED** [review]
I think this looks reasonable, but I'm curious about the reason for the move.  According to the code documentation, "a sublibrary is basically a nested namespace".  But if the API is `ui.runBriefingStageHook` under `l_UserInterface_CmdBrief`, then it should also be `ui.runBriefingStageHook` under `l_UserInterface_Brief`.  Is this correct?

**Comment by MjnMixael** [comment]
The truth is I did not read into that one enough yet to know if it was C.Brief specific or general to all briefs. That's the only reason I did not move it yet.

**Comment by Goober5000** [comment]
Oh, well I can tell you that `On Briefing Stage` is fired for both command briefings and regular briefings.  But what I mean is, what does the move actually do?  Does it affect the script API, or is it simply for code organization, or does it do a third thing?

**Comment by MjnMixael** [comment]
Moving the items affects the scripts in that they'll be called by ui.Briefing.ACTION now instead of ui.CmdBrief.ACTION, so a slight affect there. However yes, it is mostly organizational.

**Review by Goober5000 — APPROVED** [review]
Ok, gotcha.  That all sounds good then.

**Pull request merged**
