### PR TITLE
Maximum filename limit increase

### PR DESCRIPTION
**Pull request by bryansee**
Since the FS2 source code release, the maximum filename limit increase has been among the most neglected. Many modders having problems in specifying file names larger than 32 characters. When running either FRED or FS2, an error message usually appears, alerting that the 32-character has been exceeded. Accordingly, a filename character limit is increased, so does the callsign limit.

### CODE REVIEW

**Comment by chief1983** [comment]
It looks like there's only one commit that should be in this push, perhaps the branch history could be cleaned up a bit?

**Comment by asarium** [comment]
There are a few things wrong with this PR:
 1. You have a lot of commits that are not related to these changes. You have to clean up your history to only contain commits related to this PR.
 2. Changing the value of such a fundamental constant will cause some subtle issues. A lot of testing would be needed to make sure nothing gets broken by these changes.
 3. Increasing the file name length by eight times wastes memory. For all previous mods 32 byte is enough so the remaining 224 bytes would be wasted for every field that uses the `MAX_FILENAME_LEN`.
 4. If there are issues with the predefined length of a string field then `SCP_string` should be used where possible. It's obviously not an easy task to do this for the entire code base but if you encounter a specific mod option that suffers from this problem you could try improving that specific option to use a variable length `SCP_string` instead of a `char` array.

I also just tested the patch on linux, I let the WiH intro cutscene mission run and everything seemed to be alright.

**Comment by DahBlount** [comment]
I'd recommend either starting starting on a new branch or doing an interactive rebase to remove those merge commits, then rebase master onto your branch. In order to avoid messy histories, you should use `git fetch remote` then `git rebase remote/branch` instead of `git merge`.

**Comment by MageKing17** [comment]
There's very little point to bumping `MAX_FILENAME_LEN` instead of, say, converting all instances of filenames and paths to SCP_string objects; the semi-recent `MAX_PATH_LEN` bump was more of a hotfix for Interplay's bungled Steam release of FS2 (trying to avoid throwing ERANGE errors if FSO was installed to the default Steam folder) rather than any kind of inspirational model for how things should be handled.

I have a vague memory of there being some sort of patch in progress either for or based on Antipodes (or possibly already a part of Antipodes) related to string-based paths; does that ring a bell for anyone else? If nothing else, it would be a better starting point to work from.

**Comment by bryansee** [comment]
To reply chief1983's question, yes.

To DahBlount, thanks. I'll keep that in mind.

The 32-character limit for filenames are beginning to bug me (and other FSO modmakers for that matter) recently in the form of ERANGE errors, who asked me to report.

**Comment by MageKing17** [comment]
> The 32-character limit for filenames are beginning to bug me (and other FSO modmakers for that matter) recently in the form of ERANGE errors, who asked me to report.

It's... odd that modmakers would ask you to report a problem instead of just reporting the problem, but whatever.

A 32-character filesize limit is an annoyance rather than a showstopper; you aren't likely to run out of valid filenames before you run out of things to put in those files. As such, it's inherently a lower priority than, say, getting the 3.7.4 release candidate phase started so we can merge Antipodes and fix a whole host of problems (including hopefully getting rid of `MAX_PATH_LEN`, which is at least tangentially related to `MAX_FILENAME_LEN`).

**Comment by The-E** [comment]
This is not a critical issue. It is strictly in the "nice to have" category, and as such, we have time to implement this properly. The only cases I am aware of where this limitation has caused issues are either mods in development where the Modder was unaware of this particular limitation, or cases where the exercise was asked to load invalid data due to file corruption.

**Comment by The-E** [comment]
Meant to say executable there. Autocorrect strikes again...

**Comment by Goober5000** [comment]
Agree with @The-E and others.  There are very good reasons why certain limits haven't been bumped.

**Comment by The-E** [comment]
One more thing: Changes to the maximum filename length will also need to be implemented in the .vp file format, as filenames there are also assumed to be no longer than 32 characters.

**Comment by bryansee** [comment]
Thanks. I'll keep that in mind, The E.

**Pull request closed without merging**
