### PR TITLE
Remove DirectX remains

### PR DESCRIPTION
**Pull request by Echelon9**
*This is a PR to merge into Antipodes branch*

Following on from adoption of SDL2 middleware in our Antipodes branch, the remaining DirectX era legacy libraries should be removed.

NOTE: I do not have a Windows setup to actually test this. There are no issues on non-Windows platforms.

This is a repurpose of #231 (PR to merge into master).

### CODE REVIEW

**Comment by asarium** [comment]
Seems like the old force feedback stuff is still using the

**Comment by asarium** [comment]
Looks like the old force feedback stuff is still using DirectX. It's probably not used anymore but still included in the project files which breaks compilation.

**Comment by chief1983** [comment]
Yeah, seems that code\io\swff_lib.cpp is still in the codebase, and it includes code\io\sw_force.h, and both include code\directx\vdinput.h.  FF is currently broken on Antipodes (see #242) but I wonder if any working SDL FF implementation would need to rely on any DirectX FF related code.

**Comment by chief1983** [comment]
Should probably revisit this now.  The vdinput.h references can probably be removed safely at this point and FF behavior tested with them gone.  I don't expect any of the current code to use any vdinput calls now though.

**Comment by asarium** [comment]
The remaining changes from the PR have been merged as part of #724.

**Pull request closed without merging**
