### PR TITLE
Fix shader compilation on Mesa OpenGL drivers

### PR DESCRIPTION
**Pull request by asarium**
FSO is currently unusable on Mesa OpenGL drivers because they actually implement the standard properly and generate an error when GLSL language features are used that are not supported by the specified version. FSO current doesn't specify the required GLSL version in the shaders because there are some buggy drivers that don't like it.

To fix both issues I introduced a driver workaround mechanism that checks the opengl vendor or renderer strings and possible sets the workaround flags so the driver can still be supported.

Currently no vendor is detected so I need some people to test this version and report if there are vendors that don't work with `#version` in the shader.

### CODE REVIEW

**Comment by chief1983** [comment]
This sounds like it is the more comprehensive solution for an earlier attempt to just add the version universally, which broke one of the other vendors right?

**Comment by asarium** [comment]
@The-E Said it would break on the AMD implementation.

**Comment by Echelon9** [comment]
No suprise that it appears AMD's Catalyst driver is behaving badly off-spec, but can we confirm which AMD drivers (version and OS) actually trip up?

I'm far more inclined to put in the *standards compliant* behaviour for all, including Mesa, and then deal with AMD drivers via some hacky solution for as long as we can bear it.

**Comment by asarium** [comment]
I enabled version workaround for AMD with the vendor string provided by @The-E.

**Comment by Echelon9** [comment]
Great, thanks!

**Comment by niffiwan** [comment]
FYI, some nVidia on Linux results [here] (http://www.hard-light.net/forums/index.php?topic=90348.msg1793988#msg1793988) (closed source drivers)

**Comment by asarium** [comment]
I added a commandline option to override which workarounds are used which can be used for testing.

**Comment by MageKing17** [comment]
Looks like VS 2010 didn't like it.

**Comment by asarium** [comment]
Pushed an update that doesn't use range based for, I think VS doesn't like that...

**Comment by asarium** [comment]
These changes are currently not mergable as the shaders fail to compile on Nvidia drivers. Here is the log @niffiwan provided: http://pastebin.com/pDRpU3ui

**Comment by Echelon9** [comment]
So appears the underlying issue is that our shaders have been progressively bumping the minimum supported version on certain hardware, eg for 'ARB_texture_buffer_object' that requires us to track and include at least 'version #140'.

What has been masking this issue is that for at least the proprietary NVIDIA blob drivers no 'version' was required at all.

**Comment by asarium** [comment]
I think we actually only need `version 130` so we can use `texelFetch`. For `samplerBuffer` we need to add `#extension GL_EXT_gpu_shader4 : enable` to fix the first error.
The problem with `texelFetch` is that it's an OpenGL 3.0 feature but we are still limited to OpenGL 2 so we would have to add another workaround so we could use that function.

**Comment by asarium** [comment]
I investigated further on how to fix the Nvidia issues but our current rendering engine is such a mess that that is simply not possible. There are way to many assumptions that we can freely use whatever GLSL features are available.

If some one finds a proper solution for this we can reopen the PR but for now this can't be fixed easily. I think it's better to just wait for Vulkan and implement a new rendering engine with that.

**Comment by MageKing17** [comment]
What about a whitelist instead of a blacklist, adding the "#version" header for Mesa instead of taking it out for AMD/nVidia/wherever else it breaks?

**Comment by asarium** [comment]
I didn't consider that. Does anyone have the OpenGL vendor string of Mesa?

**Comment by asarium** [comment]
The Mesa vendor strings tomimaki posted aren't really easy to identify so I enabled the workaround for Nvidia drivers but Mesa probably won't like the rest of our shaders for the same reasons Nvidia broke.

**Comment by asarium** [comment]
This probably will never work and #425 has a better solution for the version problem.

**Pull request closed without merging**
