### PR TITLE
upgrade clang-tidy to 8.0, the latest stable release

### PR DESCRIPTION
**Pull request by Goober5000**
I propose upgrading the version of clang-tidy that we use.  This is motivated by a recent feature:

> New option _MinTypeNameLength_ for **`modernize-use-auto`** check to limit the minimal length of type names to be replaced with `auto`. Use to skip replacing short type names like `int`/`bool` with `auto`. Default value is 5 which means replace types with the name length >= 5 letters only (ex. `double`, `unsigned`).

It drives me nuts when `clang-tidy` wants to use `auto` instead of `int`.  I force-merged a previous PR because I refused to change it, and the same thing is happening again on #2026.

### CODE REVIEW

**Comment by niffiwan** [comment]
The idea sounds good, but are we sure that Travis provides version 8? The automatic tests didn't run clang-tidy because there were no code changes in this PR. Also [this page](https://docs.travis-ci.com/user/languages/cpp/#clang-on-linux) seems to suggest that clang version 8.0 isn't available yet, or if it is then more changes are required to `.travis.yml`?

**Comment by Goober5000** [comment]
Hmm.  Well, version 8 is released and downloadable from the clang website; active development is underway on version 9.  But Linux distribution support is another story.

**Comment by Goober5000** [comment]
I'm not exactly sure how to do that on the repository...

**Comment by asarium** [comment]
The relevant location for the changes is this:
https://github.com/scp-fs2open/fs2open.github.com/blob/a5d22589ecdbf430ba45ba98350adab8005d5d78/.travis.yml#L93-L102

Adding `llvm-toolchain-trusty-8.0` under `llvm-toolchain-trusty-4.0` and `clang-tidy-8.0` under `clang-tidy-4.0` should hopefully download the relevant packages.

**Comment by Goober5000** [comment]
Well that didn't work...

```
Installing APT Packages

0.42s$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install ninja-build libopenal-dev libreadline6-dev libpng12-dev libjpeg62-dev liblua5.1-0-dev libjansson-dev libsdl2-dev libfreetype6-dev valgrind qt57base clang-4.0 clang-tidy-4.0 clang-tidy-8.0 libc++-dev

Reading package lists...

Building dependency tree...

Reading state information...

E: Unable to locate package clang-tidy-8.0

E: Couldn't find any package by glob 'clang-tidy-8.0'

E: Couldn't find any package by regex 'clang-tidy-8.0'
apt-get.diagnostics

apt-get install failed

The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install ninja-build libopenal-dev libreadline6-dev libpng12-dev libjpeg62-dev liblua5.1-0-dev libjansson-dev libsdl2-dev libfreetype6-dev valgrind qt57base clang-4.0 clang-tidy-4.0 clang-tidy-8.0 libc++-dev" failed and exited with 100 during .
```

**Comment by tomimaki** [comment]
Seems they removed packages from https://apt.llvm.org/ 

> Aug 20th 2019 - Ubuntu Trusty remove (EOL)

**Comment by Goober5000** [comment]
¯\_(ツ)_/¯ @asarium what should I try next?

**Comment by asarium** [comment]
I'll see what happens if I change the distro to xenial (Ubuntu 16.04). That is still supported.

**Comment by asarium** [comment]
I added some changes that should upgrade clang-tidy. I updated the distro Travis uses to Xenial (16.04) in order to do that.

**Pull request merged**
