### PR TITLE
Fix doxygen documentation

### LINKED ISSUE #58: Doxygen documentation does not build on GitHub-derived fs2open
Because Git does not index empty folders, the required documentation/doxygen folder for building the Doxygen documentation is not present. This causes Doxygen to fail with fs2open.

There are also two warnings for obsolete features with Doxygen 1.8.9.1

```
$ doxygen --version
1.8.9.1
$ doxygen fs2open.Doxyfile 
Warning: Tag `XML_SCHEMA' at line 1846 of file `fs2open.Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: Tag `XML_DTD' at line 1852 of file `fs2open.Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
error: tag OUTPUT_DIRECTORY: Output directory `documentation/doxygen' does not exist and cannot be created
Exiting...
```

### PR DESCRIPTION
**Pull request by Echelon9**
Resolve #58 Doxygen documentation does not build on GitHub-derived fs2open.

Includes the creation of an "empty" directory documentation/doxygen, which a locally-initiated copy of Doxygen would populate.

### CODE REVIEW

**Comment by chief1983** [comment]
Not sure I like the idea of scattering .gitignore files throughout the repo.  Any empty hidden file could serve the purpose of keeping this directly in place though, like .keepdir, which semantically explains what it does.  Ignoring the contents of the doxygen folder could be handled in the root-level .gitignore.  

If I am investigating something and want to disable any gitignore behavior, I'd really rather not be hunting down every .gitignore file in the repository to do that.

**Comment by Echelon9** [comment]
I agree this is a subjective decision with two approaches available to us:
1. The approach presented in this patch, using a .gitignore in the folder; and
2. Your described approach, using an arbitrary file like [.keepdir] or [.gitkeep].

There appears to be no specific standard recommended from Git, although I've seen both approaches used in other projects.

FWIW, the Linux kernel team advocate approach (1) above: https://git.wiki.kernel.org/index.php/Git_FAQ#Can_I_add_empty_directories.3F

Shall we toss a coin to decide? Others' views on the preferred approach?

**Comment by MageKing17** [comment]
My inclination is towards chief's suggestion.

**Comment by The-E** [comment]
As is mine.

**Comment by Echelon9** [comment]
The tribe has spoken. I'll redo the PR with the revised approach.

**Comment by Echelon9** [comment]
And PR redone. Ready for code review and merge.

**Comment by chief1983** [comment]
I think this will do.

**Pull request merged**
