### PR TITLE
Treat Mouse as Joy0 if "turned on" in options menu

### PR DESCRIPTION
**Pull request by z64555**
Old Mouse Option Group:
image

New Mouse Option Group:
options_mouse

This control now, instead of simply doing nothing within the Controls5 version, toggles the mouse inputs between "Mouse" and "Joy-0."

When On, the mouse is treated as Joy0 and thus its axes and buttons are seen as coming from Joy-0.  This includes binding in the config menu as well as during game use, so some confusion may occur when a user is trying to bind their mouse and the button shows up as a Joy-0.  Should there be a physical joystick in addition to the mouse, the joystick inputs should play nice.

When Off, the mouse is treated as the mouse and is independent from Joy0 completely, and axes and buttons are seen as coming from the Mouse controller instead of Joy0.

This PR adds the following two XSTR indices:
1662 - "Mouse Input Mode"
1663 - "Joy-0"

Things to do:

- [x] Investigate whats needed to update the label on the Options menu to something more descriptive
- [x] Update the Information() string for plr conversion to inform the changes.

### CODE REVIEW

**Comment by z64555** [comment]
> ../code/controlconfig/controlsconfig.cpp:2696:3: error: this statement may fall through [-Werror=implicit-fallthrough=]
 2696 |   if (Use_mouse_to_fly) {
      |   ^~
../code/controlconfig/controlsconfig.cpp:2704:2: note: here
 2704 |  case CID_JOY1:
      |  ^~~~

Fallthrough is intentional here, but not sure how to //NOLINT it proper

**Comment by wookieejedi** [comment]
@BMagnu IIRC you had a fix for the previous //NOLINT, happen to know the fix here too?

**Review by Goober5000 — COMMENTED** [review]
Looks ok to me.  However I think I should hold off on explicit approval until the two "things to do" checkboxes are checked.

**Comment by z64555** [comment]
"Update the Information() string for plr conversion to inform the changes."

Since #4005 does the info popup differently, this sub-feature should depend on it.

**Comment by z64555** [comment]
XSTR indices will need to be updated as soon as #3988 goes through, since that PR also adds XSTR's

**Review by Goober5000 — APPROVED** [review]

**Comment by z64555** [comment]
XSTR indices updated. Enabled auto-merge.

**Comment by z64555** [comment]
Disabling auto merge because I forgot to add shout-out in the popup info. 🙅

**Pull request merged**
