### PR TITLE
lib/sdl208: Upgrade the included SDL libs to 2.0.8.

### PR DESCRIPTION
**Pull request by chief1983**
Should be merged at the same time as https://github.com/scp-fs2open/scp-prebuilt/pull/5

### CODE REVIEW

**Comment by asarium** [comment]
The prebuilt package is now available with the hash `d6d66b0100769457338b7ea5b8ebb84f5703e51e`.

**Comment by MageKing17** [comment]
I seem to have missed the new commit email; sorry about that.

If nobody has any ideas about what to do about AppVeyor in the short-term, I think this is worth merging anyway because SDL bugs keep causing problems and have been for months.

**Comment by asarium** [comment]
It's likely that the AppVeyor issue is caused by some reconfiguration on the AppVeyor systems but I do not have the time to track that down yet.

**Comment by chief1983** [comment]
If we merged it now, wouldn't the nightly just fail with AppVeyor in the current state?  May not want to merge anything until that's figured out.

**Comment by asarium** [comment]
#1732 should fix the Qt build issue.

**Comment by asarium** [comment]
@chief1983 Could you rebase or merge the newest changes from master into your branch? That should fix the Appveyor build.

**Comment by chief1983** [comment]
Rebase pushed, should be ready for merge shortly if all goes well.

**Pull request merged**
