### PR TITLE
Use SDL_GetPrefPath to determine config directory

### PR DESCRIPTION
**Pull request by asarium**
This tried to stay compatible with current installs as much as possible but for pilot files that isn't possible without rather substantial rewrites of the cfile system. Instead the launcher will handle copying the files from the old location.
These changes also will use the config directory for all writing operations on Windows similar to how Unix is currently handled.

This is currently not finished but it is ready for preliminary code review and testing. Remaining things to do:
- [x] wxLauncher compatibility (in work)
  - [x] Configuration files saved in correct directory based on selected build
  - [x] Player files copied to new directory
- [ ] Windows compatibility

EDIT: Remaining things should now be finished.

### CODE REVIEW

**Comment by niffiwan** [comment]
On the cmdline point, @MageKing17 suggested that it could instead be determined by the location of the config file. i.e.

    MageKing17: Surely we don't need a commandline flag for portable mode. Just look for the config file locally.
    MageKing17: If it's there, run in portable mode.

Also, this is going to conflict with a bunch of changes I was working on to enable more case-insensitive file/dir matching on Linux - but don't let that stop you, I'll just put that onhold for a bit & rework/merge that in later. Or rebase it vs Antipodes.

**Comment by MageKing17** [comment]
Similarly, can't we load pilots from multiple locations so the launcher doesn't need to copy them?

**Comment by niffiwan** [comment]
It could introduce a lot of extra complexity? i.e. reading & writing from two locations, but only creating new pilots in one? It would also be opaque to the user where any given pilot file would be stored.

Also, I thought TCs might find it useful to be able to specify a directory for pilots via a mod_table setting. i.e. on Linux/OSX currently all TBP / Diaspora / nuWoD / FSO pilots are mixed in together, having them separate could be useful.

i.e.
default -> $HOME/.local/share/HardLightProductions/FreeSpaceOpen/
Diaspora -> $HOME/.local/share/HardLightProductions/Diaspora/
etc

**Comment by MageKing17** [comment]
No need to write to multiple locations; just read.

**Comment by niffiwan** [comment]
So the pilots will effectively be transferred from the old location to the new location as part of the normal load/save process?

**Comment by MageKing17** [comment]
Then the only problem would be with deleting pilots, which is still an issue with the 3.7.0 pilot migration code.

**Comment by asarium** [comment]
I don't like the idea of introducing yet another backwards compatibility option that will rarely get used. In my opinion having the launcher (or the user if they don't use a launcher) copy the pilot files once to the new directory would be sufficient for most cases and it would also fix the pilot deleting issues introduced with the new pilot code.

**Comment by chief1983** [comment]
Part of the reason is to maintain a portable mode though right?  Ok, let's say you have no existing data files or config anywhere.  Fresh install, nothing but the exe and VP files.  How are we going to determine that the user wanted a normal install or to use portable mode?

**Comment by asarium** [comment]
Portable mode is only an add-on, this PR only aims to introduce unified config handling across platforms.

A "fresh" install would be considered a non-portable install by FSO. If the user uses a launcher then that would have to provide an option to write the config files to the game directory instead of the per-user config directory. Alternatively there will be a commandline option which will force FSO not to use the config directory.

**Comment by MageKing17** [comment]
"Yet another backwards compatibility option that will rarely get used"? Where were you planning on storing pilots in portable mode, exactly?

**Comment by asarium** [comment]
I was talking about copying the pilot files in a normal non-portable install.

**Comment by MageKing17** [comment]
And installations will never be allowed to switch between portable and non? Or you want the launcher to repeatedly copy save files every time?

**Comment by asarium** [comment]
You could switch portable and non-portable but of course FSO wouldn't display your portable pilots. Copying the pilot files would only ever be done in non-portable mode when the launcher somehow decides that this is your first time running a SDL build. For a portable install all this copying stuff obviously isn't needed.

**Comment by MageKing17** [comment]
And how is that better than reading pilots from more than one directory?

**Comment by asarium** [comment]
Because it doesn't require possibly substantial changes to the cfile system which currently is only able to list files from one on-disk directory.

**Comment by asarium** [comment]
wxLauncher compatibility has been finished. Pilot files will be copied to the new location if that location doesn't exist yet so it should be a one-time operation most of the times.

**Comment by asarium** [comment]
I decided to remove the portable install option for now because the rest is already done and wxLauncher would need some more changes for that to work properly.
Now everything about this should be finished.

**Comment by asarium** [comment]
I expanded the features of this branch to also include config file support on Windows so this PR doesn't really apply anymore. I'll open a new one once the changes have been tested by a wider audience (I'll post test builds shortly).

**Pull request closed without merging**
