### PR TITLE
Modernise CFLAGS on Mac/Linux

### PR DESCRIPTION
**Pull request by Goober5000**
Per GCC optimisation guide, which applies equally well to clang:
* -funroll-loops should not be used unless directed by profiling. The compiler will already unroll loops when it's a good idea.
* clang and gcc now have -Og optimisation levels designed to enable debugging with good performance.

(second attempt at PR #4562)

### CODE REVIEW

**Comment by Goober5000** [comment]
Well I solved the unused variable warnings, but now there's this interesting warning:
```
/__w/fs2open.github.com/fs2open.github.com/code/jpgutils/jpgutils.cpp: In function 'int jpeg_read_bitmap(const char*, ubyte*, ubyte*, int, int)':
/__w/fs2open.github.com/fs2open.github.com/code/jpgutils/jpgutils.cpp:170:56: error: argument 'image_data' might be clobbered by 'longjmp' or 'vfork' [-Werror=clobbered]
  170 | int jpeg_read_bitmap(const char *real_filename, ubyte *image_data, ubyte * /*palette*/, int dest_size, int cf_type)
      |                                                 ~~~~~~~^~~~~~~~~~
```

**Comment by Goober5000** [comment]
@notimaginative pinging since it looks like you did a lot of work in that function

**Comment by Goober5000** [comment]
Ok.  I'll have to get to this after the weekend but I'll make the change.

**Comment by Goober5000** [comment]
Ok, done.

**Review by notimaginative — APPROVED** [review]

**Pull request merged**
