### PR TITLE
Fix#1886 by Upgrading to SDL 2.0.10

### LINKED ISSUE #1886: Can't exit application if error is thrown
Recent nighties do this as well. 
For example if such error is thrown it is useless to press "Exit", it has no effect (maybe error cycles again to this window).

### PR DESCRIPTION
**Pull request by FSCyborg**
This should fix #1886.  I built it and it fixes the immediate problem.  2.0.10 is marked as stable on the SDL website.

If there are any files that should be removed, as in #1569 , I wouldn't mind doing that, just let me know.

### CODE REVIEW

**Comment by Goober5000** [comment]
Excellent work. :+1: 

I pinged chief1983 and MageKing17 to see if there are any "gotchas" from the last time SDL was updated.

@FSCyborg can you test enabling/disabling/switching joysticks, just to make sure there's no regression in the joystick bugs?

**Comment by asarium** [comment]
SDL is not handled via the prebuilt yet so at least that part is not needed for this PR.

**Comment by chief1983** [comment]
The mac folder contains SDL2.framework or am I missing something?

**Comment by FSCyborg** [comment]
I don't have a joystick to test.  Will using vjoy with a mouse work?

I will add the documentation sometime today.

**Comment by Goober5000** [comment]
@FSCyborg Don't worry about joystick testing, then.  We'll find out soon enough if there are any regressions.  I very seriously doubt there will be any, since the ones in a previous version of SDL were caught and corrected

**Comment by FSCyborg** [comment]
Turns out I had already copied the files into my working directory.  Maybe github is ignoring them?  I will try to get github to recognize the changes tomorrow.

**Comment by FSCyborg** [comment]
I just updated the documentation files which we already have in the repository.  Only two of them have actual changes.

@chief1983 I see mac folders for librocket, cmake, and the main freespace 2 folder.  I searched my repository directly for the word framework and couldn't find an already existing file.  Not sure if I should keep looking.

**Comment by chief1983** [comment]
I just opened the scp-prebuilt repo on github and clicked the Mac folder.  It has the sdl2 framework in it.  That's what was meant by that repo needing an update, that framework should be updated to 2.0.10

**Comment by FSCyborg** [comment]
@chief1983 Thanks, my brain didn't connect that you were responding to them and thought you were bringing up a new issue.

Now, even if building is not handled through there yet, I will submit another PR concurrently, just so that none of us forgets whenever we get around to actually using it.

**Comment by FSCyborg** [comment]
Here that is: https://github.com/scp-fs2open/scp-prebuilt/pull/6

**Comment by asarium** [comment]
I merged the changes but for some reason all the SSH keys were removed from that repository (we had that issue before...) so that doesn't work at the moment. I'll try to fix it tomorrow.

**Comment by asarium** [comment]
Ok, finally got the prebuilt stuff working again. You now need to use `b5cddcd84af2d85c9e9394c28e1fc5be16aacff6` in `prebuilt.cmake` instead of `4e87d4e7bef7c29316a0a4f9e33b1442b8edbee7`.

**Comment by FSCyborg** [comment]
Should now be switched.

**Pull request merged**
