### PR TITLE
Fix/refactor gr cursor interface

### PR DESCRIPTION
**Pull request by Echelon9**
Refactor of the `gr_cursor_*` interface into a clean class `CCursor` and associated enum.
* This refactor has enable optimisation of the code and improved readability. 
* Confirmed working with test runs through valgrind and gdb single step debugging.
* No visible issues in game.
* Fully doxygen documented.

Potential to move the Web_cursor_bitmap to this CCursor class in future.

### CODE REVIEW

**Comment by asarium** [comment]
Cursor handling has alrady been refactored [in Antipodes](https://github.com/scp-fs2open/fs2open.github.com/blob/antipodes/code/io/cursor.h) which means these changes will be obsolete once Antipodes gets merged into master.
Not sure if that means this shouldn't be merged but it's something to consider (the code looks good BTW).

**Comment by The-E** [comment]
Question is, do we merge this into trunk and adapt AP to use it?

**Comment by asarium** [comment]
AP doesn't need it, it's using the SDL cursor API to set the cursor of the window instead of drawing it with OpenGL.

**Comment by Echelon9** [comment]
I'm not adverse to dropping this PR, as we have a better approach sitting in the Antipodes branch.

How soon do we think we could merge in Antipodes?
With the new GitHub development process, we should consider not going for big, named branches and instead bring in more features, more often via PRs.

**Comment by The-E** [comment]
As far as I am aware, the only open issue on AP is force feedback support, which unfortunately is stalled due to a lack of developers with the required hardware.

**Pull request closed without merging**
