### PR TITLE
Controls4 - Multijoy

### PR DESCRIPTION
**Pull request by z64555**
The long awaited Multi joy feature. Multiple joysticks may be claimed by FSO from within the fs2_open.ini using the new keys:

```
Joy0ID=
Joy0GUID=
Joy1ID=
Joy1GUID=
Joy2ID=
Joy2GUID=
Joy3ID=
Joy3GUID=
```
Should "CurrentJoystick" be found, it'll assume only one joystick, so you'll have to manually edit fs2_open.ini to get this feature to work until the launchers are updated.

Joysticks show up in game as "Joy-0" with the respective bindings.

This provides significant changes over #2923 as well 
* Axis actions merged into the Control_config vector
* ADE function for inverting by action, instead of by axis
* Separate Mouse entirely from Joystick bindings. Shows up as "Mouse Button 1" etc.
* Removes saving bindings to .CSG, retaining only .PLR bindings.
  * This will be addressed with the ability to save to preset files in the future.

TODO: strings.tbl additions for axis labels, mouse and joystick button labels, controller labels

### CODE REVIEW

**Comment by z64555** [comment]
There is a bug with Knossos grabbing the wrong GUID, which can make it difficult to select them manually in the fs2_open.ini.  The GUID's reported in the fs2_open.log are correct. (search for "Initializing Joystick..." to get to the section that has the output from the joystick init)

**Comment by z64555** [comment]
@notimaginative This PR does add more items, so CCFG_MAX has changed in value.

**Comment by notimaginative** [comment]
Thanks for the heads up. Assuming the multi_packet_fixes PR gets in before this it shouldn't be a problem, since that PR includes a fix for the CCFG_MAX issue in multi.

**Comment by z64555** [comment]
Closing, and merging with #2958

**Pull request closed without merging**
