### PR TITLE
Added ai_profiles and path metadata options to force AI ships flying …

### PR DESCRIPTION
**Pull request by ln-zookeeper**
…bay paths to gradually accelerate/decelerate instead of flying the path at max speed.

This would be used to prevent arriving/departing fighters from overshooting curved paths, and/or making them gradually accelerate/decelerate when launching from or flying into a fighterbay for aesthetic reasons.

When arriving from a bay, the speed is initially multiplied by the given value, reaching the normal speed at the end of the path. When departing to a bay, the speed gradually ramps down to reach normal speed multiplied by the given value at the end of of the path.

Usage in ai_profiles.tbl (affects all bay arrivals/departures by default):

$bay arrive speed multiplier: 1.0
$bay depart speed multiplier: 0.2

Usage in ships.tbl (takes precedence over the ai_profiles settings):

$Path Metadata: $bay05_left
+departure rvec: 1.0, 0.0, 0.0
+arrive speed multiplier: 0.1
$Path Metadata: $bay06_right
+arrive speed multiplier: 0.3
+depart speed multiplier: 0.6

### CODE REVIEW

**Comment by niffiwan** [comment]
After running some tests I've got a few questions about this one:

1) I don't think this will work if only the AI Profiles setting is used.  i.e. if the bay paths never match because they aren't defined then speed_mult will never be set to FLT_MIN
2) Setting the AI profiles flag also requires ```$ai path mode: alt1```, otherwise the new code never gets called. Therefore setting the new flags should probably auto-set ```$ai path mode: alt1```, and maybe log a warning as well?

Everything else looks OK and tests OK so far.

**Comment by ln-zookeeper** [comment]
I believe both issues should now be fixed. It should not be hard to port the code to work with the normal pathing mode as well at a later point, but for now I simply added warnings about it.

**Comment by ln-zookeeper** [comment]
It seems I really wasn't thinking straight when I wrote that part. I think I'll just port the code to ai_path_0() as well, it's not particularly tricky after all.

**Comment by ln-zookeeper** [comment]
Now the warnings should be gone and the feature work in both pathing modes.

**Comment by niffiwan** [comment]
looks good to me and tests fine.  The merge conflict is also trivial.

**Pull request merged**
