### PR TITLE
Multi sexp fixes

### PR DESCRIPTION
**Pull request by notimaginative**
Addresses some multi sexp issues:
* try to handle incompatible sexp packets better
* fix operator name issue with debug messages
* enable the new show-subtitle-text options

### CODE REVIEW

**Comment by notimaginative** [comment]
This is a breaking change so it's in draft status until we're ready to merge other breaking multi PRs to avoid so many version bumps.

**Comment by notimaginative** [comment]
@JohnAFernandez It passed all of my tests so I think it's ready to go. We just need to make sure it ends up in the same nightly as one of your changes which includes a version bump.

**Review by JohnAFernandez — COMMENTED** [review]
Not that many lines changed.  And it looks straight forward.  Because of my current state, I'll take another look tomorrow, just to see if I can catch anything.

**Review by Goober5000 — COMMENTED** [review]
There are four total instance of
```
// TODO: uncomment when Github ticket #3773 is implemented
```
Did you want to uncomment all of them?

**Comment by notimaginative** [comment]
Yes I did, but obviously did a poor job of looking for them.

**Review by Goober5000 — APPROVED** [review]

**Pull request merged**
