### PR TITLE
joy_asynch - Enables SDL's event handling for joystick axes

### PR DESCRIPTION
**Pull request by z64555**
Previously, when a joystick event happened that was related to axis movement, it would be ignored by the os_poll(). Button presses from joystick events were still processed, however.

This PR changes the axis polling system to be asynchronous of frame time, simplifying the joy_read functions to just read from a buffer instead of polling the joystick per frame. This should hopefully be the "fastestest" we can get with SDL when concerning analog inputs.

### CODE REVIEW

**Comment by asarium** [comment]
What's wrong with including <limits> to fix GCC compilation?

**Comment by asarium** [comment]
Also tested in on linux, seems to work fine but it would be better to hold of on merging this until the sync PR has been merged.

**Comment by z64555** [comment]
It doesn't make immediate sense to include <limits> in joy-sdl.cpp since there's nothing in there that explicitly uses it. Instead of converting JOY_AXIS_CENTER et. al. into a const value, gcc is treating treating as if it were a #define and then complaining that it can't find <limits> even if it was #included in joy.h

**Comment by z64555** [comment]
oui, m|m pointed out some time ago that it should've been <climits> instead of just <limits> we'll see how this one goes.

**Comment by z64555** [comment]
Looks like that did the trick, waiting on PR #319

**Pull request merged**
