### PR TITLE
Save fade-out color, even if its black.

### PR DESCRIPTION
**Pull request by z64555**
Fixes issue #2960 

The existing logic for black fade-ins is overridden to use whatever color the previous fade-out did, and at some point during the end of the cutscene, the fade_out colors were being bashed to white.

edit:  As insurance, init the fade_out color to black at mission start with init_sexp

### CODE REVIEW

**Review by Goober5000 — CHANGES_REQUESTED** [review]
Keep that Mantis 2944 comment; it's important to know that information.

Instead of removing the RGB comparisons entirely, try this.  Store the array count from the `eval_array` call several lines up, and do this:
```
// Mantis #2944, if we're fading out to some specific color, save that color
if (!fade_in && rgb_count > 0)
```

**Comment by z64555** [comment]
ehhhh. honestly I think this section could be refactored a bit

**Comment by Goober5000** [comment]
> ehhhh. honestly I think this section could be refactored a bit

I don't think so; I think the sexp is written just about as well as it can be.

However, the `Fade_out_[rgb]` variables aren't reset upon mission load.  Try resetting them to -1 in `init_sexp`.

**Comment by z64555** [comment]
Ok, so lets break down whats happening in sexp_fade

ints R, G, and B are read in from the sexp, given a value of -1 should the passed values are invalid or nonexistant.

Should any of the R, G, or B values be negative, (or implicitly outside of the range of 0~255), legacy fade color block kicks in.  This block will select it to be one of four colors: White if R =1, Red if R = 2, and Black for any other value of R.

If a fadeout had occurred beforehand, instead of using Black it will use the fadout color.


> Instead of removing the RGB comparisons entirely, try this. Store the array count from the `eval_array` call several lines up, and do this:
> 
> ```
> // Mantis #2944, if we're fading out to some specific color, save that color
> if (!fade_in && rgb_count > 0)
> ```

So, having the rgb_count check for the second if block is moot, because by this time R, G, B are all set.

The refactor would get rid of this line entirely:
```
if (fade_in && (Fade_out_r >= 0) && (Fade_out_g >= 0) && (Fade_out_b >= 0))
```
and instead that else statement will just set the RBG to the Fade_out RGB, and finally have the Fade_out RGB initialized to black in the first place.

**Comment by Baezon** [comment]
"Maybe" fixes? That doesn't exactly inspire confidence, were you able to replicate the issue to see if it was fixed?

**Comment by z64555** [comment]
> 
> 
> "Maybe" fixes? That doesn't exactly inspire confidence, were you able to replicate the issue to see if it was fixed?

The "maybe" comment was from me not sure if I was running all of the same settings done with release 20.0 when I was running it with the test build, as I'm not familiar with how to do testing with mod data through the debugger.

**Comment by Goober5000** [comment]
> So, having the rgb_count check for the second if block is moot, because by this time R, G, B are all set.

No, that's why I said to store the count from `eval_array`.  Like so:
```
int rgb_count = eval_array<int>(temp_rgb, n, is_nan, is_nan_forever, [](int num) {
```
This way `rgb_count` will be > 0 if any color arguments were supplied.

**Review by MageKing17 — APPROVED** [review]

**Review by Goober5000 — APPROVED** [review]
Yup, I think this makes sense.

**Comment by z64555** [comment]
Confirmed as fixed on my side, using WiH part 2 campaign opening cutscene

**Pull request merged**
