### PR TITLE
fix control chars test that also excluded space key

### PR DESCRIPTION
**Pull request by notimaginative**

### CODE REVIEW

**Review by JohnAFernandez — APPROVED** [review]
Wow.  All this over that.

**Review by Goober5000 — APPROVED** [review]
LOL wow.

**Comment by Goober5000** [comment]
Are there any other tests in this file that might need to be tweaked?  For example, this one:
```
if ((ascii > 0) && (ascii < 255)) {
```
Should those be >= and <= ?

**Comment by notimaginative** [comment]
> Are there any other tests in this file that might need to be tweaked? For example, this one:
> 
> ```
> if ((ascii > 0) && (ascii < 255)) {
> ```
> 
> Should those be >= and <= ?

I think that test is correct. I believe that's actually from retail, just moved to a different spot.

**Comment by z64555** [comment]
:eyes:

**Pull request merged**
