### PR TITLE
convert qsort to std::sort

### PR DESCRIPTION
**Pull request by Goober5000**
My sources indicate that std::sort can often be substantially faster than qsort, since qsort invokes a function for every comparison whereas std::sort can inline the comparison.  Additionally, qsort makes no guarantees about performance, whereas std::sort is specified to have minimum n\*log(n) performance.  (In fairness, most implementations of qsort also have n\*log(n) performance, at least in the average case.  NB: qsort is not required to use the quicksort algorithm.)

Incidentally, @asarium may suspect that I'm biased against C++ due to conversations like #384, so hopefully this PR will serve as evidence otherwise. ;)

### CODE REVIEW

**Comment by niffiwan** [comment]
looks like you'll need to add this to the appropriate files for Linux to be happy:

#include <algorithm>

**Comment by Goober5000** [comment]
I think you need to edit that because github saw the brackets and decided to ignore what's inside them. :)  It just looks like:

> #include

The changes compile just fine on MSVC2013, though. :-/

**Comment by niffiwan** [comment]
yep - I fixed my comment by making it a code block :)

Yeah - not sure why linux has shoved a bunch of functions like std::sort into ```<algorithm>```

**Comment by Goober5000** [comment]
Ok, it looks like it was just that one file.  Let's see what Travis thinks.

Also, I'd appreciate a sanity check on the new sort helper functions that I modified.  I double-checked them and they look right to me, but a second opinion is always helpful. :)

**Comment by niffiwan** [comment]
LGTM

**Pull request merged**
