### PR TITLE
Remove IPX support.

### PR DESCRIPTION
**Pull request by jg18**
Remove support for the IPX protocol. The IPX selector button in the multi
options menu is now hidden, and the TCP button is disabled since there is no other option.

### CODE REVIEW

**Comment by z64555** [comment]
Reasoning behind dropping IPX support?

**Comment by jg18** [comment]
Please see the discussion in the netcode thread in the SCP internal. IPX is an outdated protocol that has long since been superseded by TCP/IP. Removing support for it simplifies the netcode and gets rid of a lot of Windows-only conditional compilation  macros. It's a prerequisite for tasks like switching to cross-platform sockets like Boost Asio.

**Comment by z64555** [comment]
You mean here, right? [http://www.hard-light.net/forums/index.php?topic=89758.msg1813528#msg1813528](url).

In which case I have no objections. But do please be sure to link relevant threads in future PR's so us derps can keep up. :P

**Comment by jg18** [comment]
Duly noted. Sorry for the confusion

**Comment by Karajorma** [comment]
Is there any reason why we're keeping Multi_options_g.protocol? Is that just to make IP6 easier if we ever decide to implement it?

**Comment by jg18** [comment]
Hmm, good question. I was trying to make the minimal amount of edits, but I can see that Multi_options_g.protocol doesn't mean much if we're no longer supporting IPX. However, since protocol is stored in the pilot file PLR IIRC, would removing it mean changing the PLR format? Or would we just have a placeholder value there that would be ignored?

**Comment by jg18** [comment]
In addition, if we want to support IPv6 later, I'd think a better way would be to make the netcode's low-level socket code IP version-neutral rather than allowing/requiring the player to pick between v4 and v6.

**Comment by asarium** [comment]
The boost socket API has some address abstractions. Hopefully that's enough to hide the differences between v4 and v6.

**Comment by chief1983** [comment]
Should he hide the entire protocol selection area, making a small black hole in the interface to simplify things?

Is there anything multi related that we could choose there instead, using the same art for the buttons and just modifying the text?  Unlikely I guess but I thought it would be worth considering.

**Comment by Echelon9** [comment]
I like the intent of this PR, and that the removal happens to clean up a fair chunk of platform specific code.
One thing to consider, which isn't clear here. Given the apparent changes to some network packet structs, does this PR led to network protocol incompatibility with other clients using earlier versions? If so, I recall there is an internal protocol version bit that might need to be incremented.

**Comment by jg18** [comment]
chief: Yeah, I thought about hiding the TCP button as well, especially since disabled controls tend to be confusing. I don't think it'd look that bad, just need to test it out. Besides, as you said,  we may find a use for the IPX/TCP buttons in the future.

As for the protocol variable and  IPv4 vs. v6, the player might have to manually choose between v4 and v6 when entering an IP address for example, such as when starting up a direct IP game instead of using FS2NetD. Need to think a bit more about the implications and whether the protocol  variable would be useful, but my inclination is to not get rid of it just yet. Also as noted, we'd need to do something about the PLR format if we did that, probably just a placeholder value so we wouldn't change the format.

Echelon9: Good point. I'll need to look into that, both whether the struct change causes an incompatibility and if so where the version number to increment is.

**Comment by chief1983** [comment]
FWIW, I ran a 'git rebase upstream/master' after checking out your branch, and that condensed it back down to one commit ahead of master.  I am unable to push to your repo but you should be able to run the same rebase command when you get back into town and that should clean this branch up.

**Comment by jg18** [comment]
As for the UI, in the multi options code, the protocol section includes not only IPX/TCP but also the IP address list and the tracker login boxes. So we can't easily hide just the protocol buttons and the artwork that  contains them.

How about this: show/enable both the IPX and TCP buttons, but when the player clicks on the IPX button, play the "general fail" sound and show a popup with "The old IPX protocol is no longer supported." This arrangement shouldn't lead to confusion on the player's part and doesn't require invasive changes to the multi options UI. Opinion?

**Comment by jg18** [comment]
Echelon9: You're right, changing the net_addr struct definition changed some packet formats which in turn required bumping the protocol version number (MULTI_FS_SERVER_VERSION). I also found some memory bugs caused by changing the net_addr's addr field's length from 6 bytes to 4, which affected some memsets and memcpy's. Finally I modified the header struct definition to reflect the changes made to the net_addr struct definition.

**Comment by jg18** [comment]
chief, I performed the rebase and the branch is now cleaned up, thanks.

**Comment by chief1983** [comment]
Welcome.  The popup solution for the TCP/IPX buttons should probably work fine too.

**Comment by jg18** [comment]
Echelon9 et al.: On second thought, I'm thinking that changing the definition/format of the net_addr and header structs was a mistake, at least as far as this PR is concerned. Besides the memset/memcpy gotchas of which I've foudn several more, the size of these structs may be the basis of other constants  like UDP_HEADER_SIZE in network\psnet2.h. Without a more thorough understanding of the netcode, I don't think we can be sure that these changes are safe, and such changes are arguably out of the scope of this PR besides. Opinion?

**Comment by The-E** [comment]
Agreed. Those changes need to be dealt with separately.

**Comment by jg18** [comment]
If that's the case, then the last 3 commits in this PR branch should be reverted. Would it be better to just roll back this branch's HEAD revision by 3 commits (hard reset) and then force push the change? Or would it be better to have three additional "revert" commits undoing them?

Once that's sorted out, I can add a follow up commit undoing the relevant changes made in the first commit.

**Comment by The-E** [comment]
I think a hard reset is the way to go here.

**Comment by jg18** [comment]
Ok, thanks.

As for Multi_options_g.protocol and Om_protocol, they might be useful to have for selecting IPv4 vs. IPv6 if we end up adding that, but I don't think it'll be clear until the switch to Boost Asio is complete. As such, I'm inclined to not remove them in this PR. Opinion?

**Comment by chief1983** [comment]
Leaving them for now sounds good to me if there's concern we'll want them later.  Still gets us into a much simpler state over all, and we can always remove more later if we decide we don't need it.

**Comment by jg18** [comment]
Ok, I've fixed the net_addr struct format and the TCP/IPX selector buttons. Anything else that needs to be addressed?

**Pull request merged**
