### PR TITLE
Add correct argument to printf format string.

### PR DESCRIPTION
**Pull request by Echelon9**
Fixes Issue #257.

### CODE REVIEW

**Comment by MageKing17** [comment]
Can't we fix the nonsensical grammar at the same time?

**Comment by Echelon9** [comment]
What would you propose? I'm not familiar with how this feature is actually used.

Simple:
```
-"Ships %s is a copy, but does not use the ship copy name extension."
+"Ship %s is a copy, but does not use the ship copy name extension."
```

Alternative:
```
-"Ships %s is a copy, but does not use the ship copy name extension."
+"Ships %s are copies, but do not use the ship copy name extension."
```

**Comment by MageKing17** [comment]
The SIF_SHIP_COPY flag (tied to the "ship copy" ship flag) means that the ship is considered a copy of another ship (exclusively used for purposes of scoring so that e.g. "SB Nahema#Special" would count as an "SB Nahema"). In order to know what ship it should count as, FSO looks for the hash symbol. If the name up to that point doesn't match anything, you get the warning on line 4275 (`"Ship %s is a copy, but base ship %s couldn't be found."`). If the hash symbol couldn't be found at all, you get this warning. Since this warning is somewhat unclear in addition to being grammatically incorrect, I'd like to suggest something along these lines (although perhaps this is a bit *too* verbose):

```
Warning(LOCATION, "Ship %s is defined as a copy (ship flag 'ship copy' is set), but is not named like one (no '#'). As a result, could not determine what ship it's supposed to be a copy of.", sip->name);
```

Perhaps it would make sense to be able to specify the name of the ship it should be treated as a copy of, if for some reason there's a good reason for the two to be named differently without showing up as different when it comes to scoring.

**Comment by Echelon9** [comment]
Updated the PR with the key parts of your description (would at least be sufficient for me if I saw it for first time, and provides enough information to know where to look).

The changes suggest in your final paragraph are perhaps better dealt with in a separate refactor. I'm keen at this first stage to correct the demonstrably incorrect format string.

**Pull request merged**
