### PR TITLE
Add flag for star gamma correction

### PR DESCRIPTION
**Pull request by Baezon**
Follow-up for #5222.

### CODE REVIEW

**Comment by PhantomHoover** [comment]
By the way, as discussed on Discord, I think we should avoid this approach in favour of just having a single acceptable behaviour for retail starfields, such as just making them uniformly brighter.

**Comment by The-E** [comment]
Yeah, agreed with PH there. The retail behaviour was so obviously wrong that "disable retail stars, use a skybox" became the de facto standard amongst mission creators, the original gamma correction change made them usable again, and this change here just turns the clock back half way.

**Comment by Baezon** [comment]
What exactly do you suggest? The ability to set their color beyond 255 or whatever, so they'd stay bright even when moving?

**Comment by The-E** [comment]
Yes. The basic behaviour of motion-blurred stars retaining their overall brightness should be kept; what's needed here (I think) is properly integrating them into the render pipeline as actually "bright" objects, i.e. objects subject to tonemapping and bloom.

**Comment by Baezon** [comment]
After discussion, I think it's agreed a flag, at least, is not the best way to approach this problem.

**Pull request closed without merging**
