### PR TITLE
Adding customizable pain flash and shield pain flash settings

### PR DESCRIPTION
**Pull request by AxemP**
Adds a way to lessen/intensify the red pain flash effect when you get hit with $Generic Pain Flash Factor.

Also adds a $Shield Pain Flash Factor that causes a similar effect when the player's shields are hit. Flash color is based off of the ship class shield color. Positive values here will cause the effect to start at full intensity at full shields and go to next to no intensity at zero shields. Negative values will cause no effect at full shields and full effect at no shields.

### CODE REVIEW

**Comment by MageKing17** [comment]
No way to have different factors for different ships?

**Comment by Goober5000** [comment]
Is that really something we want to do?  I mean, customization is nice, but we already have a ton of options we can configure.  Changing this on a per-ship class basis seems to be at an unnecessarily low level of detail.

**Comment by AxemP** [comment]
My thought is that something like this should be a mod-wide setting. The player should expect the same level of pain feedback across any ship, so having it apply to all ships the same seemed like the best idea.

**Comment by MageKing17** [comment]
I was actually thinking that someone might want different species' ships to behave in different ways (e.g. give Terran ships a positive factor, but the Terran Mara a negative one). It's not like I was saying that the game_settings.tbl setting should be *removed*; I just don't see the harm in a ships.tbl override of the global default set in the mod table. We can, of course, wait for somebody to actually request this functionality before we go out of our way to implement it.

**Comment by AxemP** [comment]
To me that still sounds pretty confusing to the player, but it shouldn't be hard to add overrides like that. Most of the work is already done, just a matter of adding the overrides if someone else wants to add them in. :)

**Pull request merged**
