### PR TITLE
Changes the "Object rotated too far" assertion to a log message

### PR DESCRIPTION
**Pull request by The-E**
As per discussion for PR #1171, only without the bad rebase.

### CODE REVIEW

**Comment by chief1983** [comment]
I know we didn't want to have this keep breaking the game, but an mprintf isn't even a halt, which is what would be required to fix this.  I would have thought a warning, which is only hit in debug builds anyway, would be more useful for fixing the issue if it happens to a dev?  And if it is happening to a modder often, there is probably something to fix there too.

**Comment by The-E** [comment]
That's where I disagree. As far as I can tell, there is no good definition of what "too far" means in context. I am pretty much convinced that whatever error this was designed to catch is no longer fatal, and as a result, I see it pop up more as a false positive than anything else.

What I'm trying to say is, if you're running into a physics issue, you are far more likely to see it pop up in gameplay than you are to see this assert fire; for us coders, the log message is enough of a starting point to work out the error, but for someone who isn't, and who is just hitting this error because its underlying assumptions are faulty, it's a red herring.

**Comment by chief1983** [comment]
That's all I'm confused on, how is the log message enough to aid a coder when the event in question has passed?

**Comment by The-E** [comment]
Because we can set a breakpoint at the point where it's firing after we've confirmed that something is actually going wrong. I don't see how interrupting gameplay for what is most likely to be a false positive is helping things.

**Pull request merged**
