### PR TITLE
[fix/nat_multiplayer] Fix for multiple users behind a NAT

### PR DESCRIPTION
**Pull request by chief1983**
Vestigare's submitted patch for allowing multiple users behind a NAT to connect to a remote standalone.  See http://www.hard-light.net/forums/index.php?topic=88971.0 for more detail.  Just putting this out to hopefully get a little more review, I had the patch sitting on my desktop and it's been purged from the thread since, don't want it to disappear forever.

### CODE REVIEW

**Comment by Echelon9** [comment]
I'll give this a test too with my OS X and Linux standalones. Am keen to get the multiplayer code improved a tad.

**Comment by chief1983** [comment]
Unfortunately I don't think I can get standalone running on my VPS due to restricted hard drive space, so I can run one in my basement, but then I only have one computer available outside of the basement to test connecting _to_ that standalone...if you set up a standalone I can get several clients connecting to it from my house behind my NAT probably.

**Comment by chief1983** [comment]
Hmm, just realized that with a second router I could set up a second NAT in my house for FS2 testing.  And I have a router I've been meaning to test anyway.

**Comment by chief1983** [comment]
I will run this on my home standalone server, if someone could attempt to connect to it with two computers behind the same NAT and see if it works?  I think the code only needs to be applied to the standalone side but it couldn't hurt to make sure it's on the clients too.

**Comment by chief1983** [comment]
Actually since I have two macbooks at work while I transfer my old files to my new one, I might be able to pull off this test myself.  But anyone else is welcome to try in case they can beat me to it.

**Comment by chief1983** [comment]
Verified, that this appears to have fixed this issue.  Both my Macbooks on my office NAT were able to connect to my standalone running at home.  Still can't join the lobby chat together, but they do both seem to be able to find the games on FS2NetD.  The lobby chat should probably remove the IP restriction at some point, but for now this definitely fixes the bug in the standalone.

**Comment by Goober5000** [comment]
I was about to merge this, since chief1983 verified the fix and I reviewed the patch just now.  It's perfectly merge-able as-is.  However, the psnet_same function is unnecessarily clunky.  This version would accomplish the same thing:

return !memcmp(a1->addr, a2->addr, 6) && a1->port == a2->port;

**Comment by chief1983** [comment]
Updated with the simplified return line.

**Comment by Goober5000** [comment]
Cool cool cool.

**Pull request merged**
