### PR TITLE
Clearer Paste function names and saner defaults

### PR DESCRIPTION
**Pull request by qazwsxal**
Fix for #4228

### CODE REVIEW

**Review by Goober5000 — CHANGES_REQUESTED** [review]
As I said in the issue, the Ctrl+V shortcut belongs with the original paste, not the Add Paste.  More importantly, this PR breaks a lot of things.  First, the `ID_EDIT_PASTE` and `ID_EDIT_PASTE_SPECIAL` should keep their original meanings, or at the very least, be named appropriately.  The menu change removes the separation of items that was added to reduce accidental misclicks.  And the change to the shortcut handling breaks the stay-on-node behavior that is needed for repeated keypresses.

**Comment by qazwsxal** [comment]
Happy to re-order menu items back to their originals and have done so in the most recent commit. Unfortunately, `ID_EDIT_PASTE` and `ID_EDIT_PASTE_SPECIAL` are defined by the ATL/MFC library. I believe this boils down to the same semantic issue present in the original FR. The majority opinion is that the expected behaviour of a CTRL+V (the "normal" paste) operation is to add clipboard content without overwriting any existing data.
I am unable to reproduce the "stay on node" behaviour breakage, repeatedly add-pasting with CTRL+V is adding new nodes underneath without moving the selected node. I'm also not sure how this might have been introduced, as the only changes are function calls being swapped over without any editing of the calls themselves.

**Review by Goober5000 — COMMENTED** [review]
I would suggest "Paste (Add Child)" instead of "Paste (Below)".

The current version of the code looks like it should work properly with regards to repeated Add Paste actions, although I would have just edited the keys instead of moving code around.

The original request dealt with just the shortcut keys, but this PR (although it fixes the separation) nevertheless swaps the destructive and non-destructive menu items.  This breaks muscle memory precedent.

**Comment by EatThePath** [comment]
> The original request dealt with just the shortcut keys, but this PR (although it fixes the separation) nevertheless swaps the destructive and non-destructive menu items. This breaks muscle memory precedent.

For what it's worth I would agree that this is probably undesirable. It's a bit awkward for new user accessibility, but unlike the hotkey this *is* a 20 year old usage pattern that probably should be kept unless doing a truly sweeping UI overhaul.

**Review by Goober5000 — APPROVED** [review]
This is acceptable.

**Comment by EatThePath** [comment]
For the record I also am good with this outcome from an interface perspective, though I'm not equipped to review the actual MFC code

**Pull request merged**
