### PR TITLE
Standalone fixes/optimizations

### PR DESCRIPTION
**Pull request by notimaginative**
Various fixes and optimizations for standalone servers, plus minor general fixes.

- reduces memory usage for standalones 35-40 MB by not initializing unneeded stuff
- fix crash on standalone reset if level has never loaded
- fix small portfwd memory leak

### CODE REVIEW

**Comment by notimaginative** [comment]
@asarium Please check that I didn't do anything too weird with the particle stuff. I tested it all pretty well but I'm not too familiar with that newer code. All of the particle changes are in the single commit (second from top) so you should be able to check it pretty easily.

**Review by asarium — APPROVED** [review]

**Comment by asarium** [comment]
Seems good to me.

**Comment by notimaginative** [comment]
Hmm, font related changes are causing a problem. All of the font stuff takes 4+ MB and is otherwise useless on standalones, but it's difficult to disable entirely. I tried to cheat a bit by not initializing the path stuff, which saves 2+ MB, but the lack of error handling causes null ptr crashes.

Have to figure out if wasting that RAM is worth a proper fix or not.

**Comment by notimaginative** [comment]
@Goober5000 If you've got some time I'd appreciate a second opinion on this before it gets merged.

**Comment by Goober5000** [comment]
@notimaginative I'll take a look later today.

**Review by Goober5000 — APPROVED** [review]
Yup, looks good to me.

**Pull request merged**
