### PR TITLE
Add Game Option to refresh selected weapon in loadout

### PR DESCRIPTION
**Pull request by wookieejedi**
This PR adds an option to always ensure the viewed weapon is one that can actually be on the selected ship when first clicking on the weapon loadout.

If you go to the loadout in the briefing and view the weapons on your ship, then go and change your ship class and go back to the weapon loadout screen, you will see that the weapon shown in the window on the right side is from your very first viewing before you changed your ship class. Displaying a weapon not allowed on a ship by default can be confusing to players, especially on mods like FotG where most ships have unique weapons.

The player can still of course click on a non-allowed weapon to view it, but with this PR the player will be initially shown a selected weapon that is allowed on the ship when opening the loadout editor.

Tested and works as expected.

### CODE REVIEW

**Review by Goober5000 — CHANGES_REQUESTED** [review]
This seems like a kludge.  If there's an actual bug, we should find the root cause and fix it, not add an option to do a certain behavior sometime and another behavior other times.

Do we have a github issue for the bug in question?  And do we have a consistently reproducible test case?

**Comment by wookieejedi** [comment]
Ah so I wouldn't really call it a bug. All that is happening is that the game remembers what weapon you had previously clicked on (it does not try to apply it to the ship or anything). 

To view what is happening, just open the weapon loadout, click on a weapon, switch back to the ship loadout and change ships. Then go back to the weapon loadout. You'll see the weapon loadout will continue to show the weapon you had selected the first time. Again, not a bug, just for mods with lots of custom ship weapon combinations it would be very useful, especially for new players, if the weapon loadout view forgot it's old selection and instead showed the current weapons on the selected ship by default.

**Review by Goober5000 — COMMENTED** [review]
Oh, I see what you mean,  Ok, that makes sense.

In that case, why not move the option to immediately before `$Weapons inherit parent collision group:`?  That would group it with the other ship and weapon selection options.

(Long term, we should probably upgrade mod_table to handle parsing its options in any order, the same as ai_profiles does.)

**Comment by wookieejedi** [comment]
Good idea, just updated the position.

**Review by Goober5000 — APPROVED** [review]
Looks good!

**Pull request merged**
