### PR TITLE
Upped MAX_SHIP_CLASSES to 500

### PR DESCRIPTION
**Pull request by The-E**
Because apparently, this is a thing we will need to have in Blue Planet.

Yes, I know it's better to remove the limit completely, which I am working on. But until that's finished, we need this to continue work.

### CODE REVIEW

**Comment by chief1983** [comment]
I seem to remember a comment back when the inferno limit was bumped that the limit would absolutely never be bumpable again.  Or maybe that was a different limit, like max objects in a mission or something?

**Comment by MageKing17** [comment]
Are you thinking of `MAX_SHIP_CLASSES_MULTI`? Trying to bump that one would lead to cascading problems with packet size, IIRC.

**Comment by chief1983** [comment]
How could one be higher than the other, unless it just stops reading ships from the table in multi after reaching the limit?

**Comment by Goober5000** [comment]
You're on the right track.  This is what happens:
```
	// check if networking should be disabled, this could probably be done later but the sooner the better
	// TODO: remove this when multi is fixed to handle more than MAX_SHIP_CLASSES_MULTI
	if ( Ship_info.size() > MAX_SHIP_CLASSES_MULTI ) {
		Networking_disabled = 1;
	}
```

**Comment by Goober5000** [comment]
A quick look through the code reveals no showstoppers.  The only potential "gotcha" might happen if a player is playing through a campaign with the higher ship class limit and decides to run a build with the lower ship class limit.  But it looks like the new pilot code accounts for this -- c.f. `pilotfile::csg_read_info()` in csg.cpp.

**Comment by The-E** [comment]
Can this be merged then?

**Comment by MageKing17** [comment]
May as well bite the bullet.

**Pull request merged**
