### PR TITLE
Final fix for reflections

### PR DESCRIPTION
**Pull request by DahBlount**
The first fix was not needed. Simply inverting the matrix used by the ENVMAP vertex shader causes reflection to work correctly.
<a href="http://imgur.com/PQzDla0"></a>

### CODE REVIEW

**Comment by SamuelCho** [comment]
So there are other ways to get the inverse of the mvp matrix without having to do a inverse operation in the shader which I think is costly to do. I already pass in a world matrix for clipping and shadow mapping which should mathematically be the inverse of the mvp. Can you use that instead? Or calculate it in the code then pass it in via uniform?

**Comment by DahBlount** [comment]
I'll see what I can do.

**Comment by DahBlount** [comment]
And I must be incompetent. I can't figure out how to do any of what you said. Using the world matrix, I get reflections that are flat in color and go around the entire model. Inverting the matrix myself and passing as a uniform causes reflections to be upside down.
Any idea what I could be doing wrong?

**Comment by DahBlount** [comment]
Okay, fixed environment reflections for real now. Added a function to invert a matrix4 and fixed the transfer of `GL_MODELVIEW_MATRIX` to `GL_env_texture_matrix` as it was inverting the Up vector of that matrix which flips reflections upside down. Everything is in order and once the checks pass it should be ready to merge.

**Comment by chief1983** [comment]
And  the new call to vm_inverse_matrix4 won't be a significant performance penalty?

**Comment by DahBlount** [comment]
Hopefully not, it's only called once and it's also the only way to invert a matrix4 that I know of. It goes without saying that my system performs very well at high resolutions regardless, so if we wanted to get a comprehensive performance test, someone with an older system would need to run a build based off this.

**Comment by asarium** [comment]
The `vm_inverse_matrix4` function should be pretty fast. For the most part it's just a lot of floating point operations which should be reasonably fast.
The previous iterations could cause performance issues because the matrix was inversed in every shader invocation instead of only once when setting the view matrix was set.

**Comment by DahBlount** [comment]
I bumped up my resolution to 3840x2160 and did some experimentation with nothing outside of the usual FPS drops, so I'd say for sure that it shouldn't have any detriment on performance as is.

**Comment by z64555** [comment]
LGTM with current commits

**Pull request merged**
