### PR TITLE
Exclude dead subsys from targeting

### LINKED ISSUE #3613: "Current target, any subsystem" multilock mode targets destroyed turrets
This applies both to holding existing locks and creating new ones. Not sure if the same is true of non-turret subsystems. I have not historically used this mode that much, so I suspect this isn't a new flaw, but it doesn't seem like it's likely to be the intended functionality.

### PR DESCRIPTION
**Pull request by BMagnu**
Fixes #3613.
Turns out ``weapon_multilock_can_lock_on_subsys`` just never checked for HP...

### CODE REVIEW

**Review by Goober5000 — APPROVED** [review]

**Review by Baezon — CHANGES_REQUESTED** [review]
Hold on now, I'm not sure this is a mistake. Continued in #3613

**Review by Baezon — APPROVED** [review]
Although, given I'm not sure this can really be classified as a bug anymore, I'm not sure we should merge this until after the stable.

**Comment by BMagnu** [comment]
Agreed.

**Comment by EatThePath** [comment]
I would like to argue against the not-a-bug decision, but rather than do it here I posted my pamphlet on the matter over in #3613

**Comment by EatThePath** [comment]
In any case I tested this branch, and it does appear to work at keeping you from *acquiring* locks on dead subs, it doesn't do anything about locks you already have on subsystems when they die

**Comment by BMagnu** [comment]
Flipped flag after discussion.
This now changes default behaviour, with the flag to opt out of it and restore original behaviour.
With this, this PR will wait for 21.4 to release

**Pull request merged**
