### PR TITLE
Generate a JSON encoded manifest of binaries

### PR DESCRIPTION
**Pull request by IssMneur**
Generate a JSON encoded manifest of the binaries that are distributed to
the users so that the launcher can more readily ID the binaries and ensure
that all of the shared objects are present to allow the engine to run

Current known defects:
- Not integrating correctly with the build pipeline
- It currently does not find the SDL.dll that is being generated

Questions:
-  Do we want to include the pdbs in the manifest for the debug builds?
- CMake doesn't seem to have an easy native way to get the filesize.  [This extension](https://github.com/sakra/FileInformation) will do it if we want to include that, otherwise two hashes makes a good substitute for the file size.

Currently the manifest looks something like this:

```
{
        "v": 1,
        "major": 3,
        "minor": 7,
        "build": 5,
        "revision": 0,
        "isa": "x86",
        "isa_extra": "AVX",
        "extra": "",
        "config": "Debug",
        "files": {
                "fs2_open_3_7_5_AVX-DEBUG.exe": {
                        "sha1": "05a264bbcfd68bfa5d3efb912a9c947a806e837e",
                        "sha256": "e24e1a9cc4125b3a0a1e1207fa9e076581202ff1c81b89013489508cffed94f7"
                },
                "fred2_open_3_7_5_AVX-DEBUG.exe": {
                        "sha1": "079300f4b72b1336e4ff57fbfbd077d73cdca361",
                        "sha256": "b61838a29a219b382ce6f210df13198e072a73f6cfc0a94731b4fd7ef322d2b4"
                }
        }
}
```

### CODE REVIEW

**Comment by JohnAFernandez** [comment]
Is there any hope of this ever getting merged?

**Comment by Goober5000** [comment]
> Is there any hope of this ever getting merged?

It has the "unfinished" label, so presumably it was never approved because @IssMneur was still working on it.

Practically speaking, it could still be reviewed and approved.

**Comment by PhantomHoover** [comment]
> Practically speaking, it could still be reviewed and approved.

No it can't, it has a merge conflict that makes it impossible to merge without modification. This should just be closed and if IssMneur happens to come back and fixes it up we can easily reopen it.

**Comment by Goober5000** [comment]
The merge conflict is very small and should not be difficult to resolve for anyone familiar with the build system.

Better arguments for closure are that a) this is unfinished and IssMneur is inactive; b) this is primarily useful for wxLauncher.

I'm in favor of closing it.

**Comment by Goober5000** [comment]
Closing unless @IssMneur returns.

**Pull request closed without merging**
