### PR TITLE
Don't compare NULL with integer

### PR DESCRIPTION
**Pull request by asarium**
As noted in #236, `NULL` was being compared with an integer value (`SDL_TimerID`) which caused issues on FreeBSD.

### CODE REVIEW

**Comment by chief1983** [comment]
This should address the comparison issue (if 0 works here) but there is also two or three places with NULL being assigned to an SDL_TimerID type.  My build fail log from yesterday is at http://pastebin.com/fNb9Y6wv

**Comment by asarium** [comment]
According to the documentation SDL_AddTimer returns `NULL` on failure which is pretty misleading as SDL_TimerID is not a pointer...
With the newest changes all errors in your log should be resolved.

**Comment by MageKing17** [comment]
Does this mean that all remaining instances of NULL are referring to a null pointer? If so, then could this also replace them with nullptr?

**Comment by asarium** [comment]
I see no reason to replace all instances as that would likely cause issues. All new code should use nullptr though.

**Comment by The-E** [comment]
Honestly, if we can use it, we should.

**Comment by asarium** [comment]
Sure but simply searching and replacing `NULL` in the entire code base will probably cause issues that I don't want to to deal with...

**Comment by chief1983** [comment]
Was afraid of this.  It bails out on each file, so it got through this one and found three more in rtvoice.cpp.
```
sound/rtvoice.cpp:97:23: error: assigning to 'SDL_TimerID' (aka 'int') from incompatible type 'nullptr_t'
                Rtv_record_timer_id = NULL;
                                    ^ ~~~~
sound/rtvoice.cpp:109:23: error: assigning to 'SDL_TimerID' (aka 'int') from incompatible type 'nullptr_t'
                Rtv_record_timer_id = NULL;
                                    ^ ~~~~
sound/rtvoice.cpp:198:23: error: assigning to 'SDL_TimerID' (aka 'int') from incompatible type 'nullptr_t'
                Rtv_record_timer_id = NULL;
                                    ^ ~~~~
```
I think I can clean these up following the same concept though, I will see what I can do.

**Comment by chief1983** [comment]
This also now fixes a warning in just about every file on FreeBSD about BYTE_ORDER and friends already being defined.  Seems SDL_endian.h leads to endian.h inclusion on FreeBSD which defines those for us.

**Pull request merged**
