### PR TITLE
First pass at removing cmdline_nohtl

### PR DESCRIPTION
**Pull request by The-E**
This doesn't do anything except remove all usages of Cmdline_nohtl. Particular care should be taken to examine the changes in shiphit.cpp, there is a behaviour change here and I do not know off-hand what the correct behaviour should be (just why that behaviour was keyed by Cmdline_nohtl eludes me).

### CODE REVIEW

**Comment by chief1983** [comment]
After some investigation, the nohtl check for the shockwave world_hitpos assignment was added in c2716d4ee879e22671971d6be5a165d21bccef4b.  taylor believed this was the best way to prevent some kind of Error() from occurring in HTL mode.  Deleting this block would retain this solution, restoring it might be worth it for a bit to see if the Error still happens or if we can find an alternative fix for it.

**Comment by SamuelCho** [comment]
Do you think you can hold off on this? I was planning on removing No_htl in conjunction with my materials integration code and doing it separately and trying to integrate that with this pull request would be a nightmare.

**Comment by MageKing17** [comment]
I have no problem with that as long as the command-line option gets deprecated.

**Comment by The-E** [comment]
Sure. I'll close this PR and open another one that just deprecates the cmdline switch, without further code changes.

**Pull request closed without merging**
