### PR TITLE
Remove DirectX remains

### PR DESCRIPTION
**Pull request by Echelon9**
Per internal discussion, this PR removes the remaining DirectX 8.1 SDK references.

These are no longer needed with the fs2open engine to ease compilation, without setting up a DirectX SDK install locally. The engine has been OpenGL only for some time.

**NOTE**: Before merging this commit will need a Windows dev to supply updated project files.

### CODE REVIEW

**Comment by chief1983** [comment]
Doesn't non-Antipodes Windows need DirectInput?  And does SDL Windows use lower level calls or does it wrap DirectInput as well?

**Comment by The-E** [comment]
Chief is correct. In the current master branch, dxInput is used to read mouse and joystick input. Removing it is therefore not an option.

**Comment by Echelon9** [comment]
Erghh, that is horrible.
Okay, well it really should be a #define to the locally installed SDK, rather than us redistributing it, but history is what history is.
Bring on Antipodes and its proper cross-platform SDL2 middleware I say.

**Comment by chief1983** [comment]
And DirectInput is for sure not a dependency of SDL on Windows?  I don't know what SDL uses as an input interface on that platform, but the directx folder is still in the antipodes branch.

**Comment by asarium** [comment]
SDL doesn't depend on having a DirectX SDK installed, I removed the SDK files in my CMake branch and FSO still compiles perfectly well.

**Comment by chief1983** [comment]
Ah, from what I found via Google, SDL 1.2 did wrap DirectInput but since the DInput API is deprecated they have stopped doing that in SDL2.

**Comment by chief1983** [comment]
So do we want to go ahead and close this or re-purpose it for removing the DirectX stuff in Antipodes?

**Comment by Echelon9** [comment]
I'll close the PR and repurpose.

**Pull request closed without merging**
