### PR TITLE
Mantis 3160: Only set processor affinity if a commandline flag is present

### PR DESCRIPTION
**Pull request by asarium**

### CODE REVIEW

**Comment by Goober5000** [comment]
Why not allow the user to specify the affinity on the command line?

**Comment by The-E** [comment]
I think specifying bit flags is a bit unwieldy.

**Comment by asarium** [comment]
The current way of specifying the bitset should be sufficient given that is will be used very rarely.

**Comment by The-E** [comment]
Agreed.

**Comment by Goober5000** [comment]
Rarely or not, it would be valuable to have an optional argument to the command line parameter so the user doesn't need to mess with the registry.  The scenario where this is likely to be used is a troubleshooting session with a newbie user over IRC.

**Comment by MageKing17** [comment]
In the most likely usage scenario for this option of the user having problems with affinity set to more than one processor, the default value of "set affinity to the second core" (which wasn't changed by this PR) will fix it.

**Comment by asarium** [comment]
The easiest way to set the affinity for quick troubleshooting is still the task manager which is much nicer than having to mess with a commandline argument.

**Pull request merged**
