### PR TITLE
Add Weapon Random Delay

### PR DESCRIPTION
**Pull request by DahBlount**
New weapon entries:
+Max Delay: float
+Min Delay: float

This also removes unneeded typecasting.

### CODE REVIEW

**Comment by DahBlount** [comment]
Does this solve all the issues?

**Comment by z64555** [comment]
Eh, the PR's commit history looks suspicious. What does your logs say on your local repo?

**Comment by DahBlount** [comment]
The log on my end lists my random fire delay commits twice as well. What needs to be done here?

**Comment by chief1983** [comment]
I'm not sure why it shows 8 files changed, I'm only showing 3 different compared to current master.  My guess is that somehow there was a merge conflict and the commits had to be reapplied.  The diff of the branch against current master looks correct to me, but I might suggest rebuilding the branch to have a cleaner history.

**Comment by DahBlount** [comment]
In what manner should I rebuild the branch?

**Comment by chief1983** [comment]
That's what I would do in this case probably.  Not sure how to make that reuse this PR though.  Maybe someone else can suggest something for that.

**Pull request closed without merging**
