### PR TITLE
Make new registry configurable on commandline

### PR DESCRIPTION
**Pull request by asarium**
The new registry handling also breaks the settings for some people so I added a commandline option which selects which path is used.

This issue should be added to the "Known issues" section of the release post so users know how to fix this issue.

### CODE REVIEW

**Comment by chief1983** [comment]
Between the code and the comments, this functionality goes by three different names:  fix registry, alternate registry path, and old registry path.  It'd be nice if all of these references agreed with each other.  I'm partial to 'old registry path' myself.

**Comment by asarium** [comment]
Well `-alternate-registry` or something like that doesn't fit in the option string so I used `-fix-registry` instead. "Old registry" is also not correct because the paths should be the same because they access the same key in the registry. I guess I could change the comment to use "original registry path".

**Comment by asarium** [comment]
@chief1983 I made some comment changes. Are they sufficient?

**Comment by asarium** [comment]
Changed code has been reviewed by @The-E.

**Pull request merged**
