### PR TITLE
Use prebuilt FreeType library on Mac

### PR DESCRIPTION
**Pull request by jg18**
Requires the FreeType static library for Mac found in [scp-prebuilt repo's PR 7](https://github.com/scp-fs2open/scp-prebuilt/pull/7).

Fixes Issue #2370 .

### CODE REVIEW

**Comment by JohnAFernandez** [comment]
For #2370

**Comment by jg18** [comment]
More generally, we should ensure our compliance with the sections of "The FreeType Project LICENSE" about requiring attribution:

"You may not pretend that  you wrote this software.  If you use it, or  only parts of it,  in a program,  you must acknowledge somewhere  in  your  documentation  that  you  have  used  the FreeType code. (`credits')"

"Redistribution in binary form must provide a  disclaimer  that states  that  the software is based in part of the work of the FreeType Team,  in  the  distribution  documentation.  We also encourage you to put an URL to the FreeType web page  in  your documentation, though this isn't mandatory."

**Review by JohnAFernandez — COMMENTED** [review]
Was this tested on Windows as well?

**Comment by jg18** [comment]
Just tested on Windows using Release and Fast Debug builds and they pass a sanity check. Started up "The Sixth Wonder" from FS2 campaign and loads/runs fine AFAICT.

Hoping to get feedback from at least one Mac player, sent a player a test build I made. Perhaps @chief1983 could try to build/run on Mac as well??

**Review by asarium — APPROVED** [review]

**Comment by JohnAFernandez** [comment]
Chief is on vacation currently.  Wish I had a mac with FSO to test.

**Comment by jg18** [comment]
Turns out the Mac player whom I was hoping would test doesn't have FS2, and Knossos's custom FSO build selection is [currently broken on Mac](https://github.com/ngld/knossos/issues/221). Guess we'll need to wait until chief has a chance to try this.

**Comment by chief1983** [comment]
This appears to work fine.  Uninstalled freetype in homebrew, reran configure and xcodebuild, moved the app (didn't pass signing but otherwise built fine) into the Freespace folder, and it starts just fine.

However, as soon as I selected a pilot and entered the mainhall, I saw severe graphics issues.  The remainder of the game only wants to render on the bottom left corner of the screen.  I had merged in the latest master, and compared this behavior to the latest nightly which doesn't exhibit any such problems (of course I did have to reinstall freetype in homebrew for that).  It's possible that some commit since the 11/15 nightly is the culprit.  I might try going to back the original PR hash and not merging in master to check that, or it could be something in my specific build that happened.

**Review by chief1983 — APPROVED** [review]

**Comment by chief1983** [comment]
After some thought, I have a feeling this is related to the high-DPI retina display on the particular Macbook Pro.  The problem doesn't happen with nightly builds (made using older Xcode on an older platform, etc) but that might be something to ponder.  I had just updated to Xcode 12.2 and was on 10.15.7 with the latest security update just installed as well.  Haven't upgraded to Big Sur anywhere yet.  I tried Release and Debug builds with the Xcode project file generator, and no other special config options.  This may warrant its own ticket at this point, since it may affect anyone else with newer hardware and up to date software who wishes to contribute.

**Pull request merged**
